## Real estate price prediction (Python_for_data_Science_project)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = 100

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.shape

(10000, 20)

### train_test_split

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
train, valid = train_test_split(data, test_size=0.2, random_state=42)

In [6]:
train.shape, valid.shape

((8000, 20), (2000, 20))

#### Prepare data

In [7]:
train.head(10)

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
9254,12473,58,1.0,65.271225,62.798045,1.0,3,1.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,210849.693542
1561,14050,146,2.0,45.091598,43.816601,1.0,5,18.0,2017,0.236108,B,B,16,3893,27,NaN,3,10,B,201549.998077
1670,3779,5,1.0,34.463114,20.561823,5.0,3,5.0,1960,0.150818,B,B,16,3433,4,2643.0,4,5,B,158433.168775
6087,3762,90,3.0,61.931107,46.126389,5.0,4,5.0,1966,0.265089,B,B,37,5288,0,1937.0,3,2,B,220194.818430
6669,358,1,1.0,42.670840,NaN,1.0,8,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,125834.270291
5933,6519,94,2.0,50.392833,3.249569,1.0,4,12.0,1973,0.521867,B,B,25,6149,0,NaN,0,0,B,157822.338178
8829,6076,27,1.0,48.599513,NaN,1.0,8,1.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,159768.113188
7945,12584,23,1.0,41.515204,NaN,1.0,12,25.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,118200.065926
3508,4144,23,1.0,42.705836,NaN,0.0,5,4.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,92290.968476
2002,15303,48,3.0,83.866174,NaN,1.0,26,1.0,2014,0.041125,B,B,46,9515,5,NaN,1,10,B,468595.039049

In [8]:
#plt.scatter(train['Rooms'], train['Square']);

In [9]:
#plt.scatter(train['Rooms'], train['Price']);

In [10]:
train['Ecology_2'].unique(), train['Ecology_3'].unique(), train['Shops_2'].unique()

(array(['B', 'A'], dtype=object),
 array(['B', 'A'], dtype=object),
 array(['B', 'A'], dtype=object))

In [11]:
train.columns

Index(['Id', 'DistrictId', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare',
       'Floor', 'HouseFloor', 'HouseYear', 'Ecology_1', 'Ecology_2',
       'Ecology_3', 'Social_1', 'Social_2', 'Social_3', 'Healthcare_1',
       'Helthcare_2', 'Shops_1', 'Shops_2', 'Price'],
      dtype='object')

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 9254 to 7270
Data columns (total 20 columns):
Id               8000 non-null int64
DistrictId       8000 non-null int64
Rooms            8000 non-null float64
Square           8000 non-null float64
LifeSquare       6299 non-null float64
KitchenSquare    8000 non-null float64
Floor            8000 non-null int64
HouseFloor       8000 non-null float64
HouseYear        8000 non-null int64
Ecology_1        8000 non-null float64
Ecology_2        8000 non-null object
Ecology_3        8000 non-null object
Social_1         8000 non-null int64
Social_2         8000 non-null int64
Social_3         8000 non-null int64
Healthcare_1     4148 non-null float64
Helthcare_2      8000 non-null int64
Shops_1          8000 non-null int64
Shops_2          8000 non-null object
Price            8000 non-null float64
dtypes: float64(8), int64(9), object(3)
memory usage: 1.3+ MB

In [13]:
train.shape

(8000, 20)

In [14]:
train.describe()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Price
count,8000.000000,8000.000000,8000.000000,8000.000000,6299.000000,8000.00000,8000.000000,8000.000000,8.000000e+03,8000.000000,8000.000000,8000.000000,8000.000000,4148.00000,8000.000000,8000.000000,8000.000000
mean,8365.521625,50.493625,1.889125,56.267255,37.325501,6.37875,8.492375,12.623250,4.491580e+03,0.117770,24.729125,5358.405125,8.006500,1136.08703,1.313375,4.246375,214094.178589
std,4865.821409,43.691588,0.839297,20.381827,95.733053,31.84321,5.221240,6.812185,2.241661e+05,0.118239,17.609415,4016.879776,23.720008,1024.34165,1.489362,4.806018,92671.160116
min,0.000000,0.000000,0.000000,2.377248,0.370619,0.00000,1.000000,0.000000,1.912000e+03,0.000000,0.000000,168.000000,0.000000,0.00000,0.000000,0.000000,59174.778028
25%,4154.750000,20.000000,1.000000,41.745094,22.797476,1.00000,4.000000,9.000000,1.974000e+03,0.017647,6.000000,1564.000000,0.000000,325.00000,0.000000,1.000000,153996.751273
50%,8369.500000,36.000000,2.000000,52.549663,32.806379,6.00000,7.000000,13.000000,1.977000e+03,0.075424,25.000000,5285.000000,2.000000,900.00000,1.000000,3.000000,192152.769521
75%,12555.500000,75.000000,2.000000,65.931541,45.048935,9.00000,12.000000,17.000000,2.001000e+03,0.195781,36.000000,7287.000000,5.000000,1548.00000,2.000000,6.000000,249135.462171
max,16796.000000,209.000000,19.000000,604.705972,7480.592129,2014.00000,42.000000,117.000000,2.005201e+07,0.521867,74.000000,19083.000000,141.000000,4849.00000,6.000000,23.000000,627525.072788

In [15]:
# Определим как каждый из признаков коррелирует с признаком 'Price'

corr_matrix = train.corr()
corr_matrix['Price'].sort_values(ascending=False)

Price            1.000000
Rooms            0.550467
Square           0.537633
Social_1         0.267954
DistrictId       0.264687
Helthcare_2      0.254505
Social_2         0.243379
Shops_1          0.184092
Floor            0.129984
Healthcare_1     0.128809
HouseFloor       0.086351
LifeSquare       0.075584
Social_3         0.074765
KitchenSquare    0.023048
Id               0.021515
HouseYear        0.004829
Ecology_1       -0.061364
Name: Price, dtype: float64

#### Обработка данных

Теперь, когда мы получили общее представление о данных датасета, устраним существующие в исходных данных аномалии, выбросы и пустоты.

##### Healthcare_1

In [16]:
train['Healthcare_1'].describe()

count    4148.00000
mean     1136.08703
std      1024.34165
min         0.00000
25%       325.00000
50%       900.00000
75%      1548.00000
max      4849.00000
Name: Healthcare_1, dtype: float64

In [17]:
train = train.drop('Healthcare_1', axis=1)

In [18]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 9254 to 7270
Data columns (total 19 columns):
Id               8000 non-null int64
DistrictId       8000 non-null int64
Rooms            8000 non-null float64
Square           8000 non-null float64
LifeSquare       6299 non-null float64
KitchenSquare    8000 non-null float64
Floor            8000 non-null int64
HouseFloor       8000 non-null float64
HouseYear        8000 non-null int64
Ecology_1        8000 non-null float64
Ecology_2        8000 non-null object
Ecology_3        8000 non-null object
Social_1         8000 non-null int64
Social_2         8000 non-null int64
Social_3         8000 non-null int64
Helthcare_2      8000 non-null int64
Shops_1          8000 non-null int64
Shops_2          8000 non-null object
Price            8000 non-null float64
dtypes: float64(7), int64(9), object(3)
memory usage: 1.2+ MB

In [19]:
def correct_healthcare_1(df):
    df = df.drop('Healthcare_1', axis=1)
    return df

##### HouseYear

In [20]:
train['HouseYear'].describe()

count    8.000000e+03
mean     4.491580e+03
std      2.241661e+05
min      1.912000e+03
25%      1.974000e+03
50%      1.977000e+03
75%      2.001000e+03
max      2.005201e+07
Name: HouseYear, dtype: float64

In [21]:
train['HouseYear'].value_counts()

1977        2131
2017         252
2016         247
2015         242
2014         165
1969         153
1970         152
2018         142
1971         138
1972         133
1968         132
1975         128
1976         128
1965         127
1974         126
1963         125
1964         125
1967         125
1973         121
1978         107
1966         103
1962         101
1979          91
1960          90
1983          89
1961          89
1982          88
1980          85
2005          82
1981          79
            ...
1952           9
1954           9
1953           7
1939           6
1950           6
1935           5
1937           5
1931           5
1918           4
1933           4
1938           4
1936           3
1919           3
1934           3
1932           2
1940           2
1948           2
1917           2
1951           2
1941           2
1942           2
1947           1
1930           1
1929           1
4968           1
1914           1
1928           1
1916           1
1912           1
20052011       1
Name: HouseYear, Length: 96, dtype: int64

In [22]:
ind_hy = train.loc[train['HouseYear'] > 2020, :].index
train.loc[ind_hy, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
4189,11607,147,2.0,44.791836,28.360393,5.0,4,9.0,4968,0.319809,B,B,25,4756,16,5,8,B,243028.603096
1497,10814,109,1.0,37.265070,20.239714,9.0,9,12.0,20052011,0.136330,B,B,30,6141,10,3,6,B,254084.534396

In [23]:
train.loc[(train['HouseYear'] > 2020) | (train['HouseYear'] < 1880), 'HouseYear'] = 1977

In [24]:
train.loc[ind_hy, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
4189,11607,147,2.0,44.791836,28.360393,5.0,4,9.0,1977,0.319809,B,B,25,4756,16,5,8,B,243028.603096
1497,10814,109,1.0,37.265070,20.239714,9.0,9,12.0,1977,0.136330,B,B,30,6141,10,3,6,B,254084.534396

In [25]:
train['HouseYear'].describe()

count    8000.000000
mean     1984.952125
std        18.364449
min      1912.000000
25%      1974.000000
50%      1977.000000
75%      2001.000000
max      2020.000000
Name: HouseYear, dtype: float64

In [26]:
def correct_houseyear(df):
    df.loc[(df['HouseYear'] > 2020) | (df['HouseYear'] < 1880), 'HouseYear'] = 1977
    return df

##### Rooms

In [27]:
train['Rooms'].describe()

count    8000.000000
mean        1.889125
std         0.839297
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max        19.000000
Name: Rooms, dtype: float64

In [28]:
#plt.scatter(train['Rooms'], train['Price']);

In [29]:
train['Rooms'].unique()

array([ 1.,  2.,  3.,  4.,  5., 19.,  0.,  6., 10.])

In [30]:
train['Rooms'].value_counts()

2.0     3111
1.0     2966
3.0     1784
4.0      117
5.0       14
0.0        5
19.0       1
10.0       1
6.0        1
Name: Rooms, dtype: int64

In [31]:
#Устраним количество комнат равных 0

In [32]:
ind_r_0 = train.loc[train['Rooms'] == 0, :].index
train.loc[ind_r_0, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
4366,456,6,0.0,81.491446,NaN,0.0,4,0.0,1977,0.243205,B,B,5,1564,0,0,0,B,212864.799112
1397,12638,27,0.0,138.427694,136.215499,0.0,4,3.0,2016,0.075424,B,B,11,3097,0,0,0,B,268394.744389
2269,7317,27,0.0,41.790881,NaN,0.0,13,0.0,1977,0.211401,B,B,9,1892,0,0,1,B,98129.976788
3911,770,28,0.0,49.483501,NaN,0.0,16,0.0,2015,0.118537,B,B,30,6207,1,1,0,B,217009.338463
4853,3224,27,0.0,2.377248,0.873147,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798

In [33]:
train.loc[(train['Rooms'] == 0) & (train['Square'] <= 50), 'Rooms'] = 1

train.loc[(train['Rooms'] == 0) & ((train['Square'] > 50) & (train['Square'] <= 100)), 'Rooms'] = 2

train.loc[(train['Rooms'] == 0) & ((train['Square'] > 100) & (train['Square'] <= 150)), 'Rooms'] = 3

train.loc[(train['Rooms'] == 0) & ((train['Square'] > 150) & (train['Square'] <= 250)), 'Rooms'] = 4

train.loc[(train['Rooms'] == 0) & ((train['Square'] > 250) & (train['Square'] <= 400)), 'Rooms'] = 5

train.loc[(train['Rooms'] == 0) & (train['Square'] > 400), 'Rooms'] = 6

In [34]:
train.loc[ind_r_0, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
4366,456,6,2.0,81.491446,NaN,0.0,4,0.0,1977,0.243205,B,B,5,1564,0,0,0,B,212864.799112
1397,12638,27,3.0,138.427694,136.215499,0.0,4,3.0,2016,0.075424,B,B,11,3097,0,0,0,B,268394.744389
2269,7317,27,1.0,41.790881,NaN,0.0,13,0.0,1977,0.211401,B,B,9,1892,0,0,1,B,98129.976788
3911,770,28,1.0,49.483501,NaN,0.0,16,0.0,2015,0.118537,B,B,30,6207,1,1,0,B,217009.338463
4853,3224,27,1.0,2.377248,0.873147,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798

In [35]:
#Устраним количество комнат больше или равно 6

In [36]:
ind_r_6 = train.loc[train['Rooms'] >= 6, :].index
train.loc[ind_r_6, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
1454,8491,1,19.0,42.006046,21.779288,7.0,17,17.0,2014,0.007122,B,B,1,264,0,0,1,B,78364.616704
2170,14003,99,6.0,59.414334,38.702244,6.0,7,9.0,1969,0.033494,B,B,66,10573,1,3,8,B,229661.964416
377,5927,57,10.0,59.056975,36.223072,10.0,22,22.0,2002,0.090799,B,B,74,19083,2,5,15,B,317265.323792

In [37]:
train.loc[(train['Rooms'] >= 6) & (train['Square'] <= 50), 'Rooms'] = 1

train.loc[(train['Rooms'] >= 6) & ((train['Square'] > 50) & (train['Square'] <= 100)), 'Rooms'] = 2

train.loc[(train['Rooms'] >= 6) & ((train['Square'] > 100) & (train['Square'] <= 150)), 'Rooms'] = 3

train.loc[(train['Rooms'] >= 6) & ((train['Square'] > 150) & (train['Square'] <= 250)), 'Rooms'] = 4

train.loc[(train['Rooms'] >= 6) & ((train['Square'] > 250) & (train['Square'] <= 400)), 'Rooms'] = 5

train.loc[(train['Rooms'] >= 6) & (train['Square'] > 400), 'Rooms'] = 6

In [38]:
train.loc[ind_r_6, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price
1454,8491,1,1.0,42.006046,21.779288,7.0,17,17.0,2014,0.007122,B,B,1,264,0,0,1,B,78364.616704
2170,14003,99,2.0,59.414334,38.702244,6.0,7,9.0,1969,0.033494,B,B,66,10573,1,3,8,B,229661.964416
377,5927,57,2.0,59.056975,36.223072,10.0,22,22.0,2002,0.090799,B,B,74,19083,2,5,15,B,317265.323792

In [39]:
train['Rooms'].unique()

array([1., 2., 3., 4., 5.])

In [40]:
#plt.scatter(train['Rooms'], train['Price']);

In [41]:
train['Rooms'].value_counts()

2.0    3114
1.0    2970
3.0    1785
4.0     117
5.0      14
Name: Rooms, dtype: int64

In [42]:
room_size = (train['Rooms'].value_counts() < (train['Rooms'].count() * 0.02)).astype(int).reset_index()
room_size.columns = ['Rooms', 'Large_flat']
room_size

   Rooms  Large_flat
0    2.0           0
1    1.0           0
2    3.0           0
3    4.0           1
4    5.0           1

In [43]:
def add_room_size(df, room_size):
    df = pd.merge(df, room_size, on='Rooms', how='left')
    df['Large_flat'] = df['Large_flat'].fillna(0)
    return df

In [44]:
train = add_room_size(train, room_size)

In [45]:
def correct_rooms(df):
    df.loc[(df['Rooms'] == 0) & (df['Square'] <= 50), 'Rooms'] = 1
    df.loc[(df['Rooms'] == 0) & ((df['Square'] > 50) & (df['Square'] <= 100)), 'Rooms'] = 2
    df.loc[(df['Rooms'] == 0) & ((df['Square'] > 100) & (df['Square'] <= 150)), 'Rooms'] = 3
    df.loc[(df['Rooms'] == 0) & ((df['Square'] > 150) & (df['Square'] <= 250)), 'Rooms'] = 4
    df.loc[(df['Rooms'] == 0) & ((df['Square'] > 250) & (df['Square'] <= 400)), 'Rooms'] = 5
    df.loc[(df['Rooms'] == 0) & (df['Square'] > 400), 'Rooms'] = 6
    df.loc[(df['Rooms'] >= 6) & (df['Square'] <= 50), 'Rooms'] = 1
    df.loc[(df['Rooms'] >= 6) & ((df['Square'] > 50) & (df['Square'] <= 100)), 'Rooms'] = 2
    df.loc[(df['Rooms'] >= 6) & ((df['Square'] > 100) & (df['Square'] <= 150)), 'Rooms'] = 3
    df.loc[(df['Rooms'] >= 6) & ((df['Square'] > 150) & (df['Square'] <= 250)), 'Rooms'] = 4
    df.loc[(df['Rooms'] >= 6) & ((df['Square'] > 250) & (df['Square'] <= 400)), 'Rooms'] = 5
    df.loc[(df['Rooms'] >= 6) & (df['Square'] > 400), 'Rooms'] = 6
    df = add_room_size(df, room_size)
    return df

In [46]:
train['Rooms'].describe()

count    8000.000000
mean        1.886375
std         0.809813
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         5.000000
Name: Rooms, dtype: float64

In [47]:
#Данные по количеству комнат приведены к общему виду.

##### LifeSquare

In [48]:
train['LifeSquare'].describe()

count    6299.000000
mean       37.325501
std        95.733053
min         0.370619
25%        22.797476
50%        32.806379
75%        45.048935
max      7480.592129
Name: LifeSquare, dtype: float64

In [49]:
#plt.scatter(train['LifeSquare'], train['Price']);

In [50]:
median_lifesquare = train.groupby(['DistrictId', 'Rooms'])['LifeSquare'].median().reset_index().rename(columns={'LifeSquare': 'Median_lifesquare'})
median_lifesquare

     DistrictId  Rooms  Median_lifesquare
0             0    1.0          21.335474
1             0    2.0          31.625847
2             0    3.0          47.130692
3             1    1.0          39.990203
4             1    2.0          53.997766
5             1    3.0          79.707512
6             1    4.0          67.345083
7             2    1.0          21.273758
8             2    2.0          31.051408
9             2    3.0          45.695096
10            2    4.0          51.399172
11            3    1.0          21.271679
12            3    2.0          32.572014
13            3    3.0          47.203612
14            4    1.0          17.685013
15            4    2.0          29.986188
16            4    3.0          53.269477
17            4    4.0          81.583849
18            5    1.0          20.307073
19            5    2.0          30.242432
20            5    3.0          39.646143
21            6    1.0          38.352374
22            6    2.0          37.873543
23            6    3.0          67.718790
24            7    1.0          20.189179
25            7    2.0          30.930040
26            7    3.0          46.468301
27            7    4.0          44.139389
28            8    1.0          21.141704
29            8    2.0          31.700339
..          ...    ...                ...
609         188    4.0          70.112069
610         189    1.0          22.625783
611         189    2.0          32.439108
612         189    3.0          43.383320
613         190    2.0          26.903125
614         190    3.0          41.874056
615         191    1.0          21.977354
616         191    3.0          48.461071
617         191    4.0          71.818319
618         192    1.0          24.736845
619         192    2.0          32.221148
620         193    1.0          20.656814
621         193    2.0          33.918107
622         194    2.0          31.152720
623         194    3.0          54.848116
624         194    4.0          56.256401
625         195    3.0          44.872616
626         195    5.0          62.377052
627         196    2.0          28.525317
628         199    3.0          36.527485
629         200    1.0          21.672234
630         200    2.0          28.626088
631         200    3.0          62.339342
632         201    1.0          20.436513
633         201    2.0          27.472272
634         202    2.0          30.661180
635         202    3.0          58.713118
636         205    1.0          18.663548
637         208    2.0          33.935922
638         209    1.0          18.101125

[639 rows x 3 columns]

In [51]:
def add_median_lifesquare(df, median_lifesquare):
    df = pd.merge(df, median_lifesquare, on=['DistrictId', 'Rooms'], how='left')
    
    df['Median_lifesquare'] = df['Median_lifesquare'].fillna(df['Square'] * 0.7)
    df['LifeSquare'] = df['LifeSquare'].fillna(df['Median_lifesquare'])
    return df

In [52]:
train = add_median_lifesquare(train, median_lifesquare)

In [53]:
train['LifeSquare'].describe()

count    8000.000000
mean       38.451245
std        85.289983
min         0.370619
25%        23.475787
50%        34.165949
75%        46.353739
max      7480.592129
Name: LifeSquare, dtype: float64

In [54]:
train.loc[train['LifeSquare'] > train['Square'], :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
22,11592,45,2.0,60.522555,62.816125,1.0,22,25.0,2017,0.195781,B,B,23,5212,6,3,2,B,349107.666290,0,38.132453
48,7501,23,2.0,51.401212,51.569732,1.0,5,12.0,1977,0.034656,B,B,0,168,0,0,0,B,90834.351008,0,51.569732
52,1610,34,2.0,52.797699,56.849348,9.0,13,17.0,2017,0.069753,B,B,53,13670,4,1,11,B,194570.587236,0,56.849348
55,14659,74,2.0,66.944203,67.660710,1.0,8,7.0,1977,0.075779,B,B,6,1437,3,0,2,B,212801.122972,0,66.440664
78,10287,6,1.0,38.344873,38.352374,1.0,10,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,122254.105486,0,38.352374
79,1821,23,2.0,49.929489,51.569732,1.0,9,12.0,1977,0.034656,B,B,0,168,0,0,0,B,88464.425395,0,51.569732
84,1971,1,1.0,41.995577,43.681046,1.0,12,20.0,1977,0.007122,B,B,1,264,0,0,1,B,150371.070429,0,39.990203
85,8386,27,2.0,62.067272,63.456181,10.0,3,17.0,2017,0.017647,B,B,2,469,0,0,0,B,178467.117151,0,36.626949
115,10191,6,2.0,63.659749,63.884799,7.0,18,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188319.662097,0,37.873543
120,8853,30,3.0,80.467878,82.384890,10.0,8,17.0,2014,0.000078,B,B,22,6398,141,3,23,B,180315.190877,0,48.692296
298,10188,23,2.0,51.543365,51.569732,0.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,86196.581698,0,51.569732
304,11164,75,2.0,48.525505,49.848984,5.0,6,5.0,1967,0.307467,B,A,30,5048,9,2,5,B,169876.764789,0,31.724268
318,15610,23,1.0,40.830363,41.642436,1.0,4,9.0,2016,0.034656,B,B,0,168,0,0,0,B,91775.321076,0,30.381045
353,4981,63,2.0,58.476185,58.873237,12.0,16,17.0,2017,0.238617,B,B,26,3889,6,3,6,B,328454.446132,0,33.745509
368,10776,63,1.0,40.711075,42.246859,8.0,10,17.0,1992,0.238617,B,B,26,3889,6,3,6,B,261337.768688,0,23.677259
407,9268,23,4.0,106.767678,112.642841,1.0,6,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,223132.085284,1,112.642841
422,12731,27,3.0,82.877358,83.783846,15.0,11,17.0,2016,0.072158,B,B,2,629,1,0,0,A,201620.866405,0,51.041416
442,13620,1,3.0,79.266760,79.707512,10.0,16,17.0,1977,0.007122,B,B,1,264,0,0,1,B,233890.854819,0,79.707512
444,10,6,3.0,75.888156,78.324716,1.0,11,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,218500.747041,0,67.718790
457,5504,6,1.0,43.741890,43.989478,1.0,9,25.0,2015,0.243205,B,B,5,1564,0,0,0,B,155443.611291,0,38.352374
461,1796,45,1.0,41.323212,42.388252,1.0,24,23.0,2017,0.195781,B,B,23,5212,6,3,2,B,245736.934369,0,21.693643
467,5300,30,3.0,169.509941,170.713651,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
479,14322,1,2.0,62.411905,63.593900,1.0,24,24.0,1977,0.007122,B,B,1,264,0,0,1,B,209817.034644,0,53.997766
500,13295,1,1.0,39.248800,39.990203,0.0,9,17.0,1977,0.007122,B,B,1,264,0,0,1,B,114363.123431,0,39.990203
527,10005,58,1.0,44.995130,47.483236,0.0,3,2.0,2019,0.437885,B,B,23,5735,3,0,5,B,106866.248746,0,22.588815
539,4935,23,1.0,28.859885,30.381045,1.0,12,11.0,1977,0.034656,B,B,0,168,0,0,0,B,68375.615508,0,30.381045
544,5402,27,4.0,98.649404,100.855911,1.0,3,1.0,2019,0.072158,B,B,2,629,1,0,0,A,294689.614794,1,100.855911
552,127,34,3.0,79.130550,83.470011,12.0,25,23.0,2015,0.069753,B,B,53,13670,4,1,11,B,405231.600823,0,77.036246
567,3960,30,1.0,39.137821,40.240232,1.0,16,16.0,2014,0.000078,B,B,22,6398,141,3,23,B,89959.591406,0,40.240232
578,10021,27,1.0,41.755282,41.857484,1.0,13,20.0,2014,0.211401,B,B,9,1892,0,0,1,B,94667.059626,0,23.475787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7571,10185,27,2.0,60.013077,63.617899,1.0,8,19.0,1977,0.211401,B,B,9,1892,0,0,1,B,137392.569761,0,36.626949
7580,15448,1,2.0,65.723452,66.141419,1.0,5,17.0,1977,0.007122,B,B,1,264,0,0,1,B,201704.639671,0,53.997766
7607,13090,1,2.0,68.425918,68.648954,1.0,7,9.0,1977,0.007122,B,B,1,264,0,0,1,B,239152.645700,0,53.997766
7621,15466,88,1.0,42.357487,44.779714,41.0,10,19.0,2016,0.127376,B,B,43,8429,3,3,9,B,194525.103119,0,21.796485
7639,14211,48,1.0,39.357596,40.015989,1.0,21,25.0,2017,0.041125,B,B,46,9515,5,1,10,B,220648.501332,0,22.077389
7648,216,62,3.0,87.003434,91.378545,1.0,3,1.0,2017,0.072158,B,B,2,629,1,0,0,A,225785.867439,0,86.386228
7668,9081,27,1.0,34.396472,35.005440,1.0,14,17.0,2016,0.011654,B,B,4,915,0,0,0,B,110728.588938,0,23.475787
7674,16234,27,2.0,57.943437,60.671325,10.0,16,17.0,2015,0.211401,B,B,9,1892,0,0,1,B,126779.219036,0,36.626949
7675,10390,1,1.0,39.264718,39.990203,1.0,7,17.0,1977,0.007122,B,B,1,264,0,0,1,B,127742.135416,0,39.990203
7690,2434,30,2.0,61.424774,61.519472,13.0,3,19.0,2015,0.000078,B,B,22,6398,141,3,23,B,133166.163513,0,59.226500
7701,7616,48,4.0,123.846928,125.650178,1.0,7,1.0,2015,0.041125,B,B,46,9515,5,1,10,B,595128.195352,1,125.650178
7705,16270,113,1.0,78.410874,78.814606,11.0,7,1.0,2018,0.050756,B,B,24,5469,1,0,1,B,292150.626080,0,22.426004
7712,4811,23,4.0,110.075277,113.830425,0.0,1,3.0,2016,0.034656,B,B,0,168,0,0,0,B,238325.639251,1,112.642841
7713,12437,30,2.0,55.242067,59.226500,1.0,4,4.0,2015,0.000078,B,B,22,6398,141,3,23,B,92135.018672,0,59.226500
7735,5367,1,3.0,81.227389,81.655818,0.0,14,17.0,1977,0.007122,B,B,1,264,0,0,1,B,218595.265514,0,79.707512
7738,15869,30,1.0,31.415062,40.240232,0.0,7,12.0,1977,0.000078,B,B,22,6398,141,3,23,B,68663.011388,0,40.240232
7740,2479,6,1.0,37.794877,38.352374,0.0,14,0.0,1977,0.243205,B,B,5,1564,0,0,0,B,148124.071590,0,38.352374
7763,14991,62,3.0,86.164240,86.386228,0.0,9,0.0,1977,0.072158,B,B,2,629,1,0,0,A,194709.995384,0,86.386228
7784,13537,6,1.0,38.874335,41.379287,1.0,5,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,128043.355789,0,38.352374
7835,13517,30,2.0,55.597409,59.226500,1.0,15,1.0,2013,0.000078,B,B,22,6398,141,3,23,B,153836.505669,0,59.226500
7850,396,54,3.0,110.119100,110.333763,1.0,8,1.0,2015,0.006076,B,B,30,5285,0,6,6,B,491296.245173,0,42.257742
7871,2277,52,1.0,38.555389,41.945460,0.0,14,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,113277.591887,0,23.548368
7872,15258,23,2.0,51.330209,51.569732,1.0,2,17.0,1977,0.034656,B,B,0,168,0,0,0,B,105059.285225,0,51.569732
7876,8715,25,1.0,32.797538,34.671697,1.0,15,13.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895
7927,3461,12,2.0,56.861937,58.940519,9.0,6,14.0,1995,0.090799,B,B,74,19083,2,5,15,B,240450.533232,0,33.909195
7931,769,23,2.0,54.023920,54.834673,10.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,93991.023578,0,51.569732
7970,11025,27,2.0,96.043563,100.982133,10.0,5,6.0,2014,0.075424,B,B,11,3097,0,0,0,B,126277.109148,0,36.626949
7982,3902,23,1.0,27.442238,30.381045,1.0,4,4.0,1977,0.034656,B,B,0,168,0,0,0,B,65547.071846,0,30.381045
7988,5234,30,1.0,29.947691,40.240232,1.0,11,22.0,2018,0.000078,B,B,22,6398,141,3,23,B,99110.577389,0,40.240232
7995,10013,30,2.0,62.219340,62.405338,1.0,4,2.0,2015,0.000078,B,B,22,6398,141,3,23,B,150136.610509,0,59.226500

In [55]:
#

In [56]:
ind_ls_s_20 = train.loc[(train['LifeSquare'] / train['Square']) >= 20, :].index
train.loc[ind_ls_s_20, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1942,16550,27,3.0,81.694417,7480.592129,1.0,9,17.0,2016,0.017647,B,B,2,469,0,0,0,B,217357.492366,0,51.041416

In [57]:
train.loc[(train['LifeSquare'] / train['Square']) >= 20, 'LifeSquare'] = (train['LifeSquare'] / 100)
train.loc[ind_ls_s_20, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1942,16550,27,3.0,81.694417,74.805921,1.0,9,17.0,2016,0.017647,B,B,2,469,0,0,0,B,217357.492366,0,51.041416

In [58]:
#

In [59]:
ind_ls_s_4 = train.loc[((train['LifeSquare'] / train['Square']) >= 4) & (train['LifeSquare'] > 130) & (train['Rooms'] <= 3), :].index
train.loc[ind_ls_s_4, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
2547,15886,85,3.0,78.059331,461.463614,10.0,12,16.0,1998,0.037178,B,B,52,11217,1,1,7,B,394253.299978,0,47.924244

In [60]:
train.loc[((train['LifeSquare'] / train['Square']) >= 4) & (train['LifeSquare'] > 130) & (train['Rooms'] <= 3), 'LifeSquare'] = (train['LifeSquare'] / 10)
train.loc[ind_ls_s_4, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
2547,15886,85,3.0,78.059331,46.146361,10.0,12,16.0,1998,0.037178,B,B,52,11217,1,1,7,B,394253.299978,0,47.924244

In [61]:
#

In [62]:
ind_ls_s_8 = train.loc[(train['LifeSquare'] / train['Square']) >= 8, :].index
train.loc[ind_ls_s_8, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1873,10527,27,1.0,4.380726,40.805837,1.0,10,17.0,2013,0.211401,B,B,9,1892,0,0,1,B,97560.720383,0,23.475787
2675,13265,1,3.0,4.823679,79.767964,0.0,6,17.0,1977,0.007122,B,B,1,264,0,0,1,B,237716.681261,0,79.707512

In [63]:
train.loc[((train['LifeSquare'] / train['Square']) >= 8) & (train['Square'] < 12) & (train['Rooms'] <= 3), 'Square'] = train['Square'] * 10
train.loc[ind_ls_s_8, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1873,10527,27,1.0,43.807258,40.805837,1.0,10,17.0,2013,0.211401,B,B,9,1892,0,0,1,B,97560.720383,0,23.475787
2675,13265,1,3.0,48.236794,79.767964,0.0,6,17.0,1977,0.007122,B,B,1,264,0,0,1,B,237716.681261,0,79.707512

In [64]:
#

In [65]:
ind_ls_s_2 = train.loc[(train['LifeSquare'] / train['Square']) >= 2, :].index
train.loc[ind_ls_s_2, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1352,12927,62,2.0,17.414181,36.861647,1.0,4,20.0,1977,0.072158,B,B,2,629,1,0,0,A,180750.471749,0,36.861647

In [66]:
train.loc[(train['LifeSquare'] / train['Square']) >= 2, 'LifeSquare'] = train['Square'] * 0.7
train.loc[ind_ls_s_2, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1352,12927,62,2.0,17.414181,12.189927,1.0,4,20.0,1977,0.072158,B,B,2,629,1,0,0,A,180750.471749,0,36.861647

In [67]:
#

In [68]:
ind_ls_1 = train.loc[train['LifeSquare'] < 1, :].index
train.loc[ind_ls_1, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1359,4378,27,3.0,106.958871,0.641822,0.0,17,0.0,2018,0.072158,B,B,2,629,1,0,0,A,337299.867936,0,51.041416
6185,5112,6,2.0,63.591740,0.795539,10.0,17,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,174741.998061,0,37.873543
6795,13491,0,1.0,38.178277,0.370619,0.0,19,17.0,2016,0.006076,B,B,30,5285,0,6,6,B,105134.286994,0,21.335474
6843,3224,27,1.0,2.377248,0.873147,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798,0,23.475787

In [69]:
train.loc[train['LifeSquare'] < 1, 'LifeSquare'] = train['LifeSquare'] * 100
train.loc[ind_ls_1, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1359,4378,27,3.0,106.958871,64.182211,0.0,17,0.0,2018,0.072158,B,B,2,629,1,0,0,A,337299.867936,0,51.041416
6185,5112,6,2.0,63.591740,79.553947,10.0,17,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,174741.998061,0,37.873543
6795,13491,0,1.0,38.178277,37.061942,0.0,19,17.0,2016,0.006076,B,B,30,5285,0,6,6,B,105134.286994,0,21.335474
6843,3224,27,1.0,2.377248,87.314672,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798,0,23.475787

In [70]:
#

In [71]:
ind_ls_10 = train.loc[train['LifeSquare'] < 10, :].index
train.loc[ind_ls_10, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
5,6519,94,2.0,50.392833,3.249569,1.0,4,12.0,1973,0.521867,B,B,25,6149,0,0,0,B,157822.338178,0,30.929506
20,15165,74,2.0,83.259565,5.387263,1.0,12,1.0,2017,0.309479,B,B,35,7715,4,0,6,B,260852.230977,0,66.440664
70,2913,34,4.0,94.888593,2.637095,1.0,4,1.0,2018,0.069753,B,B,53,13670,4,1,11,B,346949.506507,1,48.594111
139,15760,34,2.0,65.235395,4.362005,1.0,8,1.0,2014,0.069753,B,B,53,13670,4,1,11,B,336951.628930,0,56.849348
203,13603,63,1.0,127.651237,2.609712,1.0,8,17.0,2016,0.238617,B,B,26,3889,6,3,6,B,594565.299770,0,23.677259
213,8553,88,3.0,83.262530,4.769174,1.0,13,1.0,1977,0.127376,B,B,43,8429,3,3,9,B,410883.892020,0,45.051614
266,10998,6,2.0,52.703116,4.682974,1.0,17,17.0,2018,0.243205,B,B,5,1564,0,0,0,B,153296.980210,0,37.873543
274,3104,30,2.0,32.533803,4.914122,1.0,6,17.0,2015,0.000078,B,B,22,6398,141,3,23,B,115837.070662,0,59.226500
279,5236,30,1.0,48.577906,2.868683,1.0,6,25.0,1977,0.000078,B,B,22,6398,141,3,23,B,150822.681564,0,40.240232
336,6318,6,2.0,75.994434,3.512299,1.0,22,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,190746.651322,0,37.873543
355,16360,48,1.0,40.915247,4.309547,1.0,20,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,209978.966130,0,22.077389
360,14380,58,1.0,40.525820,4.174627,1.0,16,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,116642.983817,0,22.588815
385,13440,6,1.0,78.432890,4.044174,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,222826.758816,0,38.352374
439,10899,6,1.0,39.709108,1.836365,1.0,10,25.0,2017,0.243205,B,B,5,1564,0,0,0,B,134922.641633,0,38.352374
490,11956,62,3.0,86.221496,3.032334,1.0,3,15.0,2017,0.072158,B,B,2,629,1,0,0,A,167544.244106,0,86.386228
497,7627,58,3.0,82.535096,1.626501,1.0,16,17.0,2016,0.437885,B,B,23,5735,3,0,5,B,218975.318679,0,59.387001
538,7838,48,3.0,86.059789,3.434851,1.0,27,1.0,2015,0.041125,B,B,46,9515,5,1,10,B,467773.389759,0,48.669093
608,13523,23,1.0,52.787090,5.600609,1.0,7,1.0,2015,0.014073,B,B,2,475,0,0,0,B,104160.492175,0,30.381045
625,9955,6,2.0,64.083268,1.894269,1.0,2,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,187599.924231,0,37.873543
635,2317,27,1.0,38.305753,5.114439,1.0,7,12.0,1977,0.011654,B,B,4,915,0,0,0,B,97050.819286,0,23.475787
680,7389,23,1.0,52.028804,4.295819,0.0,8,9.0,1977,0.014073,B,B,2,475,0,0,0,B,98638.755928,0,30.381045
683,2108,48,2.0,61.136113,4.289714,1.0,23,1.0,2016,0.041125,B,B,46,9515,5,1,10,B,326425.621924,0,32.609650
686,15261,22,3.0,83.162217,1.318250,1.0,8,1.0,2018,0.118537,B,B,30,6207,1,1,0,B,391390.261824,0,43.927997
854,1936,74,1.0,53.835574,1.185864,0.0,7,7.0,2018,0.075779,B,B,6,1437,3,0,2,B,185976.351147,0,27.504436
862,16150,34,3.0,83.590446,4.030483,1.0,16,1.0,2015,0.069753,B,B,53,13670,4,1,11,B,315641.205620,0,77.036246
896,11654,34,2.0,56.978743,3.204071,0.0,12,0.0,1977,0.069753,B,B,53,13670,4,1,11,B,250175.781800,0,56.849348
1014,8849,45,1.0,63.419553,2.286357,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,325600.765809,0,21.693643
1020,11989,62,3.0,104.446306,1.451067,1.0,12,15.0,2015,0.072158,B,B,2,629,1,0,0,A,223692.672480,0,86.386228
1039,15597,169,2.0,68.896696,5.336872,1.0,11,1.0,2016,0.178917,B,B,18,3594,4,1,5,B,338780.798345,0,30.138998
1093,1843,74,1.0,49.635712,3.411048,1.0,4,1.0,1977,0.309479,B,B,35,7715,4,0,6,B,146838.036852,0,27.504436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6215,4345,62,1.0,49.275155,1.377284,1.0,5,1.0,2020,0.072158,B,B,2,629,1,0,0,A,135353.885620,0,22.893747
6254,11526,27,1.0,4.633498,1.969969,1.0,18,1.0,1977,0.011654,B,B,4,915,0,0,0,B,107604.269441,0,23.475787
6296,15883,23,2.0,64.473190,2.452816,1.0,6,17.0,2016,0.075779,B,B,6,1437,3,0,2,B,181679.665945,0,51.569732
6465,16779,27,3.0,51.991064,4.896202,1.0,22,25.0,1977,0.072158,B,B,2,629,1,0,0,A,174687.566186,0,51.041416
6496,1317,6,1.0,51.460538,4.763693,1.0,25,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,142065.034795,0,38.352374
6523,10229,1,1.0,45.642858,2.072088,1.0,16,24.0,1977,0.007122,B,B,1,264,0,0,1,B,157681.026389,0,39.990203
6600,8194,30,1.0,42.065862,5.624248,1.0,13,17.0,1977,0.000078,B,B,22,6398,141,3,23,B,126976.982021,0,40.240232
6620,464,25,2.0,66.012592,3.529646,1.0,15,25.0,1977,0.069753,B,B,53,13670,4,1,11,B,252748.663126,0,34.206017
6635,15075,54,2.0,81.220434,3.289115,1.0,12,1.0,2016,0.006076,B,B,30,5285,0,6,6,B,437452.971467,0,28.312865
6656,5882,6,3.0,78.105126,2.361873,1.0,2,1.0,2016,0.243205,B,B,5,1564,0,0,0,B,221807.112568,0,67.718790
6771,14638,1,2.0,66.515904,2.978572,1.0,5,17.0,2018,0.007122,B,B,1,264,0,0,1,B,231033.071195,0,53.997766
6820,5088,6,1.0,49.684155,5.567502,1.0,12,25.0,2016,0.243205,B,B,5,1564,0,0,0,B,138230.149386,0,38.352374
6856,6241,23,1.0,37.710823,1.312908,1.0,3,4.0,2016,0.034656,B,B,0,168,0,0,0,B,96563.367810,0,30.381045
6899,6196,1,2.0,55.828425,5.066533,1.0,9,1.0,2019,0.007122,B,B,1,264,0,0,1,B,183136.340415,0,53.997766
6929,8199,9,2.0,67.981161,5.164391,1.0,9,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,205998.194897,0,31.560580
6944,5306,96,1.0,49.462997,1.417155,1.0,8,15.0,2016,0.041116,B,B,53,14892,4,1,4,B,119791.098164,0,20.052043
6988,5830,23,2.0,56.809859,4.037187,1.0,3,4.0,2015,0.034656,B,B,0,168,0,0,0,B,124695.921792,0,51.569732
6989,12342,27,1.0,40.490421,4.114601,0.0,20,22.0,2019,0.211401,B,B,9,1892,0,0,1,B,120221.581843,0,23.475787
7017,6237,6,2.0,68.495636,3.064164,1.0,6,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,178486.385759,0,37.873543
7036,6782,45,1.0,2.954309,5.257278,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,438005.182323,0,21.693643
7101,3575,27,2.0,65.620926,1.819046,0.0,9,0.0,2015,0.072158,B,B,2,629,1,0,0,A,211345.630469,0,36.626949
7112,5497,58,1.0,37.686426,4.977769,1.0,2,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,72950.870871,0,22.588815
7422,6366,6,1.0,47.804946,2.553024,1.0,6,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,133552.372112,0,38.352374
7425,1388,54,2.0,74.747303,1.411101,1.0,7,22.0,1977,0.006076,B,B,30,5285,0,6,6,B,431137.951634,0,28.312865
7433,6631,85,1.0,48.990533,1.104689,1.0,5,17.0,1977,0.072158,B,B,2,629,1,0,0,A,124761.832592,0,20.855406
7461,5575,27,1.0,41.941912,4.437475,0.0,10,0.0,2016,0.211401,B,B,9,1892,0,0,1,B,113350.022423,0,23.475787
7506,10426,6,1.0,43.670665,4.552029,1.0,9,17.0,2017,0.243205,B,B,5,1564,0,0,0,B,132162.808917,0,38.352374
7593,4773,75,2.0,68.088569,3.533997,1.0,8,1.0,2015,0.122090,B,B,29,6566,7,4,0,B,311242.425922,0,31.724268
7853,583,27,3.0,84.250710,4.187885,1.0,15,1.0,2016,0.072158,B,B,2,629,1,0,0,A,236647.781363,0,51.041416
7890,1182,27,1.0,38.936986,3.064320,0.0,18,19.0,2017,0.211401,B,B,9,1892,0,0,1,B,93560.789553,0,23.475787

In [72]:
train.loc[train['LifeSquare'] < 10, 'LifeSquare'] = train['LifeSquare'] * 10
train.loc[ind_ls_10, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
5,6519,94,2.0,50.392833,32.495693,1.0,4,12.0,1973,0.521867,B,B,25,6149,0,0,0,B,157822.338178,0,30.929506
20,15165,74,2.0,83.259565,53.872631,1.0,12,1.0,2017,0.309479,B,B,35,7715,4,0,6,B,260852.230977,0,66.440664
70,2913,34,4.0,94.888593,26.370948,1.0,4,1.0,2018,0.069753,B,B,53,13670,4,1,11,B,346949.506507,1,48.594111
139,15760,34,2.0,65.235395,43.620052,1.0,8,1.0,2014,0.069753,B,B,53,13670,4,1,11,B,336951.628930,0,56.849348
203,13603,63,1.0,127.651237,26.097116,1.0,8,17.0,2016,0.238617,B,B,26,3889,6,3,6,B,594565.299770,0,23.677259
213,8553,88,3.0,83.262530,47.691744,1.0,13,1.0,1977,0.127376,B,B,43,8429,3,3,9,B,410883.892020,0,45.051614
266,10998,6,2.0,52.703116,46.829742,1.0,17,17.0,2018,0.243205,B,B,5,1564,0,0,0,B,153296.980210,0,37.873543
274,3104,30,2.0,32.533803,49.141216,1.0,6,17.0,2015,0.000078,B,B,22,6398,141,3,23,B,115837.070662,0,59.226500
279,5236,30,1.0,48.577906,28.686830,1.0,6,25.0,1977,0.000078,B,B,22,6398,141,3,23,B,150822.681564,0,40.240232
336,6318,6,2.0,75.994434,35.122988,1.0,22,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,190746.651322,0,37.873543
355,16360,48,1.0,40.915247,43.095467,1.0,20,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,209978.966130,0,22.077389
360,14380,58,1.0,40.525820,41.746265,1.0,16,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,116642.983817,0,22.588815
385,13440,6,1.0,78.432890,40.441742,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,222826.758816,0,38.352374
439,10899,6,1.0,39.709108,18.363647,1.0,10,25.0,2017,0.243205,B,B,5,1564,0,0,0,B,134922.641633,0,38.352374
490,11956,62,3.0,86.221496,30.323341,1.0,3,15.0,2017,0.072158,B,B,2,629,1,0,0,A,167544.244106,0,86.386228
497,7627,58,3.0,82.535096,16.265012,1.0,16,17.0,2016,0.437885,B,B,23,5735,3,0,5,B,218975.318679,0,59.387001
538,7838,48,3.0,86.059789,34.348509,1.0,27,1.0,2015,0.041125,B,B,46,9515,5,1,10,B,467773.389759,0,48.669093
608,13523,23,1.0,52.787090,56.006086,1.0,7,1.0,2015,0.014073,B,B,2,475,0,0,0,B,104160.492175,0,30.381045
625,9955,6,2.0,64.083268,18.942686,1.0,2,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,187599.924231,0,37.873543
635,2317,27,1.0,38.305753,51.144391,1.0,7,12.0,1977,0.011654,B,B,4,915,0,0,0,B,97050.819286,0,23.475787
680,7389,23,1.0,52.028804,42.958189,0.0,8,9.0,1977,0.014073,B,B,2,475,0,0,0,B,98638.755928,0,30.381045
683,2108,48,2.0,61.136113,42.897143,1.0,23,1.0,2016,0.041125,B,B,46,9515,5,1,10,B,326425.621924,0,32.609650
686,15261,22,3.0,83.162217,13.182499,1.0,8,1.0,2018,0.118537,B,B,30,6207,1,1,0,B,391390.261824,0,43.927997
854,1936,74,1.0,53.835574,11.858636,0.0,7,7.0,2018,0.075779,B,B,6,1437,3,0,2,B,185976.351147,0,27.504436
862,16150,34,3.0,83.590446,40.304835,1.0,16,1.0,2015,0.069753,B,B,53,13670,4,1,11,B,315641.205620,0,77.036246
896,11654,34,2.0,56.978743,32.040705,0.0,12,0.0,1977,0.069753,B,B,53,13670,4,1,11,B,250175.781800,0,56.849348
1014,8849,45,1.0,63.419553,22.863568,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,325600.765809,0,21.693643
1020,11989,62,3.0,104.446306,14.510667,1.0,12,15.0,2015,0.072158,B,B,2,629,1,0,0,A,223692.672480,0,86.386228
1039,15597,169,2.0,68.896696,53.368718,1.0,11,1.0,2016,0.178917,B,B,18,3594,4,1,5,B,338780.798345,0,30.138998
1093,1843,74,1.0,49.635712,34.110477,1.0,4,1.0,1977,0.309479,B,B,35,7715,4,0,6,B,146838.036852,0,27.504436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6215,4345,62,1.0,49.275155,13.772843,1.0,5,1.0,2020,0.072158,B,B,2,629,1,0,0,A,135353.885620,0,22.893747
6254,11526,27,1.0,4.633498,19.699690,1.0,18,1.0,1977,0.011654,B,B,4,915,0,0,0,B,107604.269441,0,23.475787
6296,15883,23,2.0,64.473190,24.528162,1.0,6,17.0,2016,0.075779,B,B,6,1437,3,0,2,B,181679.665945,0,51.569732
6465,16779,27,3.0,51.991064,48.962019,1.0,22,25.0,1977,0.072158,B,B,2,629,1,0,0,A,174687.566186,0,51.041416
6496,1317,6,1.0,51.460538,47.636929,1.0,25,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,142065.034795,0,38.352374
6523,10229,1,1.0,45.642858,20.720880,1.0,16,24.0,1977,0.007122,B,B,1,264,0,0,1,B,157681.026389,0,39.990203
6600,8194,30,1.0,42.065862,56.242482,1.0,13,17.0,1977,0.000078,B,B,22,6398,141,3,23,B,126976.982021,0,40.240232
6620,464,25,2.0,66.012592,35.296462,1.0,15,25.0,1977,0.069753,B,B,53,13670,4,1,11,B,252748.663126,0,34.206017
6635,15075,54,2.0,81.220434,32.891147,1.0,12,1.0,2016,0.006076,B,B,30,5285,0,6,6,B,437452.971467,0,28.312865
6656,5882,6,3.0,78.105126,23.618730,1.0,2,1.0,2016,0.243205,B,B,5,1564,0,0,0,B,221807.112568,0,67.718790
6771,14638,1,2.0,66.515904,29.785715,1.0,5,17.0,2018,0.007122,B,B,1,264,0,0,1,B,231033.071195,0,53.997766
6820,5088,6,1.0,49.684155,55.675021,1.0,12,25.0,2016,0.243205,B,B,5,1564,0,0,0,B,138230.149386,0,38.352374
6856,6241,23,1.0,37.710823,13.129077,1.0,3,4.0,2016,0.034656,B,B,0,168,0,0,0,B,96563.367810,0,30.381045
6899,6196,1,2.0,55.828425,50.665326,1.0,9,1.0,2019,0.007122,B,B,1,264,0,0,1,B,183136.340415,0,53.997766
6929,8199,9,2.0,67.981161,51.643908,1.0,9,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,205998.194897,0,31.560580
6944,5306,96,1.0,49.462997,14.171549,1.0,8,15.0,2016,0.041116,B,B,53,14892,4,1,4,B,119791.098164,0,20.052043
6988,5830,23,2.0,56.809859,40.371866,1.0,3,4.0,2015,0.034656,B,B,0,168,0,0,0,B,124695.921792,0,51.569732
6989,12342,27,1.0,40.490421,41.146014,0.0,20,22.0,2019,0.211401,B,B,9,1892,0,0,1,B,120221.581843,0,23.475787
7017,6237,6,2.0,68.495636,30.641637,1.0,6,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,178486.385759,0,37.873543
7036,6782,45,1.0,2.954309,52.572785,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,438005.182323,0,21.693643
7101,3575,27,2.0,65.620926,18.190459,0.0,9,0.0,2015,0.072158,B,B,2,629,1,0,0,A,211345.630469,0,36.626949
7112,5497,58,1.0,37.686426,49.777690,1.0,2,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,72950.870871,0,22.588815
7422,6366,6,1.0,47.804946,25.530235,1.0,6,25.0,1977,0.243205,B,B,5,1564,0,0,0,B,133552.372112,0,38.352374
7425,1388,54,2.0,74.747303,14.111011,1.0,7,22.0,1977,0.006076,B,B,30,5285,0,6,6,B,431137.951634,0,28.312865
7433,6631,85,1.0,48.990533,11.046892,1.0,5,17.0,1977,0.072158,B,B,2,629,1,0,0,A,124761.832592,0,20.855406
7461,5575,27,1.0,41.941912,44.374751,0.0,10,0.0,2016,0.211401,B,B,9,1892,0,0,1,B,113350.022423,0,23.475787
7506,10426,6,1.0,43.670665,45.520289,1.0,9,17.0,2017,0.243205,B,B,5,1564,0,0,0,B,132162.808917,0,38.352374
7593,4773,75,2.0,68.088569,35.339974,1.0,8,1.0,2015,0.122090,B,B,29,6566,7,4,0,B,311242.425922,0,31.724268
7853,583,27,3.0,84.250710,41.878848,1.0,15,1.0,2016,0.072158,B,B,2,629,1,0,0,A,236647.781363,0,51.041416
7890,1182,27,1.0,38.936986,30.643197,0.0,18,19.0,2017,0.211401,B,B,9,1892,0,0,1,B,93560.789553,0,23.475787

In [73]:
#

In [74]:
ind_ls_15 = train.loc[(train['LifeSquare'] < 15) & (train['Square'] / train['LifeSquare'] > 2), :].index
train.loc[ind_ls_15, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
100,8998,20,1.0,30.082090,12.125029,7.0,9,9.0,1976,0.019509,B,B,37,7687,11,5,5,B,186537.391208,0,23.124698
228,11374,46,1.0,36.007450,14.617466,9.0,7,17.0,2008,0.000000,B,B,47,11319,0,3,5,B,218409.263545,0,22.060771
576,16575,27,1.0,32.712359,11.047605,13.0,8,25.0,2016,0.072158,B,B,2,629,1,0,0,A,94433.038958,0,23.475787
686,15261,22,3.0,83.162217,13.182499,1.0,8,1.0,2018,0.118537,B,B,30,6207,1,1,0,B,391390.261824,0,43.927997
854,1936,74,1.0,53.835574,11.858636,0.0,7,7.0,2018,0.075779,B,B,6,1437,3,0,2,B,185976.351147,0,27.504436
943,6234,74,1.0,30.063248,12.208497,10.0,6,9.0,1972,0.309479,B,B,35,7715,4,0,6,B,133124.260377,0,27.504436
1020,11989,62,3.0,104.446306,14.510667,1.0,12,15.0,2015,0.072158,B,B,2,629,1,0,0,A,223692.672480,0,86.386228
1964,1530,145,1.0,39.726251,14.462872,11.0,2,12.0,1998,0.000000,B,B,30,5562,0,0,5,A,177117.097756,0,19.093353
2036,15402,27,2.0,58.521098,10.498673,1.0,4,17.0,2014,0.072158,B,B,2,629,1,0,0,A,142393.084641,0,36.626949
2087,2755,110,1.0,34.723468,14.980639,10.0,13,24.0,2000,0.033494,B,B,66,10573,1,3,8,B,162309.996645,0,23.022337
2353,15691,62,1.0,41.735073,12.423180,14.0,3,15.0,2010,0.072158,B,B,2,629,1,0,0,A,80331.107871,0,22.893747
3075,15360,27,1.0,31.276397,14.057882,6.0,21,27.0,2015,0.072158,B,B,2,629,1,0,0,A,85762.965780,0,23.475787
3107,11829,34,4.0,98.047744,14.518460,1.0,16,1.0,1977,0.069753,B,B,53,13670,4,1,11,B,366655.111294,1,48.594111
3367,5354,85,1.0,28.535084,12.733642,6.0,4,9.0,1967,0.037178,B,B,52,11217,1,1,7,B,142269.268090,0,20.855406
3420,10733,27,1.0,34.257693,14.423436,10.0,7,25.0,2014,0.072158,B,B,2,629,1,0,0,A,108396.297379,0,23.475787
3450,10330,145,1.0,37.482908,14.351381,11.0,11,12.0,1999,0.000000,B,B,30,5562,0,0,5,A,180781.664352,0,19.093353
3837,12245,23,2.0,67.032994,11.396665,1.0,3,17.0,1977,0.034656,B,B,0,168,0,0,0,B,185006.418232,0,51.569732
3901,11784,55,1.0,35.933565,14.620211,9.0,1,17.0,1990,0.041365,B,B,31,5569,0,1,4,B,141846.496274,0,21.588315
3997,59,27,1.0,27.181473,10.924281,8.0,10,25.0,2014,0.072158,B,B,2,629,1,0,0,A,75170.813107,0,23.475787
4232,8601,6,3.0,80.968060,12.396223,1.0,6,17.0,2017,0.243205,B,B,5,1564,0,0,0,B,217669.112875,0,67.718790
4399,915,6,2.0,66.854936,12.588864,1.0,8,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,180416.401098,0,37.873543
4594,12198,6,1.0,41.939733,10.711927,1.0,12,17.0,2019,0.243205,B,B,5,1564,0,0,0,B,127233.289627,0,38.352374
4657,12049,1,2.0,61.541353,12.422499,1.0,20,22.0,2014,0.007122,B,B,1,264,0,0,1,B,206168.319222,0,53.997766
4793,8626,1,1.0,47.195748,11.687911,1.0,19,24.0,1977,0.007122,B,B,1,264,0,0,1,B,170718.296542,0,39.990203
4874,8044,45,2.0,62.777104,11.411183,1.0,10,17.0,1977,0.195781,B,B,23,5212,6,3,2,B,332118.521912,0,38.132453
5131,12412,27,1.0,29.607771,12.333580,8.0,17,25.0,1967,0.072158,B,B,2,629,1,0,0,A,114320.098260,0,23.475787
5246,8837,48,1.0,40.412437,11.617853,8.0,8,25.0,2011,0.041125,B,B,46,9515,5,1,10,B,259391.801748,0,22.077389
5538,7558,9,3.0,80.288136,12.970302,1.0,14,18.0,1977,0.161532,B,B,25,5648,1,2,4,B,254966.798112,0,45.664912
5587,10930,9,2.0,65.568381,11.500464,1.0,6,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,187858.706484,0,31.560580
5870,4682,7,2.0,43.860149,11.321071,7.0,6,12.0,1969,0.035145,B,B,42,9292,3,0,3,B,235924.134145,0,30.930040
6163,5762,27,2.0,67.983723,14.714908,1.0,8,1.0,2019,0.211401,B,B,9,1892,0,0,1,B,152932.624905,0,36.626949
6169,15751,9,1.0,44.171793,12.518458,1.0,11,18.0,2017,0.161532,B,B,25,5648,1,2,4,B,134910.715588,0,22.079346
6215,4345,62,1.0,49.275155,13.772843,1.0,5,1.0,2020,0.072158,B,B,2,629,1,0,0,A,135353.885620,0,22.893747
6270,6619,46,1.0,33.101922,13.147334,5.0,4,9.0,1970,0.000000,B,B,47,11319,0,3,5,B,172925.540694,0,22.060771
6856,6241,23,1.0,37.710823,13.129077,1.0,3,4.0,2016,0.034656,B,B,0,168,0,0,0,B,96563.367810,0,30.381045
6944,5306,96,1.0,49.462997,14.171549,1.0,8,15.0,2016,0.041116,B,B,53,14892,4,1,4,B,119791.098164,0,20.052043
7391,3959,107,1.0,36.233334,13.425432,8.0,6,12.0,1971,0.174739,B,B,17,3379,9,0,3,B,158841.657082,0,21.214778
7425,1388,54,2.0,74.747303,14.111011,1.0,7,22.0,1977,0.006076,B,B,30,5285,0,6,6,B,431137.951634,0,28.312865
7433,6631,85,1.0,48.990533,11.046892,1.0,5,17.0,1977,0.072158,B,B,2,629,1,0,0,A,124761.832592,0,20.855406
7618,9784,100,1.0,35.895583,14.709211,10.0,7,11.0,1977,0.200147,B,B,23,3975,8,2,0,B,146060.096904,0,20.432361
7795,14002,161,1.0,52.330122,14.691433,12.0,10,9.0,2011,0.014423,B,B,19,3806,4,0,3,B,254291.874883,0,19.406568
7831,5826,23,1.0,55.282148,11.168019,20.0,4,3.0,2013,0.014073,B,B,2,475,0,0,0,B,157140.848998,0,30.381045

In [75]:
train.loc[(train['LifeSquare'] < 15) & (train['Square'] / train['LifeSquare'] > 2), 'LifeSquare'] = train['LifeSquare'] * 2
train.loc[ind_ls_15, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
100,8998,20,1.0,30.082090,24.250057,7.0,9,9.0,1976,0.019509,B,B,37,7687,11,5,5,B,186537.391208,0,23.124698
228,11374,46,1.0,36.007450,29.234932,9.0,7,17.0,2008,0.000000,B,B,47,11319,0,3,5,B,218409.263545,0,22.060771
576,16575,27,1.0,32.712359,22.095210,13.0,8,25.0,2016,0.072158,B,B,2,629,1,0,0,A,94433.038958,0,23.475787
686,15261,22,3.0,83.162217,26.364998,1.0,8,1.0,2018,0.118537,B,B,30,6207,1,1,0,B,391390.261824,0,43.927997
854,1936,74,1.0,53.835574,23.717271,0.0,7,7.0,2018,0.075779,B,B,6,1437,3,0,2,B,185976.351147,0,27.504436
943,6234,74,1.0,30.063248,24.416994,10.0,6,9.0,1972,0.309479,B,B,35,7715,4,0,6,B,133124.260377,0,27.504436
1020,11989,62,3.0,104.446306,29.021333,1.0,12,15.0,2015,0.072158,B,B,2,629,1,0,0,A,223692.672480,0,86.386228
1964,1530,145,1.0,39.726251,28.925743,11.0,2,12.0,1998,0.000000,B,B,30,5562,0,0,5,A,177117.097756,0,19.093353
2036,15402,27,2.0,58.521098,20.997346,1.0,4,17.0,2014,0.072158,B,B,2,629,1,0,0,A,142393.084641,0,36.626949
2087,2755,110,1.0,34.723468,29.961279,10.0,13,24.0,2000,0.033494,B,B,66,10573,1,3,8,B,162309.996645,0,23.022337
2353,15691,62,1.0,41.735073,24.846360,14.0,3,15.0,2010,0.072158,B,B,2,629,1,0,0,A,80331.107871,0,22.893747
3075,15360,27,1.0,31.276397,28.115763,6.0,21,27.0,2015,0.072158,B,B,2,629,1,0,0,A,85762.965780,0,23.475787
3107,11829,34,4.0,98.047744,29.036919,1.0,16,1.0,1977,0.069753,B,B,53,13670,4,1,11,B,366655.111294,1,48.594111
3367,5354,85,1.0,28.535084,25.467284,6.0,4,9.0,1967,0.037178,B,B,52,11217,1,1,7,B,142269.268090,0,20.855406
3420,10733,27,1.0,34.257693,28.846872,10.0,7,25.0,2014,0.072158,B,B,2,629,1,0,0,A,108396.297379,0,23.475787
3450,10330,145,1.0,37.482908,28.702762,11.0,11,12.0,1999,0.000000,B,B,30,5562,0,0,5,A,180781.664352,0,19.093353
3837,12245,23,2.0,67.032994,22.793330,1.0,3,17.0,1977,0.034656,B,B,0,168,0,0,0,B,185006.418232,0,51.569732
3901,11784,55,1.0,35.933565,29.240422,9.0,1,17.0,1990,0.041365,B,B,31,5569,0,1,4,B,141846.496274,0,21.588315
3997,59,27,1.0,27.181473,21.848562,8.0,10,25.0,2014,0.072158,B,B,2,629,1,0,0,A,75170.813107,0,23.475787
4232,8601,6,3.0,80.968060,24.792446,1.0,6,17.0,2017,0.243205,B,B,5,1564,0,0,0,B,217669.112875,0,67.718790
4399,915,6,2.0,66.854936,25.177728,1.0,8,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,180416.401098,0,37.873543
4594,12198,6,1.0,41.939733,21.423854,1.0,12,17.0,2019,0.243205,B,B,5,1564,0,0,0,B,127233.289627,0,38.352374
4657,12049,1,2.0,61.541353,24.844997,1.0,20,22.0,2014,0.007122,B,B,1,264,0,0,1,B,206168.319222,0,53.997766
4793,8626,1,1.0,47.195748,23.375822,1.0,19,24.0,1977,0.007122,B,B,1,264,0,0,1,B,170718.296542,0,39.990203
4874,8044,45,2.0,62.777104,22.822366,1.0,10,17.0,1977,0.195781,B,B,23,5212,6,3,2,B,332118.521912,0,38.132453
5131,12412,27,1.0,29.607771,24.667159,8.0,17,25.0,1967,0.072158,B,B,2,629,1,0,0,A,114320.098260,0,23.475787
5246,8837,48,1.0,40.412437,23.235705,8.0,8,25.0,2011,0.041125,B,B,46,9515,5,1,10,B,259391.801748,0,22.077389
5538,7558,9,3.0,80.288136,25.940605,1.0,14,18.0,1977,0.161532,B,B,25,5648,1,2,4,B,254966.798112,0,45.664912
5587,10930,9,2.0,65.568381,23.000928,1.0,6,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,187858.706484,0,31.560580
5870,4682,7,2.0,43.860149,22.642143,7.0,6,12.0,1969,0.035145,B,B,42,9292,3,0,3,B,235924.134145,0,30.930040
6163,5762,27,2.0,67.983723,29.429816,1.0,8,1.0,2019,0.211401,B,B,9,1892,0,0,1,B,152932.624905,0,36.626949
6169,15751,9,1.0,44.171793,25.036915,1.0,11,18.0,2017,0.161532,B,B,25,5648,1,2,4,B,134910.715588,0,22.079346
6215,4345,62,1.0,49.275155,27.545686,1.0,5,1.0,2020,0.072158,B,B,2,629,1,0,0,A,135353.885620,0,22.893747
6270,6619,46,1.0,33.101922,26.294669,5.0,4,9.0,1970,0.000000,B,B,47,11319,0,3,5,B,172925.540694,0,22.060771
6856,6241,23,1.0,37.710823,26.258153,1.0,3,4.0,2016,0.034656,B,B,0,168,0,0,0,B,96563.367810,0,30.381045
6944,5306,96,1.0,49.462997,28.343098,1.0,8,15.0,2016,0.041116,B,B,53,14892,4,1,4,B,119791.098164,0,20.052043
7391,3959,107,1.0,36.233334,26.850863,8.0,6,12.0,1971,0.174739,B,B,17,3379,9,0,3,B,158841.657082,0,21.214778
7425,1388,54,2.0,74.747303,28.222023,1.0,7,22.0,1977,0.006076,B,B,30,5285,0,6,6,B,431137.951634,0,28.312865
7433,6631,85,1.0,48.990533,22.093785,1.0,5,17.0,1977,0.072158,B,B,2,629,1,0,0,A,124761.832592,0,20.855406
7618,9784,100,1.0,35.895583,29.418422,10.0,7,11.0,1977,0.200147,B,B,23,3975,8,2,0,B,146060.096904,0,20.432361
7795,14002,161,1.0,52.330122,29.382866,12.0,10,9.0,2011,0.014423,B,B,19,3806,4,0,3,B,254291.874883,0,19.406568
7831,5826,23,1.0,55.282148,22.336038,20.0,4,3.0,2013,0.014073,B,B,2,475,0,0,0,B,157140.848998,0,30.381045

In [76]:
###

In [77]:
ind_ls_s = train.loc[train['LifeSquare'] > train['Square'], :].index
train.loc[ind_ls_s, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
22,11592,45,2.0,60.522555,62.816125,1.0,22,25.0,2017,0.195781,B,B,23,5212,6,3,2,B,349107.666290,0,38.132453
48,7501,23,2.0,51.401212,51.569732,1.0,5,12.0,1977,0.034656,B,B,0,168,0,0,0,B,90834.351008,0,51.569732
52,1610,34,2.0,52.797699,56.849348,9.0,13,17.0,2017,0.069753,B,B,53,13670,4,1,11,B,194570.587236,0,56.849348
55,14659,74,2.0,66.944203,67.660710,1.0,8,7.0,1977,0.075779,B,B,6,1437,3,0,2,B,212801.122972,0,66.440664
78,10287,6,1.0,38.344873,38.352374,1.0,10,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,122254.105486,0,38.352374
79,1821,23,2.0,49.929489,51.569732,1.0,9,12.0,1977,0.034656,B,B,0,168,0,0,0,B,88464.425395,0,51.569732
84,1971,1,1.0,41.995577,43.681046,1.0,12,20.0,1977,0.007122,B,B,1,264,0,0,1,B,150371.070429,0,39.990203
85,8386,27,2.0,62.067272,63.456181,10.0,3,17.0,2017,0.017647,B,B,2,469,0,0,0,B,178467.117151,0,36.626949
115,10191,6,2.0,63.659749,63.884799,7.0,18,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188319.662097,0,37.873543
120,8853,30,3.0,80.467878,82.384890,10.0,8,17.0,2014,0.000078,B,B,22,6398,141,3,23,B,180315.190877,0,48.692296
274,3104,30,2.0,32.533803,49.141216,1.0,6,17.0,2015,0.000078,B,B,22,6398,141,3,23,B,115837.070662,0,59.226500
298,10188,23,2.0,51.543365,51.569732,0.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,86196.581698,0,51.569732
304,11164,75,2.0,48.525505,49.848984,5.0,6,5.0,1967,0.307467,B,A,30,5048,9,2,5,B,169876.764789,0,31.724268
318,15610,23,1.0,40.830363,41.642436,1.0,4,9.0,2016,0.034656,B,B,0,168,0,0,0,B,91775.321076,0,30.381045
353,4981,63,2.0,58.476185,58.873237,12.0,16,17.0,2017,0.238617,B,B,26,3889,6,3,6,B,328454.446132,0,33.745509
355,16360,48,1.0,40.915247,43.095467,1.0,20,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,209978.966130,0,22.077389
360,14380,58,1.0,40.525820,41.746265,1.0,16,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,116642.983817,0,22.588815
368,10776,63,1.0,40.711075,42.246859,8.0,10,17.0,1992,0.238617,B,B,26,3889,6,3,6,B,261337.768688,0,23.677259
407,9268,23,4.0,106.767678,112.642841,1.0,6,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,223132.085284,1,112.642841
422,12731,27,3.0,82.877358,83.783846,15.0,11,17.0,2016,0.072158,B,B,2,629,1,0,0,A,201620.866405,0,51.041416
442,13620,1,3.0,79.266760,79.707512,10.0,16,17.0,1977,0.007122,B,B,1,264,0,0,1,B,233890.854819,0,79.707512
444,10,6,3.0,75.888156,78.324716,1.0,11,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,218500.747041,0,67.718790
457,5504,6,1.0,43.741890,43.989478,1.0,9,25.0,2015,0.243205,B,B,5,1564,0,0,0,B,155443.611291,0,38.352374
461,1796,45,1.0,41.323212,42.388252,1.0,24,23.0,2017,0.195781,B,B,23,5212,6,3,2,B,245736.934369,0,21.693643
467,5300,30,3.0,169.509941,170.713651,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
479,14322,1,2.0,62.411905,63.593900,1.0,24,24.0,1977,0.007122,B,B,1,264,0,0,1,B,209817.034644,0,53.997766
500,13295,1,1.0,39.248800,39.990203,0.0,9,17.0,1977,0.007122,B,B,1,264,0,0,1,B,114363.123431,0,39.990203
527,10005,58,1.0,44.995130,47.483236,0.0,3,2.0,2019,0.437885,B,B,23,5735,3,0,5,B,106866.248746,0,22.588815
539,4935,23,1.0,28.859885,30.381045,1.0,12,11.0,1977,0.034656,B,B,0,168,0,0,0,B,68375.615508,0,30.381045
544,5402,27,4.0,98.649404,100.855911,1.0,3,1.0,2019,0.072158,B,B,2,629,1,0,0,A,294689.614794,1,100.855911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7571,10185,27,2.0,60.013077,63.617899,1.0,8,19.0,1977,0.211401,B,B,9,1892,0,0,1,B,137392.569761,0,36.626949
7580,15448,1,2.0,65.723452,66.141419,1.0,5,17.0,1977,0.007122,B,B,1,264,0,0,1,B,201704.639671,0,53.997766
7607,13090,1,2.0,68.425918,68.648954,1.0,7,9.0,1977,0.007122,B,B,1,264,0,0,1,B,239152.645700,0,53.997766
7621,15466,88,1.0,42.357487,44.779714,41.0,10,19.0,2016,0.127376,B,B,43,8429,3,3,9,B,194525.103119,0,21.796485
7639,14211,48,1.0,39.357596,40.015989,1.0,21,25.0,2017,0.041125,B,B,46,9515,5,1,10,B,220648.501332,0,22.077389
7648,216,62,3.0,87.003434,91.378545,1.0,3,1.0,2017,0.072158,B,B,2,629,1,0,0,A,225785.867439,0,86.386228
7668,9081,27,1.0,34.396472,35.005440,1.0,14,17.0,2016,0.011654,B,B,4,915,0,0,0,B,110728.588938,0,23.475787
7674,16234,27,2.0,57.943437,60.671325,10.0,16,17.0,2015,0.211401,B,B,9,1892,0,0,1,B,126779.219036,0,36.626949
7675,10390,1,1.0,39.264718,39.990203,1.0,7,17.0,1977,0.007122,B,B,1,264,0,0,1,B,127742.135416,0,39.990203
7690,2434,30,2.0,61.424774,61.519472,13.0,3,19.0,2015,0.000078,B,B,22,6398,141,3,23,B,133166.163513,0,59.226500
7701,7616,48,4.0,123.846928,125.650178,1.0,7,1.0,2015,0.041125,B,B,46,9515,5,1,10,B,595128.195352,1,125.650178
7705,16270,113,1.0,78.410874,78.814606,11.0,7,1.0,2018,0.050756,B,B,24,5469,1,0,1,B,292150.626080,0,22.426004
7712,4811,23,4.0,110.075277,113.830425,0.0,1,3.0,2016,0.034656,B,B,0,168,0,0,0,B,238325.639251,1,112.642841
7713,12437,30,2.0,55.242067,59.226500,1.0,4,4.0,2015,0.000078,B,B,22,6398,141,3,23,B,92135.018672,0,59.226500
7735,5367,1,3.0,81.227389,81.655818,0.0,14,17.0,1977,0.007122,B,B,1,264,0,0,1,B,218595.265514,0,79.707512
7738,15869,30,1.0,31.415062,40.240232,0.0,7,12.0,1977,0.000078,B,B,22,6398,141,3,23,B,68663.011388,0,40.240232
7740,2479,6,1.0,37.794877,38.352374,0.0,14,0.0,1977,0.243205,B,B,5,1564,0,0,0,B,148124.071590,0,38.352374
7763,14991,62,3.0,86.164240,86.386228,0.0,9,0.0,1977,0.072158,B,B,2,629,1,0,0,A,194709.995384,0,86.386228
7784,13537,6,1.0,38.874335,41.379287,1.0,5,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,128043.355789,0,38.352374
7835,13517,30,2.0,55.597409,59.226500,1.0,15,1.0,2013,0.000078,B,B,22,6398,141,3,23,B,153836.505669,0,59.226500
7850,396,54,3.0,110.119100,110.333763,1.0,8,1.0,2015,0.006076,B,B,30,5285,0,6,6,B,491296.245173,0,42.257742
7871,2277,52,1.0,38.555389,41.945460,0.0,14,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,113277.591887,0,23.548368
7872,15258,23,2.0,51.330209,51.569732,1.0,2,17.0,1977,0.034656,B,B,0,168,0,0,0,B,105059.285225,0,51.569732
7876,8715,25,1.0,32.797538,34.671697,1.0,15,13.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895
7927,3461,12,2.0,56.861937,58.940519,9.0,6,14.0,1995,0.090799,B,B,74,19083,2,5,15,B,240450.533232,0,33.909195
7931,769,23,2.0,54.023920,54.834673,10.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,93991.023578,0,51.569732
7970,11025,27,2.0,96.043563,100.982133,10.0,5,6.0,2014,0.075424,B,B,11,3097,0,0,0,B,126277.109148,0,36.626949
7982,3902,23,1.0,27.442238,30.381045,1.0,4,4.0,1977,0.034656,B,B,0,168,0,0,0,B,65547.071846,0,30.381045
7988,5234,30,1.0,29.947691,40.240232,1.0,11,22.0,2018,0.000078,B,B,22,6398,141,3,23,B,99110.577389,0,40.240232
7995,10013,30,2.0,62.219340,62.405338,1.0,4,2.0,2015,0.000078,B,B,22,6398,141,3,23,B,150136.610509,0,59.226500

In [78]:
train.loc[train['LifeSquare'] > train['Square'], 'LifeSquare'] = train['Square'] * 0.7
train.loc[ind_ls_s, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
22,11592,45,2.0,60.522555,42.365788,1.0,22,25.0,2017,0.195781,B,B,23,5212,6,3,2,B,349107.666290,0,38.132453
48,7501,23,2.0,51.401212,35.980849,1.0,5,12.0,1977,0.034656,B,B,0,168,0,0,0,B,90834.351008,0,51.569732
52,1610,34,2.0,52.797699,36.958389,9.0,13,17.0,2017,0.069753,B,B,53,13670,4,1,11,B,194570.587236,0,56.849348
55,14659,74,2.0,66.944203,46.860942,1.0,8,7.0,1977,0.075779,B,B,6,1437,3,0,2,B,212801.122972,0,66.440664
78,10287,6,1.0,38.344873,26.841411,1.0,10,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,122254.105486,0,38.352374
79,1821,23,2.0,49.929489,34.950642,1.0,9,12.0,1977,0.034656,B,B,0,168,0,0,0,B,88464.425395,0,51.569732
84,1971,1,1.0,41.995577,29.396904,1.0,12,20.0,1977,0.007122,B,B,1,264,0,0,1,B,150371.070429,0,39.990203
85,8386,27,2.0,62.067272,43.447090,10.0,3,17.0,2017,0.017647,B,B,2,469,0,0,0,B,178467.117151,0,36.626949
115,10191,6,2.0,63.659749,44.561824,7.0,18,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188319.662097,0,37.873543
120,8853,30,3.0,80.467878,56.327514,10.0,8,17.0,2014,0.000078,B,B,22,6398,141,3,23,B,180315.190877,0,48.692296
274,3104,30,2.0,32.533803,22.773662,1.0,6,17.0,2015,0.000078,B,B,22,6398,141,3,23,B,115837.070662,0,59.226500
298,10188,23,2.0,51.543365,36.080355,0.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,86196.581698,0,51.569732
304,11164,75,2.0,48.525505,33.967853,5.0,6,5.0,1967,0.307467,B,A,30,5048,9,2,5,B,169876.764789,0,31.724268
318,15610,23,1.0,40.830363,28.581254,1.0,4,9.0,2016,0.034656,B,B,0,168,0,0,0,B,91775.321076,0,30.381045
353,4981,63,2.0,58.476185,40.933330,12.0,16,17.0,2017,0.238617,B,B,26,3889,6,3,6,B,328454.446132,0,33.745509
355,16360,48,1.0,40.915247,28.640673,1.0,20,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,209978.966130,0,22.077389
360,14380,58,1.0,40.525820,28.368074,1.0,16,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,116642.983817,0,22.588815
368,10776,63,1.0,40.711075,28.497752,8.0,10,17.0,1992,0.238617,B,B,26,3889,6,3,6,B,261337.768688,0,23.677259
407,9268,23,4.0,106.767678,74.737375,1.0,6,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,223132.085284,1,112.642841
422,12731,27,3.0,82.877358,58.014150,15.0,11,17.0,2016,0.072158,B,B,2,629,1,0,0,A,201620.866405,0,51.041416
442,13620,1,3.0,79.266760,55.486732,10.0,16,17.0,1977,0.007122,B,B,1,264,0,0,1,B,233890.854819,0,79.707512
444,10,6,3.0,75.888156,53.121709,1.0,11,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,218500.747041,0,67.718790
457,5504,6,1.0,43.741890,30.619323,1.0,9,25.0,2015,0.243205,B,B,5,1564,0,0,0,B,155443.611291,0,38.352374
461,1796,45,1.0,41.323212,28.926248,1.0,24,23.0,2017,0.195781,B,B,23,5212,6,3,2,B,245736.934369,0,21.693643
467,5300,30,3.0,169.509941,118.656958,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
479,14322,1,2.0,62.411905,43.688334,1.0,24,24.0,1977,0.007122,B,B,1,264,0,0,1,B,209817.034644,0,53.997766
500,13295,1,1.0,39.248800,27.474160,0.0,9,17.0,1977,0.007122,B,B,1,264,0,0,1,B,114363.123431,0,39.990203
527,10005,58,1.0,44.995130,31.496591,0.0,3,2.0,2019,0.437885,B,B,23,5735,3,0,5,B,106866.248746,0,22.588815
539,4935,23,1.0,28.859885,20.201919,1.0,12,11.0,1977,0.034656,B,B,0,168,0,0,0,B,68375.615508,0,30.381045
544,5402,27,4.0,98.649404,69.054583,1.0,3,1.0,2019,0.072158,B,B,2,629,1,0,0,A,294689.614794,1,100.855911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7571,10185,27,2.0,60.013077,42.009154,1.0,8,19.0,1977,0.211401,B,B,9,1892,0,0,1,B,137392.569761,0,36.626949
7580,15448,1,2.0,65.723452,46.006416,1.0,5,17.0,1977,0.007122,B,B,1,264,0,0,1,B,201704.639671,0,53.997766
7607,13090,1,2.0,68.425918,47.898143,1.0,7,9.0,1977,0.007122,B,B,1,264,0,0,1,B,239152.645700,0,53.997766
7621,15466,88,1.0,42.357487,29.650241,41.0,10,19.0,2016,0.127376,B,B,43,8429,3,3,9,B,194525.103119,0,21.796485
7639,14211,48,1.0,39.357596,27.550317,1.0,21,25.0,2017,0.041125,B,B,46,9515,5,1,10,B,220648.501332,0,22.077389
7648,216,62,3.0,87.003434,60.902404,1.0,3,1.0,2017,0.072158,B,B,2,629,1,0,0,A,225785.867439,0,86.386228
7668,9081,27,1.0,34.396472,24.077530,1.0,14,17.0,2016,0.011654,B,B,4,915,0,0,0,B,110728.588938,0,23.475787
7674,16234,27,2.0,57.943437,40.560406,10.0,16,17.0,2015,0.211401,B,B,9,1892,0,0,1,B,126779.219036,0,36.626949
7675,10390,1,1.0,39.264718,27.485303,1.0,7,17.0,1977,0.007122,B,B,1,264,0,0,1,B,127742.135416,0,39.990203
7690,2434,30,2.0,61.424774,42.997342,13.0,3,19.0,2015,0.000078,B,B,22,6398,141,3,23,B,133166.163513,0,59.226500
7701,7616,48,4.0,123.846928,86.692850,1.0,7,1.0,2015,0.041125,B,B,46,9515,5,1,10,B,595128.195352,1,125.650178
7705,16270,113,1.0,78.410874,54.887612,11.0,7,1.0,2018,0.050756,B,B,24,5469,1,0,1,B,292150.626080,0,22.426004
7712,4811,23,4.0,110.075277,77.052694,0.0,1,3.0,2016,0.034656,B,B,0,168,0,0,0,B,238325.639251,1,112.642841
7713,12437,30,2.0,55.242067,38.669447,1.0,4,4.0,2015,0.000078,B,B,22,6398,141,3,23,B,92135.018672,0,59.226500
7735,5367,1,3.0,81.227389,56.859172,0.0,14,17.0,1977,0.007122,B,B,1,264,0,0,1,B,218595.265514,0,79.707512
7738,15869,30,1.0,31.415062,21.990544,0.0,7,12.0,1977,0.000078,B,B,22,6398,141,3,23,B,68663.011388,0,40.240232
7740,2479,6,1.0,37.794877,26.456414,0.0,14,0.0,1977,0.243205,B,B,5,1564,0,0,0,B,148124.071590,0,38.352374
7763,14991,62,3.0,86.164240,60.314968,0.0,9,0.0,1977,0.072158,B,B,2,629,1,0,0,A,194709.995384,0,86.386228
7784,13537,6,1.0,38.874335,27.212035,1.0,5,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,128043.355789,0,38.352374
7835,13517,30,2.0,55.597409,38.918187,1.0,15,1.0,2013,0.000078,B,B,22,6398,141,3,23,B,153836.505669,0,59.226500
7850,396,54,3.0,110.119100,77.083370,1.0,8,1.0,2015,0.006076,B,B,30,5285,0,6,6,B,491296.245173,0,42.257742
7871,2277,52,1.0,38.555389,26.988772,0.0,14,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,113277.591887,0,23.548368
7872,15258,23,2.0,51.330209,35.931147,1.0,2,17.0,1977,0.034656,B,B,0,168,0,0,0,B,105059.285225,0,51.569732
7876,8715,25,1.0,32.797538,22.958277,1.0,15,13.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895
7927,3461,12,2.0,56.861937,39.803356,9.0,6,14.0,1995,0.090799,B,B,74,19083,2,5,15,B,240450.533232,0,33.909195
7931,769,23,2.0,54.023920,37.816744,10.0,3,3.0,1977,0.005767,B,B,1,388,0,0,0,B,93991.023578,0,51.569732
7970,11025,27,2.0,96.043563,67.230494,10.0,5,6.0,2014,0.075424,B,B,11,3097,0,0,0,B,126277.109148,0,36.626949
7982,3902,23,1.0,27.442238,19.209567,1.0,4,4.0,1977,0.034656,B,B,0,168,0,0,0,B,65547.071846,0,30.381045
7988,5234,30,1.0,29.947691,20.963383,1.0,11,22.0,2018,0.000078,B,B,22,6398,141,3,23,B,99110.577389,0,40.240232
7995,10013,30,2.0,62.219340,43.553538,1.0,4,2.0,2015,0.000078,B,B,22,6398,141,3,23,B,150136.610509,0,59.226500

In [79]:
#

In [80]:
#plt.scatter(train['LifeSquare'], train['Price']);

In [81]:
index_lf_250 = train.loc[(train['LifeSquare'] > 250), :].index
train.loc[index_lf_250, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
3825,2307,102,1.0,409.425181,286.597627,10.0,4,4.0,2016,0.238617,B,B,26,3889,6,3,6,B,90470.43083,0,225.347649

In [82]:
train.loc[train['LifeSquare'] > 250, 'LifeSquare'] = train['LifeSquare'] / 10
train.loc[index_lf_250, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
3825,2307,102,1.0,409.425181,28.659763,10.0,4,4.0,2016,0.238617,B,B,26,3889,6,3,6,B,90470.43083,0,225.347649

In [83]:
#### Проверка

In [84]:
train.loc[train['LifeSquare'] > train['Square'], :]

Empty DataFrame
Columns: [Id, DistrictId, Rooms, Square, LifeSquare, KitchenSquare, Floor, HouseFloor, HouseYear, Ecology_1, Ecology_2, Ecology_3, Social_1, Social_2, Social_3, Helthcare_2, Shops_1, Shops_2, Price, Large_flat, Median_lifesquare]
Index: []

In [85]:
#plt.scatter(train['LifeSquare'], train['Price']);

In [86]:
index_lf_100 = train.loc[(train['LifeSquare'] > 100), :].index
train.loc[index_lf_100, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
299,5548,86,5.0,275.645284,233.949309,26.0,12,37.0,2011,0.161976,B,A,31,7010,5,3,7,B,455264.882666,1,158.336567
371,4249,23,5.0,198.930182,123.139863,10.0,1,2.0,2011,0.014073,B,B,2,475,0,0,0,B,345665.209100,1,123.139863
467,5300,30,3.0,169.509941,118.656958,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
1001,5621,23,3.0,163.495333,161.504222,12.0,5,3.0,1977,0.014073,B,B,2,475,0,0,0,B,207007.956663,0,65.146215
1202,16568,27,4.0,200.334539,140.234178,25.0,1,2.0,2013,0.041116,B,B,53,14892,4,1,4,B,528560.506016,1,100.855911
1305,5030,17,2.0,102.683649,101.525114,1.0,20,1.0,1977,0.093443,B,B,23,4635,5,2,4,B,573999.459148,0,33.096094
1472,3267,58,3.0,138.980817,138.004600,43.0,2,2.0,1977,0.437885,B,B,23,5735,3,0,5,B,169528.896664,0,59.387001
2358,3718,56,3.0,190.857689,107.376164,19.0,7,3.0,2007,0.000000,B,B,23,5067,4,2,6,B,338644.075979,0,46.385710
2464,12638,27,3.0,138.427694,136.215499,0.0,4,3.0,2016,0.075424,B,B,11,3097,0,0,0,B,268394.744389,0,51.041416
2729,12552,58,3.0,116.405693,113.109653,112.0,3,3.0,2016,0.437885,B,B,23,5735,3,0,5,B,296165.936689,0,59.387001
2798,8901,34,5.0,121.577423,114.913843,1.0,25,1.0,1977,0.069753,B,B,53,13670,4,1,11,B,455446.393758,1,114.913843
3301,13434,13,5.0,183.382273,100.985505,15.0,2,6.0,1997,0.090799,B,B,74,19083,2,5,15,B,622888.825328,1,85.009616
3571,2603,30,3.0,162.587886,113.811520,0.0,2,3.0,1977,0.000078,B,B,22,6398,141,3,23,B,207407.352593,0,48.692296
3737,5563,23,3.0,104.200078,103.547051,1.0,25,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,245484.323624,0,65.146215
3780,14181,62,3.0,156.636577,153.685835,1.0,1,3.0,2005,0.072158,B,B,2,629,1,0,0,A,502523.573863,0,86.386228
4888,1453,62,3.0,106.330403,103.618474,0.0,5,17.0,2016,0.072158,B,B,2,629,1,0,0,A,248765.007260,0,86.386228
5075,12142,74,3.0,116.494390,115.110477,0.0,3,17.0,2018,0.309479,B,B,35,7715,4,0,6,B,404355.847831,0,46.963803
5467,11055,151,1.0,174.649522,122.254665,15.0,10,12.0,1958,0.236108,B,B,16,3893,27,3,10,B,232766.187698,0,22.769316
5920,500,27,3.0,117.898724,117.446940,0.0,11,12.0,2015,0.072158,B,B,2,629,1,0,0,A,256224.533278,0,51.041416
6866,7441,62,3.0,114.734473,112.589083,112.0,3,3.0,2015,0.072158,B,B,2,629,1,0,0,A,315245.521059,0,86.386228
7015,12570,62,3.0,137.907783,136.697187,15.0,4,3.0,1977,0.072158,B,B,2,629,1,0,0,A,295412.633601,0,86.386228
7030,6674,54,1.0,168.086347,125.486563,30.0,18,28.0,2011,0.006076,B,B,30,5285,0,6,6,B,367353.574566,0,54.542950
7534,6502,20,1.0,126.389517,103.637322,14.0,22,47.0,2012,0.019509,B,B,37,7687,11,5,5,B,450706.552655,0,23.124698
7673,10070,27,3.0,103.683549,102.886556,1.0,9,1.0,2018,0.072158,B,B,2,629,1,0,0,A,227866.350490,0,51.041416

In [87]:
train.loc[(train['LifeSquare'] > 100) & (train['Rooms'] <= 2), 'Rooms'] = 3
train.loc[index_lf_100, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
299,5548,86,5.0,275.645284,233.949309,26.0,12,37.0,2011,0.161976,B,A,31,7010,5,3,7,B,455264.882666,1,158.336567
371,4249,23,5.0,198.930182,123.139863,10.0,1,2.0,2011,0.014073,B,B,2,475,0,0,0,B,345665.209100,1,123.139863
467,5300,30,3.0,169.509941,118.656958,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
1001,5621,23,3.0,163.495333,161.504222,12.0,5,3.0,1977,0.014073,B,B,2,475,0,0,0,B,207007.956663,0,65.146215
1202,16568,27,4.0,200.334539,140.234178,25.0,1,2.0,2013,0.041116,B,B,53,14892,4,1,4,B,528560.506016,1,100.855911
1305,5030,17,3.0,102.683649,101.525114,1.0,20,1.0,1977,0.093443,B,B,23,4635,5,2,4,B,573999.459148,0,33.096094
1472,3267,58,3.0,138.980817,138.004600,43.0,2,2.0,1977,0.437885,B,B,23,5735,3,0,5,B,169528.896664,0,59.387001
2358,3718,56,3.0,190.857689,107.376164,19.0,7,3.0,2007,0.000000,B,B,23,5067,4,2,6,B,338644.075979,0,46.385710
2464,12638,27,3.0,138.427694,136.215499,0.0,4,3.0,2016,0.075424,B,B,11,3097,0,0,0,B,268394.744389,0,51.041416
2729,12552,58,3.0,116.405693,113.109653,112.0,3,3.0,2016,0.437885,B,B,23,5735,3,0,5,B,296165.936689,0,59.387001
2798,8901,34,5.0,121.577423,114.913843,1.0,25,1.0,1977,0.069753,B,B,53,13670,4,1,11,B,455446.393758,1,114.913843
3301,13434,13,5.0,183.382273,100.985505,15.0,2,6.0,1997,0.090799,B,B,74,19083,2,5,15,B,622888.825328,1,85.009616
3571,2603,30,3.0,162.587886,113.811520,0.0,2,3.0,1977,0.000078,B,B,22,6398,141,3,23,B,207407.352593,0,48.692296
3737,5563,23,3.0,104.200078,103.547051,1.0,25,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,245484.323624,0,65.146215
3780,14181,62,3.0,156.636577,153.685835,1.0,1,3.0,2005,0.072158,B,B,2,629,1,0,0,A,502523.573863,0,86.386228
4888,1453,62,3.0,106.330403,103.618474,0.0,5,17.0,2016,0.072158,B,B,2,629,1,0,0,A,248765.007260,0,86.386228
5075,12142,74,3.0,116.494390,115.110477,0.0,3,17.0,2018,0.309479,B,B,35,7715,4,0,6,B,404355.847831,0,46.963803
5467,11055,151,3.0,174.649522,122.254665,15.0,10,12.0,1958,0.236108,B,B,16,3893,27,3,10,B,232766.187698,0,22.769316
5920,500,27,3.0,117.898724,117.446940,0.0,11,12.0,2015,0.072158,B,B,2,629,1,0,0,A,256224.533278,0,51.041416
6866,7441,62,3.0,114.734473,112.589083,112.0,3,3.0,2015,0.072158,B,B,2,629,1,0,0,A,315245.521059,0,86.386228
7015,12570,62,3.0,137.907783,136.697187,15.0,4,3.0,1977,0.072158,B,B,2,629,1,0,0,A,295412.633601,0,86.386228
7030,6674,54,3.0,168.086347,125.486563,30.0,18,28.0,2011,0.006076,B,B,30,5285,0,6,6,B,367353.574566,0,54.542950
7534,6502,20,3.0,126.389517,103.637322,14.0,22,47.0,2012,0.019509,B,B,37,7687,11,5,5,B,450706.552655,0,23.124698
7673,10070,27,3.0,103.683549,102.886556,1.0,9,1.0,2018,0.072158,B,B,2,629,1,0,0,A,227866.350490,0,51.041416

In [88]:
#

In [89]:
#plt.scatter(train['Rooms'], train['LifeSquare']);

In [90]:
def correct_lifesquare(df):
    df = add_median_lifesquare(df, median_lifesquare)
    
    df.loc[(df['LifeSquare'] / df['Square']) >= 20, 'LifeSquare'] = (df['LifeSquare'] / 100)
    df.loc[((df['LifeSquare'] / df['Square']) >= 4) & (df['LifeSquare'] > 130) & (df['Rooms'] <= 3), 'LifeSquare'] = (df['LifeSquare'] / 10)
    df.loc[((df['LifeSquare'] / df['Square']) >= 8) & (df['Square'] < 12) & (df['Rooms'] <= 3), 'Square'] = df['Square'] * 10
    df.loc[(df['LifeSquare'] / df['Square']) >= 2, 'LifeSquare'] = df['Square'] * 0.7
    df.loc[df['LifeSquare'] < 1, 'LifeSquare'] = df['LifeSquare'] * 100
    df.loc[df['LifeSquare'] < 10, 'LifeSquare'] = df['LifeSquare'] * 10
    df.loc[(df['LifeSquare'] < 15) & (df['Square'] / df['LifeSquare'] > 2), 'LifeSquare'] = df['LifeSquare'] * 2
    df.loc[df['LifeSquare'] > df['Square'], 'LifeSquare'] = df['Square'] * 0.7
    df.loc[df['LifeSquare'] > 250, 'LifeSquare'] = df['LifeSquare'] / 10
    df.loc[(df['LifeSquare'] > 100) & (df['Rooms'] <= 2), 'Rooms'] = 3
    return df

In [91]:
train['LifeSquare'].describe()

count    8000.000000
mean       36.867090
std        15.516237
min         1.664073
25%        23.945023
50%        33.625826
75%        45.461937
max       233.949309
Name: LifeSquare, dtype: float64

##### Square

In [92]:
train['Square'].describe()

count    8000.000000
mean       56.277610
std        20.366119
min         2.377248
25%        41.751942
50%        52.549663
75%        65.931541
max       604.705972
Name: Square, dtype: float64

In [93]:
#plt.scatter(train['Square'], train['Price']);

In [94]:
index_square = train.loc[(train['Square'] > 250), 'Price'].index
train.loc[index_square, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
299,5548,86,5.0,275.645284,233.949309,26.0,12,37.0,2011,0.161976,B,A,31,7010,5,3,7,B,455264.882666,1,158.336567
1492,28,9,2.0,604.705972,31.560580,1.0,17,18.0,1977,0.161532,B,B,25,5648,1,2,4,B,187717.242538,0,31.560580
3825,2307,102,1.0,409.425181,28.659763,10.0,4,4.0,2016,0.238617,B,B,26,3889,6,3,6,B,90470.430830,0,225.347649

In [95]:
train.loc[(train['Square'] > 250) & (train['Rooms'] < 5), 'Square'] = train['Square'] / 10
train.loc[index_square, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
299,5548,86,5.0,275.645284,233.949309,26.0,12,37.0,2011,0.161976,B,A,31,7010,5,3,7,B,455264.882666,1,158.336567
1492,28,9,2.0,60.470597,31.560580,1.0,17,18.0,1977,0.161532,B,B,25,5648,1,2,4,B,187717.242538,0,31.560580
3825,2307,102,1.0,40.942518,28.659763,10.0,4,4.0,2016,0.238617,B,B,26,3889,6,3,6,B,90470.430830,0,225.347649

In [96]:
ind_s10 = train.loc[(train['Square'] < 10), :].index
train.loc[ind_s10, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1554,9487,5,1.0,5.129222,3.590455,1.0,1,1.0,1977,0.150818,B,B,16,3433,4,4,5,B,369472.403061,0,20.307073
6187,7657,38,1.0,4.502784,3.151949,1.0,28,1.0,1977,0.060753,B,B,15,2787,2,0,7,B,483283.488083,0,22.145046
6254,11526,27,1.0,4.633498,3.243449,1.0,18,1.0,1977,0.011654,B,B,4,915,0,0,0,B,107604.269441,0,23.475787
6843,3224,27,1.0,2.377248,1.664073,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798,0,23.475787
7036,6782,45,1.0,2.954309,2.068016,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,438005.182323,0,21.693643

In [97]:
train.loc[(train['Square'] < 10), 'Square'] = train['Square'] * 10
train.loc[ind_s10, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1554,9487,5,1.0,51.292216,3.590455,1.0,1,1.0,1977,0.150818,B,B,16,3433,4,4,5,B,369472.403061,0,20.307073
6187,7657,38,1.0,45.027837,3.151949,1.0,28,1.0,1977,0.060753,B,B,15,2787,2,0,7,B,483283.488083,0,22.145046
6254,11526,27,1.0,46.334984,3.243449,1.0,18,1.0,1977,0.011654,B,B,4,915,0,0,0,B,107604.269441,0,23.475787
6843,3224,27,1.0,23.772476,1.664073,0.0,1,0.0,1977,0.017647,B,B,2,469,0,0,0,B,126596.941798,0,23.475787
7036,6782,45,1.0,29.543086,2.068016,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,438005.182323,0,21.693643

In [98]:
ind_s30 = train.loc[(train['Square'] < 30) & ((train['Rooms'] == 2) | (train['Rooms'] == 3) | (train['Rooms'] == 4) | (train['Rooms'] == 5)), :].index
train.loc[ind_s30, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1352,12927,62,2.0,17.414181,12.189927,1.0,4,20.0,1977,0.072158,B,B,2,629,1,0,0,A,180750.471749,0,36.861647
1978,4352,104,2.0,28.517666,15.565872,3.0,7,6.0,1931,0.000078,B,B,22,6398,141,3,23,B,197245.267664,0,41.951063
3693,12676,81,3.0,13.784865,9.649405,7.0,4,5.0,1960,0.319809,B,B,25,4756,16,5,8,B,78388.806186,0,46.344367

In [99]:
train.loc[(train['Square'] < 30) & ((train['Rooms'] == 2) | (train['Rooms'] == 3) | (train['Rooms'] == 4) | (train['Rooms'] == 5)), 'Rooms'] = 1
train.loc[ind_s30, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1352,12927,62,1.0,17.414181,12.189927,1.0,4,20.0,1977,0.072158,B,B,2,629,1,0,0,A,180750.471749,0,36.861647
1978,4352,104,1.0,28.517666,15.565872,3.0,7,6.0,1931,0.000078,B,B,22,6398,141,3,23,B,197245.267664,0,41.951063
3693,12676,81,1.0,13.784865,9.649405,7.0,4,5.0,1960,0.319809,B,B,25,4756,16,5,8,B,78388.806186,0,46.344367

In [100]:
ind_s45 = train.loc[(train['Square'] < 45) & ((train['Rooms'] == 3) | (train['Rooms'] == 4) | (train['Rooms'] == 5)), :].index
train.loc[ind_s45, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
50,13772,96,4.0,44.128947,18.212628,10.0,10,13.0,2005,0.041116,B,B,53,14892,4,1,4,B,201374.604049,1,61.133253
5864,6358,27,5.0,42.003293,29.402305,0.0,5,12.0,1977,0.011654,B,B,4,915,0,0,0,B,112693.641769,1,29.402305
5880,16772,109,3.0,32.795221,22.956655,6.0,2,9.0,1979,0.136330,B,B,30,6141,10,3,6,B,173602.708629,0,45.416096
6298,7594,53,5.0,39.906082,39.394024,1.0,5,1.0,1977,0.049637,B,B,34,7759,0,1,3,B,206148.845716,1,39.394024

In [101]:
train.loc[(train['Square'] < 45) & ((train['Rooms'] == 3) | (train['Rooms'] == 4) | (train['Rooms'] == 5)), 'Rooms'] = 2
train.loc[ind_s45, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
50,13772,96,2.0,44.128947,18.212628,10.0,10,13.0,2005,0.041116,B,B,53,14892,4,1,4,B,201374.604049,1,61.133253
5864,6358,27,2.0,42.003293,29.402305,0.0,5,12.0,1977,0.011654,B,B,4,915,0,0,0,B,112693.641769,1,29.402305
5880,16772,109,2.0,32.795221,22.956655,6.0,2,9.0,1979,0.136330,B,B,30,6141,10,3,6,B,173602.708629,0,45.416096
6298,7594,53,2.0,39.906082,39.394024,1.0,5,1.0,1977,0.049637,B,B,34,7759,0,1,3,B,206148.845716,1,39.394024

In [102]:
ind_s60 = train.loc[(train['Square'] < 60) & ((train['Rooms'] == 4) | (train['Rooms'] == 5)), :].index
train.loc[ind_s60, :]

Empty DataFrame
Columns: [Id, DistrictId, Rooms, Square, LifeSquare, KitchenSquare, Floor, HouseFloor, HouseYear, Ecology_1, Ecology_2, Ecology_3, Social_1, Social_2, Social_3, Helthcare_2, Shops_1, Shops_2, Price, Large_flat, Median_lifesquare]
Index: []

In [103]:
train.loc[(train['Square'] < 60) & ((train['Rooms'] == 4) | (train['Rooms'] == 5)), 'Rooms'] = 3
train.loc[ind_s60, :]

Empty DataFrame
Columns: [Id, DistrictId, Rooms, Square, LifeSquare, KitchenSquare, Floor, HouseFloor, HouseYear, Ecology_1, Ecology_2, Ecology_3, Social_1, Social_2, Social_3, Helthcare_2, Shops_1, Shops_2, Price, Large_flat, Median_lifesquare]
Index: []

In [104]:
ind_s75 = train.loc[(train['Square'] < 75) & (train['Rooms'] == 5), :].index
train.loc[ind_s75, :]

Empty DataFrame
Columns: [Id, DistrictId, Rooms, Square, LifeSquare, KitchenSquare, Floor, HouseFloor, HouseYear, Ecology_1, Ecology_2, Ecology_3, Social_1, Social_2, Social_3, Helthcare_2, Shops_1, Shops_2, Price, Large_flat, Median_lifesquare]
Index: []

In [105]:
train.loc[(train['Square'] < 75) & (train['Rooms'] == 5), 'Rooms'] = 4
train.loc[ind_s75, :]

Empty DataFrame
Columns: [Id, DistrictId, Rooms, Square, LifeSquare, KitchenSquare, Floor, HouseFloor, HouseYear, Ecology_1, Ecology_2, Ecology_3, Social_1, Social_2, Social_3, Helthcare_2, Shops_1, Shops_2, Price, Large_flat, Median_lifesquare]
Index: []

In [106]:
#plt.scatter(train['Square'], train['Price']);

In [107]:
#plt.scatter(train['Rooms'], train['Square']);

In [108]:
index_sq_150 = train.loc[(train['Square'] > 150), 'Price'].index
train.loc[index_sq_150, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
299,5548,86,5.0,275.645284,233.949309,26.0,12,37.0,2011,0.161976,B,A,31,7010,5,3,7,B,455264.882666,1,158.336567
371,4249,23,5.0,198.930182,123.139863,10.0,1,2.0,2011,0.014073,B,B,2,475,0,0,0,B,345665.209100,1,123.139863
467,5300,30,3.0,169.509941,118.656958,1.0,2,2.0,2018,0.000078,B,B,22,6398,141,3,23,B,200800.673767,0,48.692296
775,4991,93,3.0,167.767027,45.755033,1.0,1,1.0,1977,0.004949,B,B,0,186,0,0,0,B,211180.794219,0,45.755033
1001,5621,23,3.0,163.495333,161.504222,12.0,5,3.0,1977,0.014073,B,B,2,475,0,0,0,B,207007.956663,0,65.146215
1202,16568,27,4.0,200.334539,140.234178,25.0,1,2.0,2013,0.041116,B,B,53,14892,4,1,4,B,528560.506016,1,100.855911
1854,16204,23,1.0,160.647588,30.381045,1.0,3,3.0,1977,0.014073,B,B,2,475,0,0,0,B,217874.997452,0,30.381045
2358,3718,56,3.0,190.857689,107.376164,19.0,7,3.0,2007,0.000000,B,B,23,5067,4,2,6,B,338644.075979,0,46.385710
2569,3914,24,4.0,155.930023,76.831293,15.0,6,22.0,2012,0.111627,B,B,50,12238,8,2,3,B,559886.965348,1,76.831293
2883,14556,183,4.0,151.150660,98.187482,23.0,6,7.0,1912,0.037316,B,B,32,6748,93,4,10,B,284884.959104,1,98.187482
3301,13434,13,5.0,183.382273,100.985505,15.0,2,6.0,1997,0.090799,B,B,74,19083,2,5,15,B,622888.825328,1,85.009616
3571,2603,30,3.0,162.587886,113.811520,0.0,2,3.0,1977,0.000078,B,B,22,6398,141,3,23,B,207407.352593,0,48.692296
3780,14181,62,3.0,156.636577,153.685835,1.0,1,3.0,2005,0.072158,B,B,2,629,1,0,0,A,502523.573863,0,86.386228
3829,5376,93,2.0,170.379494,33.284043,1.0,3,2.0,1977,0.004949,B,B,0,186,0,0,0,B,194582.912756,0,33.284043
4933,5602,93,3.0,169.385184,45.755033,1.0,2,10.0,1977,0.004949,B,B,0,186,0,0,0,B,190949.293998,0,45.755033
5467,11055,151,3.0,174.649522,122.254665,15.0,10,12.0,1958,0.236108,B,B,16,3893,27,3,10,B,232766.187698,0,22.769316
5825,15947,129,4.0,185.906396,84.830074,31.0,5,3.0,2015,0.020741,B,B,24,5613,5,2,5,B,340273.238253,1,84.830074
6867,11764,93,3.0,169.117203,45.755033,1.0,5,3.0,1977,0.004949,B,B,0,186,0,0,0,B,211325.577641,0,45.755033
7030,6674,54,3.0,168.086347,125.486563,30.0,18,28.0,2011,0.006076,B,B,30,5285,0,6,6,B,367353.574566,0,54.542950

In [109]:
index_sq_ls_150 = train.loc[(train['Square'] > 150) & ((train['Square'] / train['LifeSquare']) > 3 ), :].index
train.loc[index_sq_ls_150, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
775,4991,93,3.0,167.767027,45.755033,1.0,1,1.0,1977,0.004949,B,B,0,186,0,0,0,B,211180.794219,0,45.755033
1854,16204,23,1.0,160.647588,30.381045,1.0,3,3.0,1977,0.014073,B,B,2,475,0,0,0,B,217874.997452,0,30.381045
3829,5376,93,2.0,170.379494,33.284043,1.0,3,2.0,1977,0.004949,B,B,0,186,0,0,0,B,194582.912756,0,33.284043
4933,5602,93,3.0,169.385184,45.755033,1.0,2,10.0,1977,0.004949,B,B,0,186,0,0,0,B,190949.293998,0,45.755033
6867,11764,93,3.0,169.117203,45.755033,1.0,5,3.0,1977,0.004949,B,B,0,186,0,0,0,B,211325.577641,0,45.755033

In [110]:
train.loc[((train['Square'] > 150) & ((train['Square'] / train['LifeSquare']) > 3 ) & ('Rooms' == 1)), 'Rooms'] = 3
train.loc[index_sq_ls_150, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
775,4991,93,3.0,167.767027,45.755033,1.0,1,1.0,1977,0.004949,B,B,0,186,0,0,0,B,211180.794219,0,45.755033
1854,16204,23,1.0,160.647588,30.381045,1.0,3,3.0,1977,0.014073,B,B,2,475,0,0,0,B,217874.997452,0,30.381045
3829,5376,93,2.0,170.379494,33.284043,1.0,3,2.0,1977,0.004949,B,B,0,186,0,0,0,B,194582.912756,0,33.284043
4933,5602,93,3.0,169.385184,45.755033,1.0,2,10.0,1977,0.004949,B,B,0,186,0,0,0,B,190949.293998,0,45.755033
6867,11764,93,3.0,169.117203,45.755033,1.0,5,3.0,1977,0.004949,B,B,0,186,0,0,0,B,211325.577641,0,45.755033

In [111]:
#

In [112]:
ind_s_r_1 = train.loc[(train['Square'] > 60) & (train['Rooms'] == 1 ), :].index
train.loc[ind_s_r_1, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
0,12473,58,1.0,65.271225,62.798045,1.0,3,1.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849.693542,0,22.588815
23,13670,22,1.0,87.485627,19.131630,0.0,16,0.0,1977,0.118537,B,B,30,6207,1,1,0,B,361744.269547,0,19.131630
203,13603,63,1.0,127.651237,26.097116,1.0,8,17.0,2016,0.238617,B,B,26,3889,6,3,6,B,594565.299770,0,23.677259
385,13440,6,1.0,78.432890,40.441742,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,222826.758816,0,38.352374
816,1699,9,1.0,78.936164,76.746654,1.0,8,7.0,1977,0.161532,B,B,25,5648,1,2,4,B,226206.962435,0,22.079346
1014,8849,45,1.0,63.419553,22.863568,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,325600.765809,0,21.693643
1046,16332,23,1.0,63.714931,30.381045,1.0,11,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,152263.886454,0,30.381045
1115,6186,1,1.0,62.006079,39.990203,1.0,7,1.0,1977,0.007122,B,B,1,264,0,0,1,B,197006.124188,0,39.990203
1297,9021,23,1.0,103.744170,72.620919,1.0,26,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,223249.331500,0,30.381045
1597,7178,22,1.0,64.561270,19.131630,1.0,9,17.0,1977,0.118537,B,B,30,6207,1,1,0,B,184554.326180,0,19.131630
1702,15229,6,1.0,62.007598,60.925062,1.0,3,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,195493.300595,0,38.352374
1854,16204,23,1.0,160.647588,30.381045,1.0,3,3.0,1977,0.014073,B,B,2,475,0,0,0,B,217874.997452,0,30.381045
1953,14662,23,1.0,148.179026,30.381045,1.0,1,2.0,1977,0.014073,B,B,2,475,0,0,0,B,160902.854650,0,30.381045
2012,14773,30,1.0,105.619549,87.387096,5.0,14,39.0,2010,0.000078,B,B,22,6398,141,3,23,B,476843.942405,0,40.240232
2243,16638,38,1.0,106.260300,74.382210,1.0,4,1.0,1977,0.060753,B,B,15,2787,2,0,7,B,509162.416594,0,22.145046
2283,9552,23,1.0,105.432181,73.802526,0.0,3,2.0,1977,0.014073,B,B,2,475,0,0,0,B,218718.046451,0,30.381045
2417,1754,6,1.0,61.978423,39.432987,1.0,1,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,177116.339701,0,38.352374
2492,4458,27,1.0,65.322105,37.224179,1.0,2,1.0,2017,0.014058,B,B,1,290,0,0,0,B,116069.938826,0,23.475787
2503,6072,6,1.0,65.102017,64.622603,1.0,10,9.0,2015,0.243205,B,B,5,1564,0,0,0,B,175899.978284,0,38.352374
2558,6589,30,1.0,62.110823,52.812128,4.0,31,44.0,2009,0.000078,B,B,22,6398,141,3,23,B,117647.461002,0,40.240232
2707,15157,54,1.0,106.239622,83.296167,17.0,26,37.0,2009,0.006076,B,B,30,5285,0,6,6,B,274139.065875,0,54.542950
2772,11625,84,1.0,102.640234,78.746443,19.0,26,36.0,2012,0.006076,B,B,30,5285,0,6,6,B,342223.033781,0,20.996490
2803,1096,1,1.0,62.562518,39.990203,1.0,11,1.0,1977,0.007122,B,B,1,264,0,0,1,B,197569.582936,0,39.990203
2856,1428,27,1.0,62.973855,19.795411,19.0,4,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,151261.777244,0,23.475787
2946,2967,1,1.0,62.494611,34.896944,0.0,1,0.0,1977,0.007122,B,B,1,264,0,0,1,B,193568.854208,0,39.990203
3302,3522,6,1.0,66.419841,39.871009,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,193361.229815,0,38.352374
3862,0,0,1.0,109.144492,84.613939,15.0,6,15.0,2011,0.319809,B,B,25,4756,16,5,8,B,289034.391871,0,21.335474
3958,2270,27,1.0,69.135583,68.232968,1.0,3,1.0,1977,0.011654,B,B,4,915,0,0,0,B,174590.373323,0,23.475787
4209,478,6,1.0,65.685851,38.352374,1.0,13,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188642.549176,0,38.352374
4333,12335,9,1.0,60.022123,28.583693,1.0,9,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,176731.431750,0,22.079346
4487,14588,23,1.0,106.514211,30.381045,1.0,1,2.0,1977,0.014073,B,B,2,475,0,0,0,B,242956.031432,0,30.381045
4632,11599,23,1.0,121.988052,30.381045,1.0,2,2.0,1977,0.014073,B,B,2,475,0,0,0,B,273307.249093,0,30.381045
4666,3614,24,1.0,65.857744,29.912816,17.0,7,22.0,2010,0.111627,B,B,50,12238,8,2,3,B,87463.729219,0,23.389607
4891,11179,27,1.0,63.629664,62.489687,1.0,4,22.0,2015,0.211401,B,B,9,1892,0,0,1,B,150432.107862,0,23.475787
5014,13204,93,1.0,68.218458,64.800783,1.0,3,9.0,2013,0.012522,B,B,2,507,0,0,0,B,86540.216330,0,21.171292
5027,7815,6,1.0,74.609609,52.226727,1.0,16,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,216181.637056,0,38.352374
5159,13773,15,1.0,64.894962,37.975900,12.0,9,14.0,2006,0.158249,B,B,21,5731,0,1,0,B,286626.448908,0,21.314096
5366,9275,113,1.0,101.737698,74.881315,16.0,23,24.0,2019,0.050756,B,B,24,5469,1,0,1,B,396825.943131,0,22.426004
5554,13559,79,1.0,96.838013,49.140960,22.0,19,24.0,2016,0.050756,B,B,24,5469,1,0,1,B,348962.861294,0,21.293780
5718,16504,27,1.0,72.486741,58.944462,20.0,6,6.0,2017,0.075424,B,B,11,3097,0,0,0,B,195520.319385,0,23.475787
5961,7789,146,1.0,60.890931,45.768512,11.0,13,32.0,2011,0.236108,B,B,16,3893,27,3,10,B,227510.033762,0,21.564404
6121,7803,59,1.0,60.771554,20.638847,0.0,22,25.0,2017,0.019509,B,B,37,7687,11,5,5,B,266621.110418,0,20.638847
6214,11459,79,1.0,98.727990,49.781722,22.0,18,24.0,2019,0.050756,B,B,24,5469,1,0,1,B,351021.797311,0,21.293780
6432,1394,27,1.0,61.469716,26.684677,15.0,5,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,155874.732400,0,23.475787
6587,12164,24,1.0,70.567808,67.238393,1.0,9,16.0,2015,0.111627,B,B,50,12238,8,2,3,B,370121.277371,0,23.389607
6624,5021,30,1.0,63.620542,40.240232,1.0,4,17.0,1977,0.000078,B,B,22,6398,141,3,23,B,173209.186142,0,40.240232
6690,14921,27,1.0,85.185408,23.475787,1.0,3,2.0,2016,0.211401,B,B,9,1892,0,0,1,B,204223.826341,0,23.475787
6864,13178,30,1.0,111.680625,40.240232,1.0,9,8.0,2015,0.000078,B,B,22,6398,141,3,23,B,456417.428803,0,40.240232
6921,7878,27,1.0,67.746361,67.347172,1.0,3,17.0,2017,0.017647,B,B,2,469,0,0,0,B,179294.237176,0,23.475787
7235,3154,85,1.0,72.998799,20.855406,12.0,13,17.0,1977,0.037178,B,B,52,11217,1,1,7,B,374073.836779,0,20.855406
7362,8824,27,1.0,62.451190,53.618269,14.0,7,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,152956.829998,0,23.475787
7705,16270,113,1.0,78.410874,54.887612,11.0,7,1.0,2018,0.050756,B,B,24,5469,1,0,1,B,292150.626080,0,22.426004
7725,12555,162,1.0,60.014279,36.656730,10.0,2,6.0,1956,0.236108,B,B,16,3893,27,3,10,B,304424.418395,0,30.628398
7868,16578,113,1.0,103.196375,84.122714,20.0,5,25.0,2017,0.050756,B,B,24,5469,1,0,1,B,366400.936549,0,22.426004

In [113]:
train.loc[((train['Square'] > 60) & (train['Square'] <= 100)) & (train['Rooms'] == 1 ), 'Rooms'] = 2
train.loc[((train['Square'] > 100) & (train['Square'] <= 150)) & (train['Rooms'] == 1 ), 'Rooms'] = 3
train.loc[(train['Square'] > 150) & (train['Rooms'] == 1 ), 'Rooms'] = 4
train.loc[ind_s_r_1, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
0,12473,58,2.0,65.271225,62.798045,1.0,3,1.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849.693542,0,22.588815
23,13670,22,2.0,87.485627,19.131630,0.0,16,0.0,1977,0.118537,B,B,30,6207,1,1,0,B,361744.269547,0,19.131630
203,13603,63,3.0,127.651237,26.097116,1.0,8,17.0,2016,0.238617,B,B,26,3889,6,3,6,B,594565.299770,0,23.677259
385,13440,6,2.0,78.432890,40.441742,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,222826.758816,0,38.352374
816,1699,9,2.0,78.936164,76.746654,1.0,8,7.0,1977,0.161532,B,B,25,5648,1,2,4,B,226206.962435,0,22.079346
1014,8849,45,2.0,63.419553,22.863568,1.0,3,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,325600.765809,0,21.693643
1046,16332,23,2.0,63.714931,30.381045,1.0,11,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,152263.886454,0,30.381045
1115,6186,1,2.0,62.006079,39.990203,1.0,7,1.0,1977,0.007122,B,B,1,264,0,0,1,B,197006.124188,0,39.990203
1297,9021,23,3.0,103.744170,72.620919,1.0,26,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,223249.331500,0,30.381045
1597,7178,22,2.0,64.561270,19.131630,1.0,9,17.0,1977,0.118537,B,B,30,6207,1,1,0,B,184554.326180,0,19.131630
1702,15229,6,2.0,62.007598,60.925062,1.0,3,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,195493.300595,0,38.352374
1854,16204,23,4.0,160.647588,30.381045,1.0,3,3.0,1977,0.014073,B,B,2,475,0,0,0,B,217874.997452,0,30.381045
1953,14662,23,3.0,148.179026,30.381045,1.0,1,2.0,1977,0.014073,B,B,2,475,0,0,0,B,160902.854650,0,30.381045
2012,14773,30,3.0,105.619549,87.387096,5.0,14,39.0,2010,0.000078,B,B,22,6398,141,3,23,B,476843.942405,0,40.240232
2243,16638,38,3.0,106.260300,74.382210,1.0,4,1.0,1977,0.060753,B,B,15,2787,2,0,7,B,509162.416594,0,22.145046
2283,9552,23,3.0,105.432181,73.802526,0.0,3,2.0,1977,0.014073,B,B,2,475,0,0,0,B,218718.046451,0,30.381045
2417,1754,6,2.0,61.978423,39.432987,1.0,1,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,177116.339701,0,38.352374
2492,4458,27,2.0,65.322105,37.224179,1.0,2,1.0,2017,0.014058,B,B,1,290,0,0,0,B,116069.938826,0,23.475787
2503,6072,6,2.0,65.102017,64.622603,1.0,10,9.0,2015,0.243205,B,B,5,1564,0,0,0,B,175899.978284,0,38.352374
2558,6589,30,2.0,62.110823,52.812128,4.0,31,44.0,2009,0.000078,B,B,22,6398,141,3,23,B,117647.461002,0,40.240232
2707,15157,54,3.0,106.239622,83.296167,17.0,26,37.0,2009,0.006076,B,B,30,5285,0,6,6,B,274139.065875,0,54.542950
2772,11625,84,3.0,102.640234,78.746443,19.0,26,36.0,2012,0.006076,B,B,30,5285,0,6,6,B,342223.033781,0,20.996490
2803,1096,1,2.0,62.562518,39.990203,1.0,11,1.0,1977,0.007122,B,B,1,264,0,0,1,B,197569.582936,0,39.990203
2856,1428,27,2.0,62.973855,19.795411,19.0,4,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,151261.777244,0,23.475787
2946,2967,1,2.0,62.494611,34.896944,0.0,1,0.0,1977,0.007122,B,B,1,264,0,0,1,B,193568.854208,0,39.990203
3302,3522,6,2.0,66.419841,39.871009,1.0,2,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,193361.229815,0,38.352374
3862,0,0,3.0,109.144492,84.613939,15.0,6,15.0,2011,0.319809,B,B,25,4756,16,5,8,B,289034.391871,0,21.335474
3958,2270,27,2.0,69.135583,68.232968,1.0,3,1.0,1977,0.011654,B,B,4,915,0,0,0,B,174590.373323,0,23.475787
4209,478,6,2.0,65.685851,38.352374,1.0,13,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188642.549176,0,38.352374
4333,12335,9,2.0,60.022123,28.583693,1.0,9,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,176731.431750,0,22.079346
4487,14588,23,3.0,106.514211,30.381045,1.0,1,2.0,1977,0.014073,B,B,2,475,0,0,0,B,242956.031432,0,30.381045
4632,11599,23,3.0,121.988052,30.381045,1.0,2,2.0,1977,0.014073,B,B,2,475,0,0,0,B,273307.249093,0,30.381045
4666,3614,24,2.0,65.857744,29.912816,17.0,7,22.0,2010,0.111627,B,B,50,12238,8,2,3,B,87463.729219,0,23.389607
4891,11179,27,2.0,63.629664,62.489687,1.0,4,22.0,2015,0.211401,B,B,9,1892,0,0,1,B,150432.107862,0,23.475787
5014,13204,93,2.0,68.218458,64.800783,1.0,3,9.0,2013,0.012522,B,B,2,507,0,0,0,B,86540.216330,0,21.171292
5027,7815,6,2.0,74.609609,52.226727,1.0,16,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,216181.637056,0,38.352374
5159,13773,15,2.0,64.894962,37.975900,12.0,9,14.0,2006,0.158249,B,B,21,5731,0,1,0,B,286626.448908,0,21.314096
5366,9275,113,3.0,101.737698,74.881315,16.0,23,24.0,2019,0.050756,B,B,24,5469,1,0,1,B,396825.943131,0,22.426004
5554,13559,79,2.0,96.838013,49.140960,22.0,19,24.0,2016,0.050756,B,B,24,5469,1,0,1,B,348962.861294,0,21.293780
5718,16504,27,2.0,72.486741,58.944462,20.0,6,6.0,2017,0.075424,B,B,11,3097,0,0,0,B,195520.319385,0,23.475787
5961,7789,146,2.0,60.890931,45.768512,11.0,13,32.0,2011,0.236108,B,B,16,3893,27,3,10,B,227510.033762,0,21.564404
6121,7803,59,2.0,60.771554,20.638847,0.0,22,25.0,2017,0.019509,B,B,37,7687,11,5,5,B,266621.110418,0,20.638847
6214,11459,79,2.0,98.727990,49.781722,22.0,18,24.0,2019,0.050756,B,B,24,5469,1,0,1,B,351021.797311,0,21.293780
6432,1394,27,2.0,61.469716,26.684677,15.0,5,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,155874.732400,0,23.475787
6587,12164,24,2.0,70.567808,67.238393,1.0,9,16.0,2015,0.111627,B,B,50,12238,8,2,3,B,370121.277371,0,23.389607
6624,5021,30,2.0,63.620542,40.240232,1.0,4,17.0,1977,0.000078,B,B,22,6398,141,3,23,B,173209.186142,0,40.240232
6690,14921,27,2.0,85.185408,23.475787,1.0,3,2.0,2016,0.211401,B,B,9,1892,0,0,1,B,204223.826341,0,23.475787
6864,13178,30,3.0,111.680625,40.240232,1.0,9,8.0,2015,0.000078,B,B,22,6398,141,3,23,B,456417.428803,0,40.240232
6921,7878,27,2.0,67.746361,67.347172,1.0,3,17.0,2017,0.017647,B,B,2,469,0,0,0,B,179294.237176,0,23.475787
7235,3154,85,2.0,72.998799,20.855406,12.0,13,17.0,1977,0.037178,B,B,52,11217,1,1,7,B,374073.836779,0,20.855406
7362,8824,27,2.0,62.451190,53.618269,14.0,7,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,152956.829998,0,23.475787
7705,16270,113,2.0,78.410874,54.887612,11.0,7,1.0,2018,0.050756,B,B,24,5469,1,0,1,B,292150.626080,0,22.426004
7725,12555,162,2.0,60.014279,36.656730,10.0,2,6.0,1956,0.236108,B,B,16,3893,27,3,10,B,304424.418395,0,30.628398
7868,16578,113,3.0,103.196375,84.122714,20.0,5,25.0,2017,0.050756,B,B,24,5469,1,0,1,B,366400.936549,0,22.426004

In [114]:
#plt.scatter(train['Rooms'], train['Square']);

In [115]:
ind_s_r_2 = train.loc[(train['Square'] > 120) & (train['Rooms'] == 2 ), :].index
train.loc[ind_s_r_2, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
3829,5376,93,2.0,170.379494,33.284043,1.0,3,2.0,1977,0.004949,B,B,0,186,0,0,0,B,194582.912756,0,33.284043
4223,7111,27,2.0,139.070296,89.787666,42.0,5,3.0,2016,0.014073,B,B,2,475,0,0,0,B,153946.777452,0,36.626949

In [116]:
train.loc[((train['Square'] > 120) & (train['Square'] <= 150)) & (train['Rooms'] == 2 ), 'Rooms'] = 3
train.loc[((train['Square'] > 150) & (train['Square'] <= 200)) & (train['Rooms'] == 2 ), 'Rooms'] = 4
train.loc[ind_s_r_2, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
3829,5376,93,4.0,170.379494,33.284043,1.0,3,2.0,1977,0.004949,B,B,0,186,0,0,0,B,194582.912756,0,33.284043
4223,7111,27,3.0,139.070296,89.787666,42.0,5,3.0,2016,0.014073,B,B,2,475,0,0,0,B,153946.777452,0,36.626949

In [117]:
#

In [118]:
ind_s_r_5 = train.loc[(train['Square'] < 100) & (train['Rooms'] == 5 ), :].index
train.loc[ind_s_r_5, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
2898,238,88,5.0,90.762276,70.991790,5.0,1,9.0,1972,0.127376,B,B,43,8429,3,3,9,B,289683.939174,1,70.991790
5448,4282,195,5.0,95.617533,62.377052,7.0,7,7.0,1940,0.015017,B,B,17,3079,59,0,8,B,479525.147323,1,62.377052
6644,4214,105,5.0,85.313605,56.686693,5.0,4,12.0,1967,0.040243,B,B,25,3478,11,3,1,B,461678.738428,1,56.686693

In [119]:
train.loc[(train['Square'] < 100) & (train['Rooms'] == 5 ), 'Rooms'] = 4
train.loc[ind_s_r_5, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
2898,238,88,4.0,90.762276,70.991790,5.0,1,9.0,1972,0.127376,B,B,43,8429,3,3,9,B,289683.939174,1,70.991790
5448,4282,195,4.0,95.617533,62.377052,7.0,7,7.0,1940,0.015017,B,B,17,3079,59,0,8,B,479525.147323,1,62.377052
6644,4214,105,4.0,85.313605,56.686693,5.0,4,12.0,1967,0.040243,B,B,25,3478,11,3,1,B,461678.738428,1,56.686693

In [120]:
#plt.scatter(train['Rooms'], train['Square']);

In [121]:
#plt.scatter(train['Rooms'], train['LifeSquare']);

In [122]:
def correct_square(df):
    df.loc[(df['Square'] > 250) & (df['Rooms'] < 5), 'Square'] = df['Square'] / 10
    df.loc[(df['Square'] < 10), 'Square'] = df['Square'] * 10
    df.loc[(df['Square'] < 30) & ((df['Rooms'] == 2) | (df['Rooms'] == 3) | (df['Rooms'] == 4) | (df['Rooms'] == 5)), 'Rooms'] = 1
    df.loc[(df['Square'] < 45) & ((df['Rooms'] == 3) | (df['Rooms'] == 4) | (df['Rooms'] == 5)), 'Rooms'] = 2
    df.loc[(df['Square'] < 60) & ((df['Rooms'] == 4) | (df['Rooms'] == 5)), 'Rooms'] = 3
    df.loc[(df['Square'] < 75) & (df['Rooms'] == 5), 'Rooms'] = 4
    df.loc[((df['Square'] > 150) & ((df['Square'] / df['LifeSquare']) > 3 ) & ('Rooms' == 1)), 'Rooms'] = 3
    df.loc[((df['Square'] > 60) & (df['Square'] <= 100)) & (df['Rooms'] == 1 ), 'Rooms'] = 2
    df.loc[((df['Square'] > 100) & (df['Square'] <= 150)) & (df['Rooms'] == 1 ), 'Rooms'] = 3
    df.loc[(df['Square'] > 150) & (df['Rooms'] == 1 ), 'Rooms'] = 4
    df.loc[((df['Square'] > 120) & (df['Square'] <= 150)) & (df['Rooms'] == 2 ), 'Rooms'] = 3
    df.loc[((df['Square'] > 150) & (df['Square'] <= 200)) & (df['Rooms'] == 2 ), 'Rooms'] = 4
    df.loc[(df['Square'] < 100) & (df['Rooms'] == 5 ), 'Rooms'] = 4
    return df

In [123]:
train['Square'].describe()

count    8000.000000
mean       56.185567
std        18.977563
min        13.784865
25%        41.754680
50%        52.544854
75%        65.926358
max       275.645284
Name: Square, dtype: float64

##### KitchenSquare

In [124]:
train['KitchenSquare'].describe()

count    8000.00000
mean        6.37875
std        31.84321
min         0.00000
25%         1.00000
50%         6.00000
75%         9.00000
max      2014.00000
Name: KitchenSquare, dtype: float64

In [125]:
train['KitchenSquare'].nunique()

52

In [126]:
#plt.scatter(train['Rooms'], train['KitchenSquare']);

In [127]:
ind_k_250 = train.loc[train['KitchenSquare'] > 250, :].index
train.loc[ind_k_250, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1452,14679,81,1.0,32.276663,19.278394,1970.0,6,1.0,1977,0.006076,B,B,30,5285,0,6,6,B,105539.556275,0,21.470132
4058,14656,62,1.0,47.100719,46.447960,2014.0,4,1.0,2014,0.072158,B,B,2,629,1,0,0,A,108337.484207,0,22.893747

In [128]:
train.loc[train['KitchenSquare'] > 250, 'KitchenSquare'] = round(train['Square'] / 4, 1)
train.loc[ind_k_250, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1452,14679,81,1.0,32.276663,19.278394,8.1,6,1.0,1977,0.006076,B,B,30,5285,0,6,6,B,105539.556275,0,21.470132
4058,14656,62,1.0,47.100719,46.447960,11.8,4,1.0,2014,0.072158,B,B,2,629,1,0,0,A,108337.484207,0,22.893747

In [129]:
#

In [130]:
#plt.scatter(train['Rooms'], train['KitchenSquare']);

In [131]:
ind_ks_20 = train.loc[(train['KitchenSquare'] > 20) & (train['Rooms'] == 1 ), :].index
train.loc[ind_ks_20, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
105,2271,27,1.0,43.292516,42.835643,40.0,12,11.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787
656,1315,6,1.0,48.128114,45.023531,48.0,21,1.0,2013,0.243205,B,B,5,1564,0,0,0,B,146950.912410,0,38.352374
3004,11624,46,1.0,42.983283,24.224435,37.0,15,16.0,1983,0.188784,B,B,31,6137,4,0,1,B,198450.736353,0,22.060771
3722,10546,62,1.0,46.013187,43.417043,43.0,4,17.0,2019,0.072158,B,B,2,629,1,0,0,A,113909.099428,0,22.893747
4401,673,27,1.0,54.418214,51.498581,51.0,10,17.0,2017,0.072158,B,B,2,629,1,0,0,A,133273.635012,0,23.475787
4990,15781,10,1.0,35.813564,19.953992,35.0,6,14.0,1971,0.282798,B,B,33,8667,2,0,6,B,164306.314182,0,19.796380
5697,13703,42,1.0,38.071692,19.723548,73.0,9,10.0,2006,0.158249,B,B,21,5731,0,1,0,B,160488.033165,0,21.634588
5879,6569,27,1.0,38.220258,18.716856,84.0,4,17.0,2018,0.011654,B,B,4,915,0,0,0,B,99079.960518,0,23.475787
7173,6708,48,1.0,42.069359,22.487739,39.0,1,10.0,2010,0.041125,B,B,46,9515,5,1,10,B,200021.835127,0,22.077389
7319,9690,27,1.0,40.081042,37.834964,37.0,18,19.0,2019,0.211401,B,B,9,1892,0,0,1,B,93218.650461,0,23.475787
7621,15466,88,1.0,42.357487,29.650241,41.0,10,19.0,2016,0.127376,B,B,43,8429,3,3,9,B,194525.103119,0,21.796485

In [132]:
train.loc[(train['KitchenSquare'] > 20) & (train['Rooms'] == 1 ), 'KitchenSquare'] = round(train['Square'] / 4, 1)
train.loc[ind_ks_20, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
105,2271,27,1.0,43.292516,42.835643,10.8,12,11.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787
656,1315,6,1.0,48.128114,45.023531,12.0,21,1.0,2013,0.243205,B,B,5,1564,0,0,0,B,146950.912410,0,38.352374
3004,11624,46,1.0,42.983283,24.224435,10.7,15,16.0,1983,0.188784,B,B,31,6137,4,0,1,B,198450.736353,0,22.060771
3722,10546,62,1.0,46.013187,43.417043,11.5,4,17.0,2019,0.072158,B,B,2,629,1,0,0,A,113909.099428,0,22.893747
4401,673,27,1.0,54.418214,51.498581,13.6,10,17.0,2017,0.072158,B,B,2,629,1,0,0,A,133273.635012,0,23.475787
4990,15781,10,1.0,35.813564,19.953992,9.0,6,14.0,1971,0.282798,B,B,33,8667,2,0,6,B,164306.314182,0,19.796380
5697,13703,42,1.0,38.071692,19.723548,9.5,9,10.0,2006,0.158249,B,B,21,5731,0,1,0,B,160488.033165,0,21.634588
5879,6569,27,1.0,38.220258,18.716856,9.6,4,17.0,2018,0.011654,B,B,4,915,0,0,0,B,99079.960518,0,23.475787
7173,6708,48,1.0,42.069359,22.487739,10.5,1,10.0,2010,0.041125,B,B,46,9515,5,1,10,B,200021.835127,0,22.077389
7319,9690,27,1.0,40.081042,37.834964,10.0,18,19.0,2019,0.211401,B,B,9,1892,0,0,1,B,93218.650461,0,23.475787
7621,15466,88,1.0,42.357487,29.650241,10.6,10,19.0,2016,0.127376,B,B,43,8429,3,3,9,B,194525.103119,0,21.796485

In [133]:
ind_ks_25 = train.loc[(train['KitchenSquare'] > 25) & (train['Rooms'] == 2 ), :].index
train.loc[ind_ks_25, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
605,4265,161,2.0,53.216778,32.644859,53.0,7,17.0,1994,0.000699,B,B,14,3369,24,0,3,B,261125.669724,0,32.644859
3188,11739,27,2.0,61.070298,59.845092,58.0,8,17.0,2016,0.072158,B,B,2,629,1,0,0,A,212188.959537,0,36.626949
3449,12918,23,2.0,51.440463,36.008324,51.0,3,17.0,2017,0.005767,B,B,1,388,0,0,0,B,88150.012510,0,51.569732
4066,16593,52,2.0,64.859242,54.537501,62.0,15,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,185993.474671,0,54.537501
4966,12507,54,2.0,79.810535,79.578961,78.0,10,15.0,2014,0.006076,B,B,30,5285,0,6,6,B,438708.707579,0,28.312865
5095,300,31,2.0,106.427686,34.230415,32.0,4,40.0,2013,0.151346,B,A,32,5889,10,4,1,B,624549.354546,0,34.107772
5929,12666,34,2.0,60.603363,24.008321,58.0,14,22.0,1977,0.069753,B,B,53,13670,4,1,11,B,261733.472106,0,56.849348
6880,7162,34,2.0,56.738764,39.717135,54.0,26,25.0,2016,0.069753,B,B,53,13670,4,1,11,B,244220.621495,0,56.849348
7518,6508,23,2.0,67.146049,33.959154,63.0,5,17.0,2019,0.034656,B,B,0,168,0,0,0,B,193130.585871,0,51.569732

In [134]:
train.loc[(train['KitchenSquare'] > 25) & (train['Rooms'] == 2 ), 'KitchenSquare'] = round(train['Square'] / 4, 1)
train.loc[ind_ks_25, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
605,4265,161,2.0,53.216778,32.644859,13.3,7,17.0,1994,0.000699,B,B,14,3369,24,0,3,B,261125.669724,0,32.644859
3188,11739,27,2.0,61.070298,59.845092,15.3,8,17.0,2016,0.072158,B,B,2,629,1,0,0,A,212188.959537,0,36.626949
3449,12918,23,2.0,51.440463,36.008324,12.9,3,17.0,2017,0.005767,B,B,1,388,0,0,0,B,88150.012510,0,51.569732
4066,16593,52,2.0,64.859242,54.537501,16.2,15,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,185993.474671,0,54.537501
4966,12507,54,2.0,79.810535,79.578961,20.0,10,15.0,2014,0.006076,B,B,30,5285,0,6,6,B,438708.707579,0,28.312865
5095,300,31,2.0,106.427686,34.230415,26.6,4,40.0,2013,0.151346,B,A,32,5889,10,4,1,B,624549.354546,0,34.107772
5929,12666,34,2.0,60.603363,24.008321,15.2,14,22.0,1977,0.069753,B,B,53,13670,4,1,11,B,261733.472106,0,56.849348
6880,7162,34,2.0,56.738764,39.717135,14.2,26,25.0,2016,0.069753,B,B,53,13670,4,1,11,B,244220.621495,0,56.849348
7518,6508,23,2.0,67.146049,33.959154,16.8,5,17.0,2019,0.034656,B,B,0,168,0,0,0,B,193130.585871,0,51.569732

In [135]:
#

In [136]:
ind_ks_40 = train.loc[(train['KitchenSquare'] > 40) & (train['Rooms'] == 3 ), :].index
train.loc[ind_ks_40, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1472,3267,58,3.0,138.980817,138.004600,43.0,2,2.0,1977,0.437885,B,B,23,5735,3,0,5,B,169528.896664,0,59.387001
1524,16395,2,3.0,79.722243,44.731219,72.0,12,16.0,1987,0.130618,B,B,39,10418,9,1,9,B,370148.625285,0,45.695096
2729,12552,58,3.0,116.405693,113.109653,112.0,3,3.0,2016,0.437885,B,B,23,5735,3,0,5,B,296165.936689,0,59.387001
3923,12390,72,3.0,97.490674,68.243472,96.0,22,25.0,2019,0.210473,B,B,11,2398,2,3,0,B,445074.956552,0,71.057208
4223,7111,27,3.0,139.070296,89.787666,42.0,5,3.0,2016,0.014073,B,B,2,475,0,0,0,B,153946.777452,0,36.626949
5136,2737,27,3.0,123.430072,86.401050,123.0,5,10.0,2015,0.017647,B,B,2,469,0,0,0,B,234194.837047,0,51.041416
6866,7441,62,3.0,114.734473,112.589083,112.0,3,3.0,2015,0.072158,B,B,2,629,1,0,0,A,315245.521059,0,86.386228

In [137]:
train.loc[(train['KitchenSquare'] > 40) & (train['Rooms'] == 3 ), 'KitchenSquare'] = round(train['Square'] / 4, 1)
train.loc[ind_ks_40, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
1472,3267,58,3.0,138.980817,138.004600,34.7,2,2.0,1977,0.437885,B,B,23,5735,3,0,5,B,169528.896664,0,59.387001
1524,16395,2,3.0,79.722243,44.731219,19.9,12,16.0,1987,0.130618,B,B,39,10418,9,1,9,B,370148.625285,0,45.695096
2729,12552,58,3.0,116.405693,113.109653,29.1,3,3.0,2016,0.437885,B,B,23,5735,3,0,5,B,296165.936689,0,59.387001
3923,12390,72,3.0,97.490674,68.243472,24.4,22,25.0,2019,0.210473,B,B,11,2398,2,3,0,B,445074.956552,0,71.057208
4223,7111,27,3.0,139.070296,89.787666,34.8,5,3.0,2016,0.014073,B,B,2,475,0,0,0,B,153946.777452,0,36.626949
5136,2737,27,3.0,123.430072,86.401050,30.9,5,10.0,2015,0.017647,B,B,2,469,0,0,0,B,234194.837047,0,51.041416
6866,7441,62,3.0,114.734473,112.589083,28.7,3,3.0,2015,0.072158,B,B,2,629,1,0,0,A,315245.521059,0,86.386228

In [138]:
#plt.scatter(train['Rooms'], train['KitchenSquare']);

In [139]:
#

In [140]:
ind_ks_ls_s = train.loc[((train['KitchenSquare'] + train['LifeSquare']) >= train['Square']), :].index
train.loc[ind_ks_ls_s, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
45,4989,23,2.0,50.833326,50.751479,10.0,7,17.0,2018,0.034656,B,B,0,168,0,0,0,B,115339.701990,0,51.569732
47,12188,30,1.0,40.256191,40.240232,1.0,11,1.0,2016,0.000078,B,B,22,6398,141,3,23,B,123564.448837,0,40.240232
54,12085,1,1.0,44.283958,43.453315,1.0,7,22.0,1977,0.007122,B,B,1,264,0,0,1,B,146412.359305,0,39.990203
89,2031,66,2.0,74.418358,70.893915,9.0,15,17.0,2003,0.111627,B,B,50,12238,8,2,3,B,538574.775415,0,32.809245
100,8998,20,1.0,30.082090,24.250057,7.0,9,9.0,1976,0.019509,B,B,37,7687,11,5,5,B,186537.391208,0,23.124698
105,2271,27,1.0,43.292516,42.835643,10.8,12,11.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787
113,15953,1,1.0,40.040907,39.990203,1.0,12,17.0,1977,0.007122,B,B,1,264,0,0,1,B,162635.563746,0,39.990203
128,7243,9,2.0,58.089253,52.460857,8.0,5,22.0,1981,0.136244,B,B,11,2370,0,0,1,B,59877.592523,0,31.560580
130,14447,53,1.0,42.088880,38.616540,10.0,13,15.0,2017,0.049637,B,B,34,7759,0,1,3,B,195454.651452,0,22.044696
136,383,106,1.0,35.622216,33.552376,10.0,22,22.0,2005,0.246032,B,A,22,3151,4,3,3,B,187595.522709,0,27.147169
150,194,23,1.0,40.089322,30.381045,15.0,19,17.0,2019,0.034656,B,B,0,168,0,0,0,B,81258.057035,0,30.381045
156,1383,6,2.0,62.492460,58.981406,10.0,14,25.0,2018,0.243205,B,B,5,1564,0,0,0,B,177762.538836,0,37.873543
158,12307,60,1.0,40.064914,38.733288,8.0,13,14.0,1974,0.007659,B,B,35,7077,56,3,19,B,160810.546681,0,28.387647
161,13018,66,2.0,45.215152,44.218716,5.0,1,9.0,1968,0.111627,B,B,50,12238,8,2,3,B,190404.510114,0,32.809245
192,3114,9,2.0,55.328165,51.364581,8.0,6,14.0,1992,0.161532,B,B,25,5648,1,2,4,B,178602.154267,0,31.560580
226,7945,34,1.0,47.176086,38.416136,10.0,15,25.0,2015,0.069753,B,B,53,13670,4,1,11,B,210963.673120,0,23.201339
228,11374,46,1.0,36.007450,29.234932,9.0,7,17.0,2008,0.000000,B,B,47,11319,0,3,5,B,218409.263545,0,22.060771
233,8924,1,1.0,39.949017,39.921643,1.0,3,17.0,1977,0.007122,B,B,1,264,0,0,1,B,150053.085463,0,39.990203
258,14553,6,2.0,67.972296,64.712021,10.0,15,17.0,2018,0.243205,B,B,5,1564,0,0,0,B,189382.650276,0,37.873543
260,4451,1,3.0,79.953687,79.707512,1.0,12,17.0,1977,0.007122,B,B,1,264,0,0,1,B,241324.507250,0,79.707512
300,13979,34,3.0,89.125965,88.934494,12.0,8,17.0,1999,0.069753,B,B,53,13670,4,1,11,B,398098.546863,0,77.036246
307,8051,6,2.0,65.779137,64.797240,1.0,16,17.0,2015,0.243205,B,B,5,1564,0,0,0,B,187072.563233,0,37.873543
309,8552,48,3.0,95.210109,95.038236,1.0,18,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,477900.371154,0,48.669093
329,12206,6,1.0,42.637682,38.352374,10.0,13,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,130953.109096,0,38.352374
343,10315,27,1.0,42.431843,40.957925,10.0,2,12.0,2015,0.017647,B,B,2,469,0,0,0,B,126626.328643,0,23.475787
406,12373,27,1.0,47.025803,46.611669,10.0,10,10.0,2016,0.072158,B,B,2,629,1,0,0,A,163231.817827,0,23.475787
431,11389,27,1.0,41.368234,40.974750,10.0,6,12.0,2015,0.011654,B,B,4,915,0,0,0,B,113622.430624,0,23.475787
434,2182,27,2.0,74.642233,74.164321,1.0,7,9.0,2017,0.072158,B,B,2,629,1,0,0,A,166353.734353,0,36.626949
553,11966,27,1.0,47.042957,45.660065,6.0,10,17.0,2017,0.017647,B,B,2,469,0,0,0,B,146146.401691,0,23.475787
576,16575,27,1.0,32.712359,22.095210,13.0,8,25.0,2016,0.072158,B,B,2,629,1,0,0,A,94433.038958,0,23.475787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,7692,88,1.0,44.998499,43.817250,10.0,12,17.0,2016,0.127376,B,B,43,8429,3,3,9,B,214178.862397,0,21.796485
7351,15513,27,1.0,47.439867,47.204497,1.0,10,22.0,2015,0.211401,B,B,9,1892,0,0,1,B,117344.434056,0,23.475787
7362,8824,27,2.0,62.451190,53.618269,14.0,7,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,152956.829998,0,23.475787
7443,2101,63,1.0,50.154873,48.215731,10.0,14,17.0,2018,0.238617,B,B,26,3889,6,3,6,B,280202.201533,0,23.677259
7446,5411,6,2.0,63.027480,62.886644,10.0,18,17.0,2016,0.243205,B,B,5,1564,0,0,0,B,163606.107890,0,37.873543
7475,9968,18,3.0,77.674812,74.783868,10.0,4,17.0,1998,0.000000,B,B,30,5562,0,0,5,A,141462.056617,0,47.652879
7476,10480,52,2.0,64.207293,64.029024,1.0,7,17.0,2014,0.371149,B,B,34,7065,1,2,5,B,163579.130631,0,54.537501
7483,6102,30,2.0,59.616690,59.226500,1.0,6,12.0,2014,0.000078,B,B,22,6398,141,3,23,B,131361.635453,0,59.226500
7550,15428,58,2.0,69.304601,65.858689,10.0,6,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,154478.309071,0,33.143949
7568,2793,23,3.0,73.630355,70.716665,10.0,3,17.0,2018,0.005767,B,B,1,388,0,0,0,B,109873.366020,0,65.146215
7589,14829,30,1.0,46.326966,40.240232,10.0,10,20.0,1977,0.000078,B,B,22,6398,141,3,23,B,209756.373938,0,40.240232
7606,9926,149,1.0,42.821584,41.002360,8.0,10,10.0,2002,0.041116,B,B,53,14892,4,1,4,B,161577.299862,0,31.135748
7618,9784,100,1.0,35.895583,29.418422,10.0,7,11.0,1977,0.200147,B,B,23,3975,8,2,0,B,146060.096904,0,20.432361
7638,1575,23,1.0,33.555591,33.330277,1.0,5,9.0,2014,0.034656,B,B,0,168,0,0,0,B,61670.348212,0,30.381045
7662,13498,23,1.0,31.434944,31.121836,1.0,11,1.0,1977,0.034656,B,B,0,168,0,0,0,B,65033.895299,0,30.381045
7673,10070,27,3.0,103.683549,102.886556,1.0,9,1.0,2018,0.072158,B,B,2,629,1,0,0,A,227866.350490,0,51.041416
7689,251,27,1.0,52.296770,45.148885,9.0,3,12.0,2019,0.072158,B,B,2,629,1,0,0,A,140129.283318,0,23.475787
7703,11960,34,1.0,38.232839,35.143077,10.0,19,0.0,1977,0.069753,B,B,53,13670,4,1,11,B,190443.723654,0,23.201339
7706,2381,23,1.0,30.611500,30.381045,1.0,12,12.0,1977,0.034656,B,B,0,168,0,0,0,B,66927.004124,0,30.381045
7732,8645,34,3.0,89.118209,85.724112,10.0,17,25.0,2018,0.069753,B,B,53,13670,4,1,11,B,326553.576819,0,77.036246
7751,8959,27,1.0,44.602693,44.108220,1.0,2,2.0,2014,0.014058,B,B,1,290,0,0,0,B,86829.404676,0,23.475787
7819,11594,9,2.0,59.953348,56.803789,8.0,14,22.0,1977,0.136244,B,B,11,2370,0,0,1,B,189407.427829,0,31.560580
7868,16578,113,3.0,103.196375,84.122714,20.0,5,25.0,2017,0.050756,B,B,24,5469,1,0,1,B,366400.936549,0,22.426004
7874,3347,74,1.0,47.635827,47.416146,10.0,3,17.0,2017,0.075779,B,B,6,1437,3,0,2,B,166129.838794,0,27.504436
7883,4948,34,2.0,61.363205,56.849348,9.0,23,25.0,2018,0.069753,B,B,53,13670,4,1,11,B,277013.351570,0,56.849348
7887,14950,78,1.0,39.983708,39.660886,9.0,6,12.0,1967,0.092291,B,B,21,4346,2,1,2,B,161087.979229,0,22.043274
7915,1953,1,2.0,63.043237,53.997766,10.0,18,17.0,2016,0.007122,B,B,1,264,0,0,1,B,168828.232009,0,53.997766
7968,10176,1,3.0,75.081772,74.716290,1.0,13,17.0,2015,0.007122,B,B,1,264,0,0,1,B,211523.600587,0,79.707512
7985,3134,27,2.0,62.245962,62.184284,10.0,5,5.0,2016,0.072158,B,B,2,629,1,0,0,A,197796.499229,0,36.626949
7990,10278,23,1.0,43.880576,42.972991,1.0,12,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,139897.079874,0,30.381045

In [141]:
train.loc[((train['KitchenSquare'] + train['LifeSquare']) >= train['Square']), 'LifeSquare'] = (train['Square'] * 0.9 - train['KitchenSquare'])
train.loc[ind_ks_ls_s, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
45,4989,23,2.0,50.833326,35.749994,10.0,7,17.0,2018,0.034656,B,B,0,168,0,0,0,B,115339.701990,0,51.569732
47,12188,30,1.0,40.256191,35.230572,1.0,11,1.0,2016,0.000078,B,B,22,6398,141,3,23,B,123564.448837,0,40.240232
54,12085,1,1.0,44.283958,38.855562,1.0,7,22.0,1977,0.007122,B,B,1,264,0,0,1,B,146412.359305,0,39.990203
89,2031,66,2.0,74.418358,57.976522,9.0,15,17.0,2003,0.111627,B,B,50,12238,8,2,3,B,538574.775415,0,32.809245
100,8998,20,1.0,30.082090,20.073881,7.0,9,9.0,1976,0.019509,B,B,37,7687,11,5,5,B,186537.391208,0,23.124698
105,2271,27,1.0,43.292516,28.163264,10.8,12,11.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787
113,15953,1,1.0,40.040907,35.036816,1.0,12,17.0,1977,0.007122,B,B,1,264,0,0,1,B,162635.563746,0,39.990203
128,7243,9,2.0,58.089253,44.280328,8.0,5,22.0,1981,0.136244,B,B,11,2370,0,0,1,B,59877.592523,0,31.560580
130,14447,53,1.0,42.088880,27.879992,10.0,13,15.0,2017,0.049637,B,B,34,7759,0,1,3,B,195454.651452,0,22.044696
136,383,106,1.0,35.622216,22.059994,10.0,22,22.0,2005,0.246032,B,A,22,3151,4,3,3,B,187595.522709,0,27.147169
150,194,23,1.0,40.089322,21.080390,15.0,19,17.0,2019,0.034656,B,B,0,168,0,0,0,B,81258.057035,0,30.381045
156,1383,6,2.0,62.492460,46.243214,10.0,14,25.0,2018,0.243205,B,B,5,1564,0,0,0,B,177762.538836,0,37.873543
158,12307,60,1.0,40.064914,28.058423,8.0,13,14.0,1974,0.007659,B,B,35,7077,56,3,19,B,160810.546681,0,28.387647
161,13018,66,2.0,45.215152,35.693637,5.0,1,9.0,1968,0.111627,B,B,50,12238,8,2,3,B,190404.510114,0,32.809245
192,3114,9,2.0,55.328165,41.795348,8.0,6,14.0,1992,0.161532,B,B,25,5648,1,2,4,B,178602.154267,0,31.560580
226,7945,34,1.0,47.176086,32.458477,10.0,15,25.0,2015,0.069753,B,B,53,13670,4,1,11,B,210963.673120,0,23.201339
228,11374,46,1.0,36.007450,23.406705,9.0,7,17.0,2008,0.000000,B,B,47,11319,0,3,5,B,218409.263545,0,22.060771
233,8924,1,1.0,39.949017,34.954115,1.0,3,17.0,1977,0.007122,B,B,1,264,0,0,1,B,150053.085463,0,39.990203
258,14553,6,2.0,67.972296,51.175066,10.0,15,17.0,2018,0.243205,B,B,5,1564,0,0,0,B,189382.650276,0,37.873543
260,4451,1,3.0,79.953687,70.958318,1.0,12,17.0,1977,0.007122,B,B,1,264,0,0,1,B,241324.507250,0,79.707512
300,13979,34,3.0,89.125965,68.213368,12.0,8,17.0,1999,0.069753,B,B,53,13670,4,1,11,B,398098.546863,0,77.036246
307,8051,6,2.0,65.779137,58.201223,1.0,16,17.0,2015,0.243205,B,B,5,1564,0,0,0,B,187072.563233,0,37.873543
309,8552,48,3.0,95.210109,84.689099,1.0,18,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,477900.371154,0,48.669093
329,12206,6,1.0,42.637682,28.373914,10.0,13,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,130953.109096,0,38.352374
343,10315,27,1.0,42.431843,28.188659,10.0,2,12.0,2015,0.017647,B,B,2,469,0,0,0,B,126626.328643,0,23.475787
406,12373,27,1.0,47.025803,32.323223,10.0,10,10.0,2016,0.072158,B,B,2,629,1,0,0,A,163231.817827,0,23.475787
431,11389,27,1.0,41.368234,27.231411,10.0,6,12.0,2015,0.011654,B,B,4,915,0,0,0,B,113622.430624,0,23.475787
434,2182,27,2.0,74.642233,66.178010,1.0,7,9.0,2017,0.072158,B,B,2,629,1,0,0,A,166353.734353,0,36.626949
553,11966,27,1.0,47.042957,36.338661,6.0,10,17.0,2017,0.017647,B,B,2,469,0,0,0,B,146146.401691,0,23.475787
576,16575,27,1.0,32.712359,16.441123,13.0,8,25.0,2016,0.072158,B,B,2,629,1,0,0,A,94433.038958,0,23.475787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,7692,88,1.0,44.998499,30.498649,10.0,12,17.0,2016,0.127376,B,B,43,8429,3,3,9,B,214178.862397,0,21.796485
7351,15513,27,1.0,47.439867,41.695880,1.0,10,22.0,2015,0.211401,B,B,9,1892,0,0,1,B,117344.434056,0,23.475787
7362,8824,27,2.0,62.451190,42.206071,14.0,7,6.0,1977,0.075424,B,B,11,3097,0,0,0,B,152956.829998,0,23.475787
7443,2101,63,1.0,50.154873,35.139386,10.0,14,17.0,2018,0.238617,B,B,26,3889,6,3,6,B,280202.201533,0,23.677259
7446,5411,6,2.0,63.027480,46.724732,10.0,18,17.0,2016,0.243205,B,B,5,1564,0,0,0,B,163606.107890,0,37.873543
7475,9968,18,3.0,77.674812,59.907331,10.0,4,17.0,1998,0.000000,B,B,30,5562,0,0,5,A,141462.056617,0,47.652879
7476,10480,52,2.0,64.207293,56.786563,1.0,7,17.0,2014,0.371149,B,B,34,7065,1,2,5,B,163579.130631,0,54.537501
7483,6102,30,2.0,59.616690,52.655021,1.0,6,12.0,2014,0.000078,B,B,22,6398,141,3,23,B,131361.635453,0,59.226500
7550,15428,58,2.0,69.304601,52.374141,10.0,6,17.0,1977,0.437885,B,B,23,5735,3,0,5,B,154478.309071,0,33.143949
7568,2793,23,3.0,73.630355,56.267319,10.0,3,17.0,2018,0.005767,B,B,1,388,0,0,0,B,109873.366020,0,65.146215
7589,14829,30,1.0,46.326966,31.694269,10.0,10,20.0,1977,0.000078,B,B,22,6398,141,3,23,B,209756.373938,0,40.240232
7606,9926,149,1.0,42.821584,30.539426,8.0,10,10.0,2002,0.041116,B,B,53,14892,4,1,4,B,161577.299862,0,31.135748
7618,9784,100,1.0,35.895583,22.306025,10.0,7,11.0,1977,0.200147,B,B,23,3975,8,2,0,B,146060.096904,0,20.432361
7638,1575,23,1.0,33.555591,29.200032,1.0,5,9.0,2014,0.034656,B,B,0,168,0,0,0,B,61670.348212,0,30.381045
7662,13498,23,1.0,31.434944,27.291449,1.0,11,1.0,1977,0.034656,B,B,0,168,0,0,0,B,65033.895299,0,30.381045
7673,10070,27,3.0,103.683549,92.315194,1.0,9,1.0,2018,0.072158,B,B,2,629,1,0,0,A,227866.350490,0,51.041416
7689,251,27,1.0,52.296770,38.067093,9.0,3,12.0,2019,0.072158,B,B,2,629,1,0,0,A,140129.283318,0,23.475787
7703,11960,34,1.0,38.232839,24.409555,10.0,19,0.0,1977,0.069753,B,B,53,13670,4,1,11,B,190443.723654,0,23.201339
7706,2381,23,1.0,30.611500,26.550350,1.0,12,12.0,1977,0.034656,B,B,0,168,0,0,0,B,66927.004124,0,30.381045
7732,8645,34,3.0,89.118209,70.206388,10.0,17,25.0,2018,0.069753,B,B,53,13670,4,1,11,B,326553.576819,0,77.036246
7751,8959,27,1.0,44.602693,39.142424,1.0,2,2.0,2014,0.014058,B,B,1,290,0,0,0,B,86829.404676,0,23.475787
7819,11594,9,2.0,59.953348,45.958013,8.0,14,22.0,1977,0.136244,B,B,11,2370,0,0,1,B,189407.427829,0,31.560580
7868,16578,113,3.0,103.196375,72.876737,20.0,5,25.0,2017,0.050756,B,B,24,5469,1,0,1,B,366400.936549,0,22.426004
7874,3347,74,1.0,47.635827,32.872244,10.0,3,17.0,2017,0.075779,B,B,6,1437,3,0,2,B,166129.838794,0,27.504436
7883,4948,34,2.0,61.363205,46.226884,9.0,23,25.0,2018,0.069753,B,B,53,13670,4,1,11,B,277013.351570,0,56.849348
7887,14950,78,1.0,39.983708,26.985337,9.0,6,12.0,1967,0.092291,B,B,21,4346,2,1,2,B,161087.979229,0,22.043274
7915,1953,1,2.0,63.043237,46.738914,10.0,18,17.0,2016,0.007122,B,B,1,264,0,0,1,B,168828.232009,0,53.997766
7968,10176,1,3.0,75.081772,66.573594,1.0,13,17.0,2015,0.007122,B,B,1,264,0,0,1,B,211523.600587,0,79.707512
7985,3134,27,2.0,62.245962,46.021366,10.0,5,5.0,2016,0.072158,B,B,2,629,1,0,0,A,197796.499229,0,36.626949
7990,10278,23,1.0,43.880576,38.492518,1.0,12,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,139897.079874,0,30.381045

In [142]:
#

In [143]:
ind_ks_r_1 = train.loc[(train['KitchenSquare'] <= 1) & (train['Rooms'] == 1), :].index
train.loc[ind_ks_r_1, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare
4,358,1,1.0,42.670840,39.990203,1.0,8,17.0,1977,0.007122,B,B,1,264,0,0,1,B,125834.270291,0,39.990203
6,6076,27,1.0,48.599513,23.475787,1.0,8,1.0,1977,0.072158,B,B,2,629,1,0,0,A,159768.113188,0,23.475787
7,12584,23,1.0,41.515204,30.381045,1.0,12,25.0,1977,0.075779,B,B,6,1437,3,0,2,B,118200.065926,0,30.381045
8,4144,23,1.0,42.705836,30.381045,0.0,5,4.0,1977,0.034656,B,B,0,168,0,0,0,B,92290.968476,0,30.381045
17,6793,27,1.0,43.108815,23.475787,1.0,11,17.0,1977,0.211401,B,B,9,1892,0,0,1,B,99530.021887,0,23.475787
27,13430,27,1.0,47.191767,23.475787,1.0,6,17.0,1977,0.072158,B,B,2,629,1,0,0,A,145057.208975,0,23.475787
30,2997,1,1.0,41.176905,39.990203,1.0,14,17.0,1977,0.007122,B,B,1,264,0,0,1,B,135612.754405,0,39.990203
31,8741,23,1.0,41.222507,30.381045,1.0,12,20.0,1977,0.034656,B,B,0,168,0,0,0,B,95913.659963,0,30.381045
47,12188,30,1.0,40.256191,35.230572,1.0,11,1.0,2016,0.000078,B,B,22,6398,141,3,23,B,123564.448837,0,40.240232
54,12085,1,1.0,44.283958,38.855562,1.0,7,22.0,1977,0.007122,B,B,1,264,0,0,1,B,146412.359305,0,39.990203
60,7528,30,1.0,42.327960,40.853732,1.0,4,4.0,2014,0.000078,B,B,22,6398,141,3,23,B,73487.116852,0,40.240232
65,489,58,1.0,53.327195,22.588815,1.0,4,9.0,1977,0.437885,B,B,23,5735,3,0,5,B,112075.045202,0,22.588815
66,4672,27,1.0,51.684045,23.475787,1.0,14,13.0,1977,0.072158,B,B,2,629,1,0,0,A,129773.347048,0,23.475787
69,15385,23,1.0,27.911197,27.603121,0.0,3,6.0,2017,0.034656,B,B,0,168,0,0,0,B,65608.074129,0,30.381045
78,10287,6,1.0,38.344873,26.841411,1.0,10,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,122254.105486,0,38.352374
84,1971,1,1.0,41.995577,29.396904,1.0,12,20.0,1977,0.007122,B,B,1,264,0,0,1,B,150371.070429,0,39.990203
95,12925,1,1.0,47.534668,39.990203,1.0,5,3.0,1977,0.007122,B,B,1,264,0,0,1,B,142843.988109,0,39.990203
99,5606,6,1.0,41.784525,38.352374,0.0,5,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,120519.551910,0,38.352374
113,15953,1,1.0,40.040907,35.036816,1.0,12,17.0,1977,0.007122,B,B,1,264,0,0,1,B,162635.563746,0,39.990203
114,3795,27,1.0,41.267487,23.475787,0.0,4,10.0,1977,0.011654,B,B,4,915,0,0,0,B,110177.006490,0,23.475787
121,9099,27,1.0,41.038511,39.346335,1.0,3,12.0,2015,0.011654,B,B,4,915,0,0,0,B,112949.680809,0,23.475787
123,13180,27,1.0,42.580785,23.475787,1.0,2,17.0,1977,0.011654,B,B,4,915,0,0,0,B,105571.922693,0,23.475787
126,2597,169,1.0,43.257138,24.408929,0.0,5,0.0,1977,0.178917,B,B,18,3594,4,1,5,B,226053.135229,0,24.408929
127,11974,52,1.0,40.190905,23.548368,1.0,4,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,130155.254776,0,23.548368
129,16348,23,1.0,42.237012,30.381045,1.0,19,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,111124.741258,0,30.381045
138,13568,52,1.0,39.925541,23.548368,1.0,15,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,133131.015846,0,23.548368
163,14228,23,1.0,43.025196,30.381045,1.0,9,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,112597.867569,0,30.381045
167,6789,25,1.0,32.738888,24.711895,0.0,16,20.0,2016,0.069753,B,B,53,13670,4,1,11,B,146105.918171,0,24.711895
172,6549,6,1.0,44.553960,38.352374,0.0,3,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,124458.195810,0,38.352374
179,328,45,1.0,42.713308,21.693643,0.0,5,0.0,1977,0.195781,B,B,23,5212,6,3,2,B,282454.657354,0,21.693643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7765,2592,23,1.0,43.624731,30.381045,1.0,10,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,106323.014183,0,30.381045
7766,8256,58,1.0,41.806066,40.202217,1.0,1,4.0,2015,0.437885,B,B,23,5735,3,0,5,B,94194.141120,0,22.588815
7771,3277,6,1.0,40.565764,38.352374,1.0,5,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,140399.697252,0,38.352374
7773,7794,22,1.0,40.615693,19.131630,1.0,5,17.0,1977,0.118537,B,B,30,6207,1,1,0,B,140393.887533,0,19.131630
7784,13537,6,1.0,38.874335,27.212035,1.0,5,17.0,2014,0.243205,B,B,5,1564,0,0,0,B,128043.355789,0,38.352374
7785,8326,27,1.0,36.451567,23.475787,0.0,16,25.0,1977,0.072158,B,B,2,629,1,0,0,A,111215.557261,0,23.475787
7788,9528,27,1.0,45.751789,23.475787,1.0,5,1.0,1977,0.072158,B,B,2,629,1,0,0,A,116149.290815,0,23.475787
7794,13146,74,1.0,46.449711,27.504436,0.0,6,0.0,1977,0.075779,B,B,6,1437,3,0,2,B,168705.450148,0,27.504436
7797,12484,30,1.0,47.556592,44.409813,1.0,6,22.0,1977,0.000078,B,B,22,6398,141,3,23,B,170347.706212,0,40.240232
7811,937,1,1.0,59.694581,39.990203,1.0,15,17.0,1977,0.007122,B,B,1,264,0,0,1,B,164805.710733,0,39.990203
7829,562,1,1.0,50.865456,39.990203,0.0,7,0.0,1977,0.007122,B,B,1,264,0,0,1,B,173432.291297,0,39.990203
7847,6003,1,1.0,41.703247,39.990203,1.0,8,17.0,1977,0.007122,B,B,1,264,0,0,1,B,166481.350886,0,39.990203
7854,8268,23,1.0,41.069085,30.381045,0.0,9,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,117416.295033,0,30.381045
7871,2277,52,1.0,38.555389,26.988772,0.0,14,17.0,1977,0.371149,B,B,34,7065,1,2,5,B,113277.591887,0,23.548368
7876,8715,25,1.0,32.797538,22.958277,1.0,15,13.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895
7877,14974,22,1.0,38.520283,19.131630,1.0,19,20.0,1977,0.118537,B,B,30,6207,1,1,0,B,137778.662626,0,19.131630
7881,14282,23,1.0,40.257605,30.381045,1.0,4,12.0,1977,0.034656,B,B,0,168,0,0,0,B,96769.330478,0,30.381045
7886,15167,27,1.0,46.655792,23.475787,1.0,15,1.0,1977,0.072158,B,B,2,629,1,0,0,A,143327.711053,0,23.475787
7890,1182,27,1.0,38.936986,30.643197,0.0,18,19.0,2017,0.211401,B,B,9,1892,0,0,1,B,93560.789553,0,23.475787
7893,1308,62,1.0,44.008402,22.893747,1.0,3,12.0,2017,0.072158,B,B,2,629,1,0,0,A,124349.824728,0,22.893747
7924,16562,6,1.0,49.073548,38.352374,1.0,14,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,155518.223364,0,38.352374
7925,11647,9,1.0,44.131409,22.079346,1.0,14,18.0,1977,0.161532,B,B,25,5648,1,2,4,B,138202.240827,0,22.079346
7926,5544,0,1.0,52.653623,21.335474,1.0,5,15.0,2016,0.006076,B,B,30,5285,0,6,6,B,188810.508549,0,21.335474
7936,4263,27,1.0,54.255191,51.135219,0.0,5,3.0,2017,0.072158,B,B,2,629,1,0,0,A,147040.226120,0,23.475787
7937,2124,62,1.0,45.592499,22.893747,0.0,12,0.0,1977,0.072158,B,B,2,629,1,0,0,A,123553.869052,0,22.893747
7951,3662,23,1.0,36.232303,30.381045,1.0,4,15.0,1977,0.005767,B,B,1,388,0,0,0,B,65410.074769,0,30.381045
7953,8328,23,1.0,39.409501,30.381045,1.0,5,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,103396.866592,0,30.381045
7982,3902,23,1.0,27.442238,19.209567,1.0,4,4.0,1977,0.034656,B,B,0,168,0,0,0,B,65547.071846,0,30.381045
7988,5234,30,1.0,29.947691,20.963383,1.0,11,22.0,2018,0.000078,B,B,22,6398,141,3,23,B,99110.577389,0,40.240232
7990,10278,23,1.0,43.880576,38.492518,1.0,12,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,139897.079874,0,30.381045

In [144]:
train['KitchenSquare'].value_counts()

1.0     1988
8.0     1050
5.0      942
10.0     852
6.0      813
9.0      667
0.0      545
7.0      495
12.0     201
11.0     187
13.0      57
14.0      39
4.0       30
15.0      27
3.0       19
16.0      15
20.0      12
17.0      10
19.0       9
2.0        3
22.0       3
18.0       3
30.0       2
25.0       2
12.9       1
26.0       1
19.9       1
26.6       1
11.8       1
10.8       1
28.7       1
14.2       1
34.7       1
10.7       1
15.3       1
9.6        1
29.1       1
15.2       1
16.2       1
30.9       1
8.1        1
34.8       1
10.5       1
31.0       1
9.5        1
11.5       1
23.0       1
21.0       1
16.8       1
13.3       1
10.6       1
24.4       1
13.6       1
Name: KitchenSquare, dtype: int64

In [145]:
kitch_size = (train['KitchenSquare'].value_counts() > (train['KitchenSquare'].count() * 0.2)).astype(int).reset_index()
kitch_size.columns = ['KitchenSquare', 'Kitchen_1']
kitch_size

    KitchenSquare  Kitchen_1
0             1.0          1
1             8.0          0
2             5.0          0
3            10.0          0
4             6.0          0
5             9.0          0
6             0.0          0
7             7.0          0
8            12.0          0
9            11.0          0
10           13.0          0
11           14.0          0
12            4.0          0
13           15.0          0
14            3.0          0
15           16.0          0
16           20.0          0
17           17.0          0
18           19.0          0
19            2.0          0
20           22.0          0
21           18.0          0
22           30.0          0
23           25.0          0
24           12.9          0
25           26.0          0
26           19.9          0
27           26.6          0
28           11.8          0
29           10.8          0
30           28.7          0
31           14.2          0
32           34.7          0
33           10.7          0
34           15.3          0
35            9.6          0
36           29.1          0
37           15.2          0
38           16.2          0
39           30.9          0
40            8.1          0
41           34.8          0
42           10.5          0
43           31.0          0
44            9.5          0
45           11.5          0
46           23.0          0
47           21.0          0
48           16.8          0
49           13.3          0
50           10.6          0
51           24.4          0
52           13.6          0

In [146]:
def add_kitch_size(df, kitch_size):
    df = pd.merge(df, kitch_size, on='KitchenSquare', how='left')
    df['Kitchen_1'] = df['Kitchen_1'].fillna(0)
    return df

In [147]:
train = add_kitch_size(train, kitch_size)

In [148]:
def correct_kitchensquare(df):
    df = add_kitch_size(df, kitch_size)
    
    df.loc[df['KitchenSquare'] > 250, 'KitchenSquare'] = round(df['Square'] / 4, 1)
    df.loc[(df['KitchenSquare'] > 20) & (df['Rooms'] == 1 ), 'KitchenSquare'] = round(df['Square'] / 4, 1)
    df.loc[(df['KitchenSquare'] > 25) & (df['Rooms'] == 2 ), 'KitchenSquare'] = round(df['Square'] / 4, 1)
    df.loc[(df['KitchenSquare'] > 40) & (df['Rooms'] == 3 ), 'KitchenSquare'] = round(df['Square'] / 4, 1)
    df.loc[((df['KitchenSquare'] + df['LifeSquare']) >= df['Square']), 'LifeSquare'] = (df['Square'] * 0.9 - df['KitchenSquare'])
    return df

In [149]:
train['KitchenSquare'].describe()

count    8000.000000
mean        5.737462
std         4.031978
min         0.000000
25%         1.000000
50%         6.000000
75%         9.000000
max        34.800000
Name: KitchenSquare, dtype: float64

##### Floor, HouseFloor

In [150]:
train['Floor'].describe()

count    8000.000000
mean        8.492375
std         5.221240
min         1.000000
25%         4.000000
50%         7.000000
75%        12.000000
max        42.000000
Name: Floor, dtype: float64

In [151]:
train['HouseFloor'].describe()

count    8000.000000
mean       12.623250
std         6.812185
min         0.000000
25%         9.000000
50%        13.000000
75%        17.000000
max       117.000000
Name: HouseFloor, dtype: float64

In [152]:
train['Floor'].unique()

array([ 3,  5,  4,  8, 12, 26,  2, 17, 11, 16,  7, 13, 22,  6, 14, 18, 20,
       10,  9, 15, 23, 19,  1, 21, 24, 27, 25, 28, 32, 31, 42, 33],
      dtype=int64)

In [153]:
train['Floor'].value_counts()

4     764
5     712
3     694
6     667
7     607
8     519
9     493
2     464
10    439
11    368
12    343
13    296
14    291
15    234
16    224
17    197
1     185
18    150
19     98
20     51
21     45
22     44
24     42
25     29
23     18
26     13
27      5
28      3
32      2
31      1
42      1
33      1
Name: Floor, dtype: int64

In [154]:
train.loc[train['Floor'] == 42, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1
3339,1674,76,2.0,74.344672,41.044132,5.0,42,48.0,2016,0.0,B,B,7,1660,39,1,5,B,411691.504766,0,36.96033,0

In [155]:
#plt.scatter(train['Floor'], train['HouseFloor']);

In [156]:
ind_hf_80 = train.loc[train['HouseFloor'] > 80, :].index
train.loc[ind_hf_80, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1
1501,78,30,2.0,65.773749,46.041624,1.0,8,117.0,1977,0.000078,B,B,22,6398,141,3,23,B,207248.370520,0,59.226500,1
2149,10806,5,1.0,51.944587,48.709601,1.0,6,99.0,1977,0.150818,B,B,16,3433,4,4,5,B,296127.115515,0,20.307073,1
4201,9300,74,2.0,71.747869,50.223509,9.0,5,99.0,1977,0.075779,B,B,6,1437,3,0,2,B,243329.912579,0,66.440664,0

In [157]:
train['HouseFloor'].value_counts()

17.0     1869
9.0      1116
12.0      861
5.0       818
14.0      504
16.0      455
1.0       411
25.0      303
22.0      268
0.0       208
24.0      138
10.0      116
8.0       113
15.0      102
4.0       100
3.0        96
19.0       92
20.0       88
18.0       67
6.0        45
2.0        42
7.0        38
23.0       31
11.0       25
21.0       25
13.0       21
30.0       18
27.0        5
40.0        5
32.0        4
37.0        3
99.0        2
39.0        2
28.0        1
47.0        1
117.0       1
29.0        1
44.0        1
36.0        1
31.0        1
48.0        1
45.0        1
Name: HouseFloor, dtype: int64

In [158]:
train.loc[((train['HouseFloor'] > 80) & ((train['Floor'] >= 17) | (train['Floor'] == None))), 'HouseFloor'] = 17
train.loc[(train['HouseFloor'] > 80) & (train['Floor'] < 17), 'HouseFloor'] = 9
train.loc[ind_hf_80, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1
1501,78,30,2.0,65.773749,46.041624,1.0,8,9.0,1977,0.000078,B,B,22,6398,141,3,23,B,207248.370520,0,59.226500,1
2149,10806,5,1.0,51.944587,48.709601,1.0,6,9.0,1977,0.150818,B,B,16,3433,4,4,5,B,296127.115515,0,20.307073,1
4201,9300,74,2.0,71.747869,50.223509,9.0,5,9.0,1977,0.075779,B,B,6,1437,3,0,2,B,243329.912579,0,66.440664,0

In [159]:
#plt.scatter(train['Floor'], train['HouseFloor']);

In [160]:
ind_hf_f_0 = train.loc[(train['Floor'] > train['HouseFloor']) | (train['Floor'] == 0) | (train['HouseFloor'] == 0), :].index
train.loc[ind_hf_f_0, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1
0,12473,58,2.0,65.271225,62.798045,1.0,3,1.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849.693542,0,22.588815,1
6,6076,27,1.0,48.599513,23.475787,1.0,8,1.0,1977,0.072158,B,B,2,629,1,0,0,A,159768.113188,0,23.475787,1
8,4144,23,1.0,42.705836,30.381045,0.0,5,4.0,1977,0.034656,B,B,0,168,0,0,0,B,92290.968476,0,30.381045,0
9,15303,48,3.0,83.866174,48.669093,1.0,26,1.0,2014,0.041125,B,B,46,9515,5,1,10,B,468595.039049,0,48.669093,1
16,1273,45,2.0,63.193038,38.132453,1.0,17,1.0,1977,0.195781,B,B,23,5212,6,3,2,B,312636.073081,0,38.132453,1
20,15165,74,2.0,83.259565,53.872631,1.0,12,1.0,2017,0.309479,B,B,35,7715,4,0,6,B,260852.230977,0,66.440664,1
23,13670,22,2.0,87.485627,19.131630,0.0,16,0.0,1977,0.118537,B,B,30,6207,1,1,0,B,361744.269547,0,19.131630,0
35,8823,7,2.0,59.466919,33.746589,9.0,18,16.0,2016,0.130618,B,B,39,10418,9,1,9,B,71291.546163,0,30.930040,0
38,3327,145,1.0,41.093702,20.643619,8.0,18,17.0,1998,0.246032,B,A,22,3151,4,3,3,B,174921.829928,0,19.093353,0
41,13179,23,1.0,40.426157,22.346519,7.0,18,17.0,2013,0.075779,B,B,6,1437,3,0,2,B,78213.740129,0,30.381045,0
43,16181,53,2.0,59.174489,33.700061,1.0,7,2.0,2015,0.049637,B,B,34,7759,0,1,3,B,322147.208461,0,33.700061,1
46,9522,25,3.0,82.120767,50.389116,1.0,4,1.0,2016,0.069753,B,B,53,13670,4,1,11,B,300497.668744,0,50.389116,1
47,12188,30,1.0,40.256191,35.230572,1.0,11,1.0,2016,0.000078,B,B,22,6398,141,3,23,B,123564.448837,0,40.240232,1
49,2956,28,2.0,41.684727,24.442781,7.0,13,12.0,1966,0.000995,B,B,42,7651,1,1,5,B,198803.145985,0,31.051013,0
53,8068,21,3.0,77.818382,47.221007,10.0,18,17.0,1992,0.194489,B,B,47,8004,3,3,5,B,320187.329283,0,45.335184,0
55,14659,74,2.0,66.944203,46.860942,1.0,8,7.0,1977,0.075779,B,B,6,1437,3,0,2,B,212801.122972,0,66.440664,1
66,4672,27,1.0,51.684045,23.475787,1.0,14,13.0,1977,0.072158,B,B,2,629,1,0,0,A,129773.347048,0,23.475787,1
70,2913,34,4.0,94.888593,26.370948,1.0,4,1.0,2018,0.069753,B,B,53,13670,4,1,11,B,346949.506507,1,48.594111,1
73,15815,101,2.0,47.028645,32.990847,5.0,7,5.0,1964,0.225825,A,B,41,6558,7,3,2,B,190884.574514,0,30.048136,0
90,1064,53,3.0,82.676933,47.234145,0.0,5,0.0,1977,0.049637,B,B,34,7759,0,1,3,B,297390.680995,0,47.234145,0
92,14765,45,2.0,72.533825,38.132453,0.0,23,0.0,1977,0.195781,B,B,23,5212,6,3,2,B,443277.942760,0,38.132453,0
95,12925,1,1.0,47.534668,39.990203,1.0,5,3.0,1977,0.007122,B,B,1,264,0,0,1,B,142843.988109,0,39.990203,1
105,2271,27,1.0,43.292516,28.163264,10.8,12,11.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787,0
115,10191,6,2.0,63.659749,44.561824,7.0,18,17.0,1977,0.243205,B,B,5,1564,0,0,0,B,188319.662097,0,37.873543,0
126,2597,169,1.0,43.257138,24.408929,0.0,5,0.0,1977,0.178917,B,B,18,3594,4,1,5,B,226053.135229,0,24.408929,0
129,16348,23,1.0,42.237012,30.381045,1.0,19,17.0,1977,0.075779,B,B,6,1437,3,0,2,B,111124.741258,0,30.381045,1
139,15760,34,2.0,65.235395,43.620052,1.0,8,1.0,2014,0.069753,B,B,53,13670,4,1,11,B,336951.628930,0,56.849348,1
149,15603,41,3.0,73.146301,45.675067,8.0,14,12.0,1983,0.036122,B,B,24,4378,0,1,1,B,286282.443059,0,44.907505,0
150,194,23,1.0,40.089322,21.080390,15.0,19,17.0,2019,0.034656,B,B,0,168,0,0,0,B,81258.057035,0,30.381045,0
151,9488,27,2.0,59.398970,36.626949,0.0,6,0.0,1977,0.011654,B,B,4,915,0,0,0,B,145040.956302,0,36.626949,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7824,16286,79,3.0,94.233363,57.451591,8.0,6,5.0,1977,0.169091,B,B,19,3856,10,2,5,B,297382.794868,0,47.723057,0
7829,562,1,1.0,50.865456,39.990203,0.0,7,0.0,1977,0.007122,B,B,1,264,0,0,1,B,173432.291297,0,39.990203,0
7831,5826,23,1.0,55.282148,22.336038,20.0,4,3.0,2013,0.014073,B,B,2,475,0,0,0,B,157140.848998,0,30.381045,0
7832,10038,27,2.0,77.989448,36.626949,0.0,9,0.0,1977,0.072158,B,B,2,629,1,0,0,A,167936.053495,0,36.626949,0
7833,15031,48,3.0,96.678127,48.669093,1.0,19,1.0,2017,0.041125,B,B,46,9515,5,1,10,B,474638.812836,0,48.669093,1
7835,13517,30,2.0,55.597409,38.918187,1.0,15,1.0,2013,0.000078,B,B,22,6398,141,3,23,B,153836.505669,0,59.226500,1
7837,220,62,2.0,77.475090,36.861647,1.0,6,1.0,1977,0.072158,B,B,2,629,1,0,0,A,183373.242203,0,36.861647,1
7840,418,54,2.0,42.987519,24.179968,7.0,13,12.0,1969,0.006076,B,B,30,5285,0,6,6,B,184661.975101,0,28.312865,0
7841,8185,6,2.0,56.705295,37.873543,1.0,12,1.0,1977,0.243205,B,B,5,1564,0,0,0,B,178342.566861,0,37.873543,1
7842,14276,128,3.0,81.740944,51.205033,8.0,15,14.0,1993,0.000000,B,B,27,4798,0,2,8,B,313758.066593,0,47.837300,0
7848,8464,103,1.0,55.139386,24.422629,12.0,25,16.0,2008,0.151346,B,A,32,5889,10,4,1,B,425716.951985,0,21.253516,0
7850,396,54,3.0,110.119100,77.083370,1.0,8,1.0,2015,0.006076,B,B,30,5285,0,6,6,B,491296.245173,0,42.257742,1
7853,583,27,3.0,84.250710,41.878848,1.0,15,1.0,2016,0.072158,B,B,2,629,1,0,0,A,236647.781363,0,51.041416,1
7863,1994,27,2.0,62.738830,36.626949,1.0,8,1.0,1977,0.072158,B,B,2,629,1,0,0,A,198697.496760,0,36.626949,1
7870,10406,24,2.0,54.551991,31.364187,1.0,22,1.0,1977,0.111627,B,B,50,12238,8,2,3,B,322544.371625,0,31.364187,1
7875,8608,27,2.0,62.576404,36.626949,0.0,2,0.0,1977,0.011654,B,B,4,915,0,0,0,B,188644.907765,0,36.626949,0
7876,8715,25,1.0,32.797538,22.958277,1.0,15,13.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895,1
7886,15167,27,1.0,46.655792,23.475787,1.0,15,1.0,1977,0.072158,B,B,2,629,1,0,0,A,143327.711053,0,23.475787,1
7892,16002,167,2.0,37.612584,25.312739,7.0,11,6.0,1964,0.050272,B,B,21,4231,14,0,3,B,237314.708739,0,34.437358,0
7894,15661,45,3.0,81.094922,74.750894,0.0,15,0.0,1977,0.195781,B,B,23,5212,6,3,2,B,442472.456032,0,74.750894,0
7909,13994,9,2.0,66.965769,31.560580,1.0,3,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,185325.865350,0,31.560580,1
7915,1953,1,2.0,63.043237,46.738914,10.0,18,17.0,2016,0.007122,B,B,1,264,0,0,1,B,168828.232009,0,53.997766,0
7923,13665,62,2.0,57.717659,36.861647,0.0,10,0.0,1977,0.072158,B,B,2,629,1,0,0,A,176072.619971,0,36.861647,0
7936,4263,27,1.0,54.255191,51.135219,0.0,5,3.0,2017,0.072158,B,B,2,629,1,0,0,A,147040.226120,0,23.475787,0
7937,2124,62,1.0,45.592499,22.893747,0.0,12,0.0,1977,0.072158,B,B,2,629,1,0,0,A,123553.869052,0,22.893747,0
7960,1040,27,2.0,65.088892,36.626949,1.0,10,1.0,1977,0.072158,B,B,2,629,1,0,0,A,179525.641685,0,36.626949,1
7973,15891,27,3.0,82.630590,51.041416,0.0,11,0.0,1977,0.017647,B,B,2,469,0,0,0,B,221431.000082,0,51.041416,0
7974,12545,9,3.0,83.978425,45.664912,1.0,10,1.0,1977,0.161532,B,B,25,5648,1,2,4,B,219577.830422,0,45.664912,1
7989,1454,21,3.0,51.195460,36.951319,5.0,10,9.0,1974,0.194489,B,B,47,8004,3,3,5,B,213426.111753,0,45.335184,0
7995,10013,30,2.0,62.219340,43.553538,1.0,4,2.0,2015,0.000078,B,B,22,6398,141,3,23,B,150136.610509,0,59.226500,1

In [161]:
train.loc[train['HouseFloor'] == 0, 'HouseFloor'] = np.round(train.loc[train['HouseFloor'] != 0, 'HouseFloor'].mean())
train.loc[(train['Floor'] > train['HouseFloor']) | (train['Floor'] == 0) | (train['HouseFloor'] == 0), 'HouseFloor'] = train['Floor']
train.loc[ind_hf_f_0, :]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1
0,12473,58,2.0,65.271225,62.798045,1.0,3,3.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849.693542,0,22.588815,1
6,6076,27,1.0,48.599513,23.475787,1.0,8,8.0,1977,0.072158,B,B,2,629,1,0,0,A,159768.113188,0,23.475787,1
8,4144,23,1.0,42.705836,30.381045,0.0,5,5.0,1977,0.034656,B,B,0,168,0,0,0,B,92290.968476,0,30.381045,0
9,15303,48,3.0,83.866174,48.669093,1.0,26,26.0,2014,0.041125,B,B,46,9515,5,1,10,B,468595.039049,0,48.669093,1
16,1273,45,2.0,63.193038,38.132453,1.0,17,17.0,1977,0.195781,B,B,23,5212,6,3,2,B,312636.073081,0,38.132453,1
20,15165,74,2.0,83.259565,53.872631,1.0,12,12.0,2017,0.309479,B,B,35,7715,4,0,6,B,260852.230977,0,66.440664,1
23,13670,22,2.0,87.485627,19.131630,0.0,16,16.0,1977,0.118537,B,B,30,6207,1,1,0,B,361744.269547,0,19.131630,0
35,8823,7,2.0,59.466919,33.746589,9.0,18,18.0,2016,0.130618,B,B,39,10418,9,1,9,B,71291.546163,0,30.930040,0
38,3327,145,1.0,41.093702,20.643619,8.0,18,18.0,1998,0.246032,B,A,22,3151,4,3,3,B,174921.829928,0,19.093353,0
41,13179,23,1.0,40.426157,22.346519,7.0,18,18.0,2013,0.075779,B,B,6,1437,3,0,2,B,78213.740129,0,30.381045,0
43,16181,53,2.0,59.174489,33.700061,1.0,7,7.0,2015,0.049637,B,B,34,7759,0,1,3,B,322147.208461,0,33.700061,1
46,9522,25,3.0,82.120767,50.389116,1.0,4,4.0,2016,0.069753,B,B,53,13670,4,1,11,B,300497.668744,0,50.389116,1
47,12188,30,1.0,40.256191,35.230572,1.0,11,11.0,2016,0.000078,B,B,22,6398,141,3,23,B,123564.448837,0,40.240232,1
49,2956,28,2.0,41.684727,24.442781,7.0,13,13.0,1966,0.000995,B,B,42,7651,1,1,5,B,198803.145985,0,31.051013,0
53,8068,21,3.0,77.818382,47.221007,10.0,18,18.0,1992,0.194489,B,B,47,8004,3,3,5,B,320187.329283,0,45.335184,0
55,14659,74,2.0,66.944203,46.860942,1.0,8,8.0,1977,0.075779,B,B,6,1437,3,0,2,B,212801.122972,0,66.440664,1
66,4672,27,1.0,51.684045,23.475787,1.0,14,14.0,1977,0.072158,B,B,2,629,1,0,0,A,129773.347048,0,23.475787,1
70,2913,34,4.0,94.888593,26.370948,1.0,4,4.0,2018,0.069753,B,B,53,13670,4,1,11,B,346949.506507,1,48.594111,1
73,15815,101,2.0,47.028645,32.990847,5.0,7,7.0,1964,0.225825,A,B,41,6558,7,3,2,B,190884.574514,0,30.048136,0
90,1064,53,3.0,82.676933,47.234145,0.0,5,13.0,1977,0.049637,B,B,34,7759,0,1,3,B,297390.680995,0,47.234145,0
92,14765,45,2.0,72.533825,38.132453,0.0,23,23.0,1977,0.195781,B,B,23,5212,6,3,2,B,443277.942760,0,38.132453,0
95,12925,1,1.0,47.534668,39.990203,1.0,5,5.0,1977,0.007122,B,B,1,264,0,0,1,B,142843.988109,0,39.990203,1
105,2271,27,1.0,43.292516,28.163264,10.8,12,12.0,2015,0.211401,B,B,9,1892,0,0,1,B,117296.173704,0,23.475787,0
115,10191,6,2.0,63.659749,44.561824,7.0,18,18.0,1977,0.243205,B,B,5,1564,0,0,0,B,188319.662097,0,37.873543,0
126,2597,169,1.0,43.257138,24.408929,0.0,5,13.0,1977,0.178917,B,B,18,3594,4,1,5,B,226053.135229,0,24.408929,0
129,16348,23,1.0,42.237012,30.381045,1.0,19,19.0,1977,0.075779,B,B,6,1437,3,0,2,B,111124.741258,0,30.381045,1
139,15760,34,2.0,65.235395,43.620052,1.0,8,8.0,2014,0.069753,B,B,53,13670,4,1,11,B,336951.628930,0,56.849348,1
149,15603,41,3.0,73.146301,45.675067,8.0,14,14.0,1983,0.036122,B,B,24,4378,0,1,1,B,286282.443059,0,44.907505,0
150,194,23,1.0,40.089322,21.080390,15.0,19,19.0,2019,0.034656,B,B,0,168,0,0,0,B,81258.057035,0,30.381045,0
151,9488,27,2.0,59.398970,36.626949,0.0,6,13.0,1977,0.011654,B,B,4,915,0,0,0,B,145040.956302,0,36.626949,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7824,16286,79,3.0,94.233363,57.451591,8.0,6,6.0,1977,0.169091,B,B,19,3856,10,2,5,B,297382.794868,0,47.723057,0
7829,562,1,1.0,50.865456,39.990203,0.0,7,13.0,1977,0.007122,B,B,1,264,0,0,1,B,173432.291297,0,39.990203,0
7831,5826,23,1.0,55.282148,22.336038,20.0,4,4.0,2013,0.014073,B,B,2,475,0,0,0,B,157140.848998,0,30.381045,0
7832,10038,27,2.0,77.989448,36.626949,0.0,9,13.0,1977,0.072158,B,B,2,629,1,0,0,A,167936.053495,0,36.626949,0
7833,15031,48,3.0,96.678127,48.669093,1.0,19,19.0,2017,0.041125,B,B,46,9515,5,1,10,B,474638.812836,0,48.669093,1
7835,13517,30,2.0,55.597409,38.918187,1.0,15,15.0,2013,0.000078,B,B,22,6398,141,3,23,B,153836.505669,0,59.226500,1
7837,220,62,2.0,77.475090,36.861647,1.0,6,6.0,1977,0.072158,B,B,2,629,1,0,0,A,183373.242203,0,36.861647,1
7840,418,54,2.0,42.987519,24.179968,7.0,13,13.0,1969,0.006076,B,B,30,5285,0,6,6,B,184661.975101,0,28.312865,0
7841,8185,6,2.0,56.705295,37.873543,1.0,12,12.0,1977,0.243205,B,B,5,1564,0,0,0,B,178342.566861,0,37.873543,1
7842,14276,128,3.0,81.740944,51.205033,8.0,15,15.0,1993,0.000000,B,B,27,4798,0,2,8,B,313758.066593,0,47.837300,0
7848,8464,103,1.0,55.139386,24.422629,12.0,25,25.0,2008,0.151346,B,A,32,5889,10,4,1,B,425716.951985,0,21.253516,0
7850,396,54,3.0,110.119100,77.083370,1.0,8,8.0,2015,0.006076,B,B,30,5285,0,6,6,B,491296.245173,0,42.257742,1
7853,583,27,3.0,84.250710,41.878848,1.0,15,15.0,2016,0.072158,B,B,2,629,1,0,0,A,236647.781363,0,51.041416,1
7863,1994,27,2.0,62.738830,36.626949,1.0,8,8.0,1977,0.072158,B,B,2,629,1,0,0,A,198697.496760,0,36.626949,1
7870,10406,24,2.0,54.551991,31.364187,1.0,22,22.0,1977,0.111627,B,B,50,12238,8,2,3,B,322544.371625,0,31.364187,1
7875,8608,27,2.0,62.576404,36.626949,0.0,2,13.0,1977,0.011654,B,B,4,915,0,0,0,B,188644.907765,0,36.626949,0
7876,8715,25,1.0,32.797538,22.958277,1.0,15,15.0,1977,0.069753,B,B,53,13670,4,1,11,B,145780.190092,0,24.711895,1
7886,15167,27,1.0,46.655792,23.475787,1.0,15,15.0,1977,0.072158,B,B,2,629,1,0,0,A,143327.711053,0,23.475787,1
7892,16002,167,2.0,37.612584,25.312739,7.0,11,11.0,1964,0.050272,B,B,21,4231,14,0,3,B,237314.708739,0,34.437358,0
7894,15661,45,3.0,81.094922,74.750894,0.0,15,15.0,1977,0.195781,B,B,23,5212,6,3,2,B,442472.456032,0,74.750894,0
7909,13994,9,2.0,66.965769,31.560580,1.0,3,3.0,1977,0.161532,B,B,25,5648,1,2,4,B,185325.865350,0,31.560580,1
7915,1953,1,2.0,63.043237,46.738914,10.0,18,18.0,2016,0.007122,B,B,1,264,0,0,1,B,168828.232009,0,53.997766,0
7923,13665,62,2.0,57.717659,36.861647,0.0,10,13.0,1977,0.072158,B,B,2,629,1,0,0,A,176072.619971,0,36.861647,0
7936,4263,27,1.0,54.255191,51.135219,0.0,5,5.0,2017,0.072158,B,B,2,629,1,0,0,A,147040.226120,0,23.475787,0
7937,2124,62,1.0,45.592499,22.893747,0.0,12,13.0,1977,0.072158,B,B,2,629,1,0,0,A,123553.869052,0,22.893747,0
7960,1040,27,2.0,65.088892,36.626949,1.0,10,10.0,1977,0.072158,B,B,2,629,1,0,0,A,179525.641685,0,36.626949,1
7973,15891,27,3.0,82.630590,51.041416,0.0,11,13.0,1977,0.017647,B,B,2,469,0,0,0,B,221431.000082,0,51.041416,0
7974,12545,9,3.0,83.978425,45.664912,1.0,10,10.0,1977,0.161532,B,B,25,5648,1,2,4,B,219577.830422,0,45.664912,1
7989,1454,21,3.0,51.195460,36.951319,5.0,10,10.0,1974,0.194489,B,B,47,8004,3,3,5,B,213426.111753,0,45.335184,0
7995,10013,30,2.0,62.219340,43.553538,1.0,4,4.0,2015,0.000078,B,B,22,6398,141,3,23,B,150136.610509,0,59.226500,1

In [162]:
#

In [163]:
#plt.scatter(train['Floor'], train['HouseFloor']);

In [164]:
def correct_floor(df):
    df.loc[((df['HouseFloor'] > 80) & ((df['Floor'] >= 17) | (df['Floor'] == None))), 'HouseFloor'] = 17
    df.loc[(df['HouseFloor'] > 80) & (df['Floor'] < 17), 'HouseFloor'] = 9
    df.loc[df['HouseFloor'] == 0, 'HouseFloor'] = np.round(df.loc[df['HouseFloor'] != 0, 'HouseFloor'].mean())
    df.loc[(df['Floor'] > df['HouseFloor']) | (df['Floor'] == 0) | (df['HouseFloor'] == 0), 'HouseFloor'] = df['Floor']
    return df

In [165]:
train['Floor'].describe()

count    8000.000000
mean        8.492375
std         5.221240
min         1.000000
25%         4.000000
50%         7.000000
75%        12.000000
max        42.000000
Name: Floor, dtype: float64

In [166]:
train['HouseFloor'].describe()

count    8000.000000
mean       13.541000
std         5.765499
min         1.000000
25%         9.000000
50%        14.000000
75%        17.000000
max        48.000000
Name: HouseFloor, dtype: float64

##### DistrictId

In [167]:
train['DistrictId'].describe()

count    8000.000000
mean       50.493625
std        43.691588
min         0.000000
25%        20.000000
50%        36.000000
75%        75.000000
max       209.000000
Name: DistrictId, dtype: float64

In [168]:
train['DistrictId'].nunique()

203

In [169]:
#plt.hist(train['DistrictId'], bins=205)

In [170]:
#Из графика очевидно, что некоторые районы значительно крупнее по своим размерам, чем другие.

In [171]:
train['DistrictId'].value_counts()

27     671
1      534
23     452
6      407
9      243
62     196
30     180
53     147
58     136
21     130
8      110
52     104
11      97
61      97
45      95
46      94
34      90
74      89
57      86
99      81
44      79
7       79
47      75
101     75
48      75
13      72
94      68
29      67
84      67
3       66
      ...
179      4
112      4
152      4
82       4
115      4
51       4
180      4
178      4
166      4
201      3
182      3
175      3
159      3
133      3
181      3
192      3
50       3
172      2
202      2
185      2
193      2
195      2
186      2
158      2
205      1
209      1
117      1
208      1
196      1
199      1
Name: DistrictId, Length: 203, dtype: int64

In [172]:
#Добавим новый признак Large_district - размер района по количеству в нём квартир (>180)

In [173]:
distr_size = (train['DistrictId'].value_counts() > (train['DistrictId'].count() * 0.02)).astype(int).reset_index()
distr_size.columns = ['DistrictId', 'Large_district']
distr_size

     DistrictId  Large_district
0            27               1
1             1               1
2            23               1
3             6               1
4             9               1
5            62               1
6            30               1
7            53               0
8            58               0
9            21               0
10            8               0
11           52               0
12           11               0
13           61               0
14           45               0
15           46               0
16           34               0
17           74               0
18           57               0
19           99               0
20           44               0
21            7               0
22           47               0
23          101               0
24           48               0
25           13               0
26           94               0
27           29               0
28           84               0
29            3               0
..          ...             ...
173         179               0
174         112               0
175         152               0
176          82               0
177         115               0
178          51               0
179         180               0
180         178               0
181         166               0
182         201               0
183         182               0
184         175               0
185         159               0
186         133               0
187         181               0
188         192               0
189          50               0
190         172               0
191         202               0
192         185               0
193         193               0
194         195               0
195         186               0
196         158               0
197         205               0
198         209               0
199         117               0
200         208               0
201         196               0
202         199               0

[203 rows x 2 columns]

In [174]:
def add_distr_size(df, distr_size):
    df = pd.merge(df, distr_size, on='DistrictId', how='left')
    df['Large_district'] = df['Large_district'].fillna(0)
    return df

In [175]:
train = add_distr_size(train, distr_size)

In [176]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 0 to 7999
Data columns (total 23 columns):
Id                   8000 non-null int64
DistrictId           8000 non-null int64
Rooms                8000 non-null float64
Square               8000 non-null float64
LifeSquare           8000 non-null float64
KitchenSquare        8000 non-null float64
Floor                8000 non-null int64
HouseFloor           8000 non-null float64
HouseYear            8000 non-null int64
Ecology_1            8000 non-null float64
Ecology_2            8000 non-null object
Ecology_3            8000 non-null object
Social_1             8000 non-null int64
Social_2             8000 non-null int64
Social_3             8000 non-null int64
Helthcare_2          8000 non-null int64
Shops_1              8000 non-null int64
Shops_2              8000 non-null object
Price                8000 non-null float64
Large_flat           8000 non-null int32
Median_lifesquare    8000 non-null float64
Kitchen_1            8000 non-null int32
Large_district       8000 non-null int32
dtypes: float64(8), int32(3), int64(9), object(3)
memory usage: 1.4+ MB

In [177]:
#Добавим новый признак Mean_price - средняя цена по району по количеству комнат

In [178]:
mean_price = train.groupby(['DistrictId', 'Rooms'], as_index=False)[['Price']].mean().rename(columns={'Price': 'Mean_price'})
mean_price

     DistrictId  Rooms     Mean_price
0             0    1.0  132458.560813
1             0    2.0  194975.316489
2             0    3.0  291539.129431
3             1    1.0  145389.263147
4             1    2.0  198659.725812
5             1    3.0  246940.712930
6             1    4.0  277290.705058
7             2    1.0  182361.807871
8             2    2.0  246284.797498
9             2    3.0  345217.050562
10            2    4.0  294405.899542
11            3    1.0  151924.375577
12            3    2.0  183439.434680
13            3    3.0  210148.885967
14            4    1.0  168150.110362
15            4    2.0  265977.430116
16            4    3.0  387732.800762
17            4    4.0  197302.241882
18            5    1.0  240410.958424
19            5    2.0  244299.929848
20            5    3.0  247356.071547
21            6    1.0  133407.643941
22            6    2.0  177089.191251
23            6    3.0  213456.026157
24            7    1.0  185101.836225
25            7    2.0  233490.821456
26            7    3.0  340497.843952
27            7    4.0  274959.672513
28            8    1.0  163035.576262
29            8    2.0  208381.954356
..          ...    ...            ...
605         188    4.0  552454.338658
606         189    1.0  228411.559126
607         189    2.0  225960.873190
608         189    3.0  335134.450010
609         190    2.0  380765.543594
610         190    3.0  547833.746502
611         191    1.0  185904.185737
612         191    3.0  313560.214377
613         191    4.0  405412.086233
614         192    1.0  137505.343314
615         192    2.0  211145.979862
616         193    1.0  130500.697853
617         193    2.0  181025.397125
618         194    2.0  224732.319843
619         194    3.0  478782.488421
620         194    4.0  319659.324785
621         195    3.0  486057.129888
622         195    4.0  479525.147323
623         196    2.0  336584.118092
624         199    3.0  432546.129741
625         200    1.0  245039.663085
626         200    2.0  244300.906533
627         200    3.0  548608.808262
628         201    1.0  341805.242387
629         201    2.0  261645.935295
630         202    2.0  502085.860162
631         202    3.0  286215.863552
632         205    1.0  220501.566180
633         208    2.0  428928.889005
634         209    1.0  140048.802277

[635 rows x 3 columns]

In [179]:
mean_price.count()

DistrictId    635
Rooms         635
Mean_price    635
dtype: int64

In [180]:
def add_mean_price(df, mean_price):
    df = pd.merge(df, mean_price, on=['DistrictId', 'Rooms'], how='left')
    return df

In [181]:
train = add_mean_price(train, mean_price)

In [182]:
train.head(5)

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1,Large_district,Mean_price
0,12473,58,2.0,65.271225,62.798045,1.0,3,3.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849.693542,0,22.588815,1,0,170872.153755
1,14050,146,2.0,45.091598,43.816601,1.0,5,18.0,2017,0.236108,B,B,16,3893,27,3,10,B,201549.998077,0,32.803769,1,0,247315.118089
2,3779,5,1.0,34.463114,20.561823,5.0,3,5.0,1960,0.150818,B,B,16,3433,4,4,5,B,158433.168775,0,20.307073,0,0,240410.958424
3,3762,90,3.0,61.931107,46.126389,5.0,4,5.0,1966,0.265089,B,B,37,5288,0,3,2,B,220194.818430,0,45.749262,0,0,340638.806841
4,358,1,1.0,42.670840,39.990203,1.0,8,17.0,1977,0.007122,B,B,1,264,0,0,1,B,125834.270291,0,39.990203,1,1,145389.263147

In [183]:
def correct_districtid(df):
    df = add_distr_size(df, distr_size)
    df = add_mean_price(df, mean_price)
    return df

In [184]:
train['DistrictId'].describe()

count    8000.000000
mean       50.493625
std        43.691588
min         0.000000
25%        20.000000
50%        36.000000
75%        75.000000
max       209.000000
Name: DistrictId, dtype: float64

##### Price

In [185]:
train['Price'].describe()

count      8000.000000
mean     214094.178589
std       92671.160116
min       59174.778028
25%      153996.751273
50%      192152.769521
75%      249135.462171
max      627525.072788
Name: Price, dtype: float64

In [186]:
train['Price'] = train['Price'].astype(np.int64)
train['Price']

0       210849
1       201549
2       158433
3       220194
4       125834
5       157822
6       159768
7       118200
8        92290
9       468595
10      199179
11      189565
12      402075
13      177097
14      162798
15      184885
16      312636
17       99530
18      171503
19      318227
20      260852
21      158341
22      349107
23      361744
24      186190
25      324303
26      238485
27      145057
28      129512
29      217267
         ...
7970    126277
7971    162335
7972    113913
7973    221431
7974    219577
7975    136120
7976    182452
7977    352400
7978    357531
7979    148406
7980    349860
7981    110750
7982     65547
7983    296679
7984    150538
7985    197796
7986    297735
7987    164122
7988     99110
7989    213426
7990    139897
7991    148458
7992    259369
7993    132806
7994    313163
7995    150136
7996    328680
7997    255102
7998    182236
7999    443365
Name: Price, Length: 8000, dtype: int64

In [187]:
#plt.hist(train['Price'], bins=20)

In [188]:
#def correct_price(df):
#    df['Price'] = df['Price'].astype(np.int64)
#    return df

In [189]:
train['Price'].describe()

count      8000.000000
mean     214093.679500
std       92671.162803
min       59174.000000
25%      153996.000000
50%      192152.000000
75%      249135.000000
max      627525.000000
Name: Price, dtype: float64

##### New feature

In [190]:
train.head(5)

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Shops_2,Price,Large_flat,Median_lifesquare,Kitchen_1,Large_district,Mean_price
0,12473,58,2.0,65.271225,62.798045,1.0,3,3.0,1977,0.437885,B,B,23,5735,3,0,5,B,210849,0,22.588815,1,0,170872.153755
1,14050,146,2.0,45.091598,43.816601,1.0,5,18.0,2017,0.236108,B,B,16,3893,27,3,10,B,201549,0,32.803769,1,0,247315.118089
2,3779,5,1.0,34.463114,20.561823,5.0,3,5.0,1960,0.150818,B,B,16,3433,4,4,5,B,158433,0,20.307073,0,0,240410.958424
3,3762,90,3.0,61.931107,46.126389,5.0,4,5.0,1966,0.265089,B,B,37,5288,0,3,2,B,220194,0,45.749262,0,0,340638.806841
4,358,1,1.0,42.670840,39.990203,1.0,8,17.0,1977,0.007122,B,B,1,264,0,0,1,B,125834,0,39.990203,1,1,145389.263147

In [191]:
#

In [192]:
train['Mean_price'].describe()

count      8000.000000
mean     214094.178589
std       75695.896366
min       84250.557673
25%      164846.378511
50%      198659.725812
75%      246940.712930
max      595128.195352
Name: Mean_price, dtype: float64

In [193]:
corr_matrix = train.corr()
corr_matrix['Price'].sort_values(ascending=False)

Price                1.000000
Mean_price           0.816823
Rooms                0.584069
Square               0.582680
LifeSquare           0.425682
Median_lifesquare    0.340562
KitchenSquare        0.315824
Social_1             0.267954
DistrictId           0.264687
Helthcare_2          0.254505
Social_2             0.243379
Large_flat           0.231922
Shops_1              0.184092
Floor                0.129984
HouseFloor           0.110599
Social_3             0.074765
HouseYear            0.035796
Id                   0.021515
Ecology_1           -0.061364
Kitchen_1           -0.182829
Large_district      -0.383393
Name: Price, dtype: float64

In [194]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 0 to 7999
Data columns (total 24 columns):
Id                   8000 non-null int64
DistrictId           8000 non-null int64
Rooms                8000 non-null float64
Square               8000 non-null float64
LifeSquare           8000 non-null float64
KitchenSquare        8000 non-null float64
Floor                8000 non-null int64
HouseFloor           8000 non-null float64
HouseYear            8000 non-null int64
Ecology_1            8000 non-null float64
Ecology_2            8000 non-null object
Ecology_3            8000 non-null object
Social_1             8000 non-null int64
Social_2             8000 non-null int64
Social_3             8000 non-null int64
Helthcare_2          8000 non-null int64
Shops_1              8000 non-null int64
Shops_2              8000 non-null object
Price                8000 non-null int64
Large_flat           8000 non-null int32
Median_lifesquare    8000 non-null float64
Kitchen_1            8000 non-null int32
Large_district       8000 non-null int32
Mean_price           8000 non-null float64
dtypes: float64(8), int32(3), int64(10), object(3)
memory usage: 1.4+ MB

In [195]:
#

In [196]:
def prepare_data(df):
    df = correct_healthcare_1(df)
    df = correct_houseyear(df)
    df = correct_rooms(df)
    df = correct_lifesquare(df)
    df = correct_square(df)
    df = correct_kitchensquare(df)
    df = correct_floor(df)
    df = correct_districtid(df)
    #df = correct_price(df)
    return df

In [197]:
#train = prepare_data(train)

In [198]:
valid = prepare_data(valid)

### Model

In [199]:
from sklearn.ensemble import RandomForestRegressor as RF

In [200]:
model = RF(n_estimators=100, max_depth=11, random_state=42)

In [201]:
feats = ['DistrictId',
         'Rooms',
         'Square',
         'LifeSquare',
         'KitchenSquare',
         'Median_lifesquare',
         'Floor',
         'HouseFloor',
         'HouseYear',
         'Ecology_1',
         'Social_1',
         'Helthcare_2',
         'Large_district',
         'Large_flat',
         #'Mean_price',
         'Kitchen_1',
         'Shops_1'
        ]

In [202]:
model.fit(train.loc[:, feats], train['Price'])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=11,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [203]:
from sklearn.metrics import r2_score as r2

In [204]:
def get_prediction(model, df, feats=feats, evaluate='Yes'):
    pred = model.predict(df.loc[:, feats])
    if evaluate == 'Yes':
        r2_value = r2(df['Price'], pred)
        print('R2: {}'.format(r2_value))
    return pred

In [205]:
pred_train = get_prediction(model=model, df=train)

R2: 0.849387260101031

In [206]:
pred_valid = get_prediction(model=model, df=valid)

R2: 0.6968771872839918

In [207]:
train['Price'].describe()

count      8000.000000
mean     214093.679500
std       92671.162803
min       59174.000000
25%      153996.000000
50%      192152.000000
75%      249135.000000
max      627525.000000
Name: Price, dtype: float64

In [208]:
valid['Price'].describe()

count      2000.000000
mean     214317.572638
std       93695.624345
min       60502.583500
25%      153360.983329
50%      193026.691821
75%      248875.567286
max      633233.466570
Name: Price, dtype: float64

In [209]:
# Test

In [210]:
test = pd.read_csv('test.csv')

In [211]:
test.shape

(5000, 19)

In [212]:
test = prepare_data(test)

In [213]:
test['Price'] = get_prediction(model, test, feats=feats, evaluate='No')

In [214]:
test.loc[:, ['Id', 'Price']].to_csv('DGerman_predictions.csv', index=False)